packages:
  base: !include ../base/complete.yaml
  hardware: !include ../hardware/sense360_core_ceiling.yaml
  presence_sensor: !include ../hardware/presence_ld2450.yaml
  profile: !include ../features/presence_advanced_profile.yaml

substitutions:
  friendly_name: Sense360 Ceiling Presence
  device_name: sense360-ceiling-presence
  timezone: "UTC"

light:
  - platform: partition
    id: ceiling_status
    name: "${friendly_name} Halo"
    segments:
      - id: led_one
        from: 0
        to: 0
    default_transition_length: 500ms
