---
substitutions:
  fallback_ssid: "${device_name} FB"

wifi:
  networks:
    - ssid: !secret wifi_ssid
      password: !secret wifi_password
  fast_connect: true
  power_save_mode: none
  ap:
    ssid: "${fallback_ssid}"
    password: "${fallback_ap_password}"

captive_portal:
