substitutions:
  fallback_ssid: "${device_name} FB"
  # Default fallback AP password - can be overridden in product files
  fallback_ap_password: "Sense360Fallback"

wifi:
  networks:
    - ssid: !secret wifi_ssid
      password: !secret wifi_password
  fast_connect: true
  # Note: power_save_mode: none is incompatible with esp32_ble/bluetooth_proxy
  # Using light mode for better compatibility while maintaining reasonable performance
  power_save_mode: light
  ap:
    ssid: "${fallback_ssid}"
    password: "${fallback_ap_password}"

captive_portal:
