---
# ============================================================================
# SENSE360 AIRIQ MODULE - CEILING VARIANT
# ============================================================================
# SKU: S360-AIR-C
#
# Comprehensive air quality monitoring module for ceiling-mounted installations.
#
# Sensors:
# - SGP41 (I2C 0x59): VOC and NOx Index
# - SCD41 (I2C 0x62): CO2, Temperature, Humidity
# - BMP390 (I2C 0x77): Barometric Pressure
# - MiCS4514: Formaldehyde, Ozone detection
# - SEN55 (I2C 0x69): PM1.0, PM2.5, PM4.0, PM10, Temperature, Humidity
#
# Expansion Bus Connection (Ceiling):
#   Pin 4 (SDA) → GPIO21
#   Pin 5 (SCL) → GPIO18
#   Pin 2 (3.3V) → Power
#   Pin 1 (GND) → Ground
#
# Power Requirements: 3.3V / 500mA max
# ============================================================================

substitutions:
  module_sku: S360-AIR-C
  module_variant: ceiling

  # I2C Configuration (Ceiling uses expansion I2C bus)
  airiq_i2c_sda: GPIO21
  airiq_i2c_scl: GPIO18
  airiq_i2c_id: i2c_airiq

  # Sensor update intervals
  airiq_sen55_update: 30s
  airiq_scd41_update: 30s
  airiq_sgp41_update: 30s
  airiq_bmp390_update: 60s

  # CO2 calibration settings
  co2_auto_calibration: "true"

# I2C Bus Configuration
i2c:
  - id: ${airiq_i2c_id}
    sda: ${airiq_i2c_sda}
    scl: ${airiq_i2c_scl}
    scan: true
    frequency: 100kHz

# ============================================================================
# SENSORS
# ============================================================================
sensor:
  # SEN55 - All-in-One Environmental Sensor
  - platform: sen5x
    id: sen55_sensor
    i2c_id: ${airiq_i2c_id}
    address: 0x69

    pm_1_0:
      id: airiq_pm1_0
      name: "${friendly_name} PM1.0"
      internal: true
      accuracy_decimals: 1
      filters:
        - throttle: ${airiq_sen55_update}

    pm_2_5:
      id: airiq_pm2_5
      name: "${friendly_name} PM2.5"
      internal: true
      accuracy_decimals: 1
      filters:
        - throttle: ${airiq_sen55_update}

    pm_4_0:
      id: airiq_pm4_0
      name: "${friendly_name} PM4.0"
      internal: true
      accuracy_decimals: 1
      filters:
        - throttle: ${airiq_sen55_update}

    pm_10_0:
      id: airiq_pm10_0
      name: "${friendly_name} PM10"
      internal: true
      accuracy_decimals: 1
      filters:
        - throttle: ${airiq_sen55_update}

    temperature:
      id: airiq_sen55_temperature
      name: "${friendly_name} SEN55 Temperature"
      internal: true
      accuracy_decimals: 1
      filters:
        - throttle: ${airiq_sen55_update}

    humidity:
      id: airiq_sen55_humidity
      name: "${friendly_name} SEN55 Humidity"
      internal: true
      accuracy_decimals: 1
      filters:
        - throttle: ${airiq_sen55_update}

    voc:
      id: airiq_voc_index
      name: "${friendly_name} VOC Index"
      internal: true
      accuracy_decimals: 0
      filters:
        - throttle: ${airiq_sen55_update}

    nox:
      id: airiq_nox_index
      name: "${friendly_name} NOx Index"
      internal: true
      accuracy_decimals: 0
      filters:
        - throttle: ${airiq_sen55_update}

    temperature_compensation:
      offset: 0
      normalized_offset_slope: 0
      time_constant: 0

    acceleration_mode: low
    store_baseline: true
    auto_cleaning_interval: 604800s

  # SCD41 - CO2 Sensor
  - platform: scd4x
    id: scd41_sensor
    i2c_id: ${airiq_i2c_id}
    address: 0x62

    co2:
      id: airiq_co2
      name: "${friendly_name} CO2"
      internal: true
      accuracy_decimals: 0
      filters:
        - throttle: ${airiq_scd41_update}

    temperature:
      id: airiq_scd41_temperature
      name: "${friendly_name} SCD41 Temperature"
      internal: true
      accuracy_decimals: 1
      filters:
        - throttle: ${airiq_scd41_update}

    humidity:
      id: airiq_scd41_humidity
      name: "${friendly_name} SCD41 Humidity"
      internal: true
      accuracy_decimals: 1
      filters:
        - throttle: ${airiq_scd41_update}

    automatic_self_calibration: ${co2_auto_calibration}
    measurement_mode: periodic
    update_interval: ${airiq_scd41_update}

  # BMP390 - Barometric Pressure
  - platform: bmp3xx
    id: bmp390_sensor
    i2c_id: ${airiq_i2c_id}
    address: 0x77

    temperature:
      id: airiq_bmp390_temperature
      name: "${friendly_name} BMP390 Temperature"
      internal: true
      oversampling: 2x

    pressure:
      id: airiq_pressure
      name: "${friendly_name} Pressure"
      internal: true
      oversampling: 2x

    update_interval: ${airiq_bmp390_update}

# ============================================================================
# Globals for Air Quality Calculations
# ============================================================================
globals:
  - id: airiq_aqi_value
    type: int
    restore_value: false
    initial_value: '0'

  - id: airiq_temperature_value
    type: float
    restore_value: false
    initial_value: '20.0'

  - id: airiq_humidity_value
    type: float
    restore_value: false
    initial_value: '50.0'

# ============================================================================
# Interval for Sensor Data Processing
# ============================================================================
interval:
  - interval: 30s
    then:
      - lambda: |-
          // Average temperature from sensors
          float temp_sen55 = id(airiq_sen55_temperature).state;
          float temp_scd41 = id(airiq_scd41_temperature).state;
          int temp_count = 0;
          float temp_sum = 0.0f;

          if (!std::isnan(temp_sen55)) { temp_sum += temp_sen55; temp_count++; }
          if (!std::isnan(temp_scd41)) { temp_sum += temp_scd41; temp_count++; }

          if (temp_count > 0) {
            id(airiq_temperature_value) = temp_sum / temp_count;
          }

          // Average humidity from sensors
          float hum_sen55 = id(airiq_sen55_humidity).state;
          float hum_scd41 = id(airiq_scd41_humidity).state;
          int hum_count = 0;
          float hum_sum = 0.0f;

          if (!std::isnan(hum_sen55)) { hum_sum += hum_sen55; hum_count++; }
          if (!std::isnan(hum_scd41)) { hum_sum += hum_scd41; hum_count++; }

          if (hum_count > 0) {
            id(airiq_humidity_value) = hum_sum / hum_count;
          }

          // Calculate AQI based on PM2.5
          float pm25 = id(airiq_pm2_5).state;
          int aqi = 0;

          if (!std::isnan(pm25)) {
            if (pm25 <= 12.0f) {
              aqi = (int)((50.0f / 12.0f) * pm25);
            } else if (pm25 <= 35.4f) {
              aqi = (int)(((100.0f - 51.0f) / (35.4f - 12.1f)) * (pm25 - 12.1f) + 51.0f);
            } else if (pm25 <= 55.4f) {
              aqi = (int)(((150.0f - 101.0f) / (55.4f - 35.5f)) * (pm25 - 35.5f) + 101.0f);
            } else if (pm25 <= 150.4f) {
              aqi = (int)(((200.0f - 151.0f) / (150.4f - 55.5f)) * (pm25 - 55.5f) + 151.0f);
            } else {
              aqi = (int)(((300.0f - 201.0f) / (250.4f - 150.5f)) * (pm25 - 150.5f) + 201.0f);
            }
          }

          id(airiq_aqi_value) = aqi;

text_sensor:
  - platform: template
    name: "${friendly_name} AirIQ Module SKU"
    lambda: |-
      return {"${module_sku}"};
    update_interval: never
    entity_category: diagnostic
