---
# ============================================================================
# SENSE360 AIRLQ EXPANSION MODULE - HARDWARE DRIVER
# ============================================================================
# Comprehensive air quality monitoring expansion module with multiple sensors:
# - SGP4x (I2C 0x59): VOC Index, Raw VOC, NOx Index (VOC/Air Quality Sensor)
# - SCD4x (I2C 0x62): CO2, Temperature, Humidity (CO2 Sensor)
# - SFA30 (I2C 0x5D): Formaldehyde concentration (Formaldehyde Sensor Module)
# - SPS30 (I2C 0x69): PM1.0, PM2.5, PM4.0, PM10, Particle Count (Particulate Matter)
# - BMP390L (I2C 0x77): Pressure, Temperature (Digital Pressure Sensor)
#
# Additional Features:
# - AirLQ_Status_Led: Status indicator LED
# - AirLQ_Led: Activity/alert indicator LED
#
# This file provides the base hardware setup. User-facing entities are defined
# in the feature profile files (basic or advanced).
#
# Expansion Bus Connection (from Core via MCS_SE0023 connector):
#   ext0_SDA → GPIO39 (I2C_SDA)
#   ext0_SCL → GPIO40 (I2C_SCL)
#   AirLQ_Status_Led → GPIO6 (Expansion GPIO 1)
#   AirLQ_Led → GPIO7 (Expansion GPIO 2)
#   3.3V → Power
#   GND → Ground
#
# I2C Address Map:
#   0x59 - SGP4x (VOC/Air Quality)
#   0x5D - SFA30 (Formaldehyde)
#   0x62 - SCD4x (CO2)
#   0x69 - SPS30 (Particulate Matter)
#   0x77 - BMP390L (Pressure)
#
# Power Requirements: 3.3V / 600mA max (SPS30 fan draws most current)
# ============================================================================

substitutions:
  # I2C bus ID (uses i2c0 from core hardware by default)
  # Override with airlq_i2c_id substitution if using different bus
  airlq_i2c_id: i2c0

  # LED GPIO Configuration
  airlq_status_led_pin: GPIO6
  airlq_led_pin: GPIO7

  # Sensor update intervals
  airlq_sgp4x_update: 30s
  airlq_scd4x_update: 30s
  airlq_sfa30_update: 30s
  airlq_sps30_update: 30s
  airlq_bmp390_update: 60s

  # CO2 calibration settings
  airlq_co2_auto_calibration: "true"

  # SPS30 auto-cleaning interval (7 days default)
  airlq_sps30_cleaning_interval: "604800s"

# ============================================================================
# LED OUTPUTS
# ============================================================================
output:
  - platform: gpio
    id: airlq_status_led_output
    pin: ${airlq_status_led_pin}

  - platform: gpio
    id: airlq_led_output
    pin: ${airlq_led_pin}

light:
  # Status LED
  - platform: binary
    id: airlq_status_led
    name: "${friendly_name} AirLQ Status LED"
    output: airlq_status_led_output
    internal: true

  # Activity/Alert LED
  - platform: binary
    id: airlq_activity_led
    name: "${friendly_name} AirLQ LED"
    output: airlq_led_output
    internal: true

# ============================================================================
# SENSORS
# ============================================================================
sensor:
  # ============================================================================
  # SGP4x - VOC/Air Quality Sensor (Sensirion)
  # I2C Address: 0x59
  # ============================================================================
  - platform: sgp4x
    id: sgp4x_sensor
    i2c_id: ${airlq_i2c_id}
    address: 0x59

    voc:
      id: airlq_voc_index
      name: "${friendly_name} VOC Index"
      internal: true
      accuracy_decimals: 0
      filters:
        - throttle: ${airlq_sgp4x_update}

    nox:
      id: airlq_nox_index
      name: "${friendly_name} NOx Index"
      internal: true
      accuracy_decimals: 0
      filters:
        - throttle: ${airlq_sgp4x_update}

    # Compensation from SCD4x for improved accuracy
    compensation:
      temperature_source: airlq_scd4x_temperature
      humidity_source: airlq_scd4x_humidity

    # Store baseline for faster startup
    store_baseline: true

    update_interval: ${airlq_sgp4x_update}

  # ============================================================================
  # SCD4x - CO2 Sensor (Sensirion SCD40/SCD41)
  # I2C Address: 0x62
  # ============================================================================
  - platform: scd4x
    id: scd4x_sensor
    i2c_id: ${airlq_i2c_id}
    address: 0x62

    co2:
      id: airlq_co2
      name: "${friendly_name} CO2"
      internal: true
      accuracy_decimals: 0
      filters:
        - throttle: ${airlq_scd4x_update}

    temperature:
      id: airlq_scd4x_temperature
      name: "${friendly_name} SCD4x Temperature"
      internal: true
      accuracy_decimals: 1
      filters:
        - throttle: ${airlq_scd4x_update}

    humidity:
      id: airlq_scd4x_humidity
      name: "${friendly_name} SCD4x Humidity"
      internal: true
      accuracy_decimals: 1
      filters:
        - throttle: ${airlq_scd4x_update}

    # Automatic self-calibration
    automatic_self_calibration: ${airlq_co2_auto_calibration}

    # Measurement mode
    measurement_mode: periodic
    update_interval: ${airlq_scd4x_update}

  # ============================================================================
  # SFA30 - Formaldehyde Sensor Module (Sensirion)
  # I2C Address: 0x5D
  # ============================================================================
  - platform: sfa30
    id: sfa30_sensor
    i2c_id: ${airlq_i2c_id}
    address: 0x5D

    formaldehyde:
      id: airlq_formaldehyde
      name: "${friendly_name} Formaldehyde"
      internal: true
      accuracy_decimals: 2
      filters:
        - throttle: ${airlq_sfa30_update}

    temperature:
      id: airlq_sfa30_temperature
      name: "${friendly_name} SFA30 Temperature"
      internal: true
      accuracy_decimals: 1
      filters:
        - throttle: ${airlq_sfa30_update}

    humidity:
      id: airlq_sfa30_humidity
      name: "${friendly_name} SFA30 Humidity"
      internal: true
      accuracy_decimals: 1
      filters:
        - throttle: ${airlq_sfa30_update}

    update_interval: ${airlq_sfa30_update}

  # ============================================================================
  # SPS30 - Particulate Matter Sensor (Sensirion)
  # I2C Address: 0x69
  # ============================================================================
  - platform: sps30
    id: sps30_sensor
    i2c_id: ${airlq_i2c_id}
    address: 0x69

    pm_1_0:
      id: airlq_pm1_0
      name: "${friendly_name} PM1.0"
      internal: true
      accuracy_decimals: 1
      filters:
        - throttle: ${airlq_sps30_update}

    pm_2_5:
      id: airlq_pm2_5
      name: "${friendly_name} PM2.5"
      internal: true
      accuracy_decimals: 1
      filters:
        - throttle: ${airlq_sps30_update}

    pm_4_0:
      id: airlq_pm4_0
      name: "${friendly_name} PM4.0"
      internal: true
      accuracy_decimals: 1
      filters:
        - throttle: ${airlq_sps30_update}

    pm_10_0:
      id: airlq_pm10_0
      name: "${friendly_name} PM10"
      internal: true
      accuracy_decimals: 1
      filters:
        - throttle: ${airlq_sps30_update}

    # Particle counts (number concentration)
    pmc_0_5:
      id: airlq_pmc0_5
      name: "${friendly_name} PMC 0.5"
      internal: true
      accuracy_decimals: 0
      filters:
        - throttle: ${airlq_sps30_update}

    pmc_1_0:
      id: airlq_pmc1_0
      name: "${friendly_name} PMC 1.0"
      internal: true
      accuracy_decimals: 0
      filters:
        - throttle: ${airlq_sps30_update}

    pmc_2_5:
      id: airlq_pmc2_5
      name: "${friendly_name} PMC 2.5"
      internal: true
      accuracy_decimals: 0
      filters:
        - throttle: ${airlq_sps30_update}

    pmc_4_0:
      id: airlq_pmc4_0
      name: "${friendly_name} PMC 4.0"
      internal: true
      accuracy_decimals: 0
      filters:
        - throttle: ${airlq_sps30_update}

    pmc_10_0:
      id: airlq_pmc10_0
      name: "${friendly_name} PMC 10"
      internal: true
      accuracy_decimals: 0
      filters:
        - throttle: ${airlq_sps30_update}

    # Typical particle size
    pm_size:
      id: airlq_pm_size
      name: "${friendly_name} Typical Particle Size"
      internal: true
      accuracy_decimals: 2
      filters:
        - throttle: ${airlq_sps30_update}

    # Auto cleaning interval (fan self-cleaning)
    auto_cleaning_interval: ${airlq_sps30_cleaning_interval}

    update_interval: ${airlq_sps30_update}

  # ============================================================================
  # BMP390L - Digital Pressure Sensor (Bosch)
  # I2C Address: 0x77
  # ============================================================================
  - platform: bmp3xx_i2c
    id: bmp390_sensor
    i2c_id: ${airlq_i2c_id}
    address: 0x77

    pressure:
      id: airlq_pressure
      name: "${friendly_name} Pressure"
      internal: true
      accuracy_decimals: 1
      filters:
        - throttle: ${airlq_bmp390_update}
      oversampling: 4x

    temperature:
      id: airlq_bmp390_temperature
      name: "${friendly_name} BMP390 Temperature"
      internal: true
      accuracy_decimals: 1
      filters:
        - throttle: ${airlq_bmp390_update}
      oversampling: 2x

    # IIR filter for noise reduction
    iir_filter: 4x

    update_interval: ${airlq_bmp390_update}

# ============================================================================
# Globals for Air Quality Calculations
# ============================================================================
globals:
  # Air Quality Index (0-500 scale, US EPA standard)
  - id: airlq_aqi_value
    type: int
    restore_value: false
    initial_value: '0'

  # Primary temperature source (averaged from sensors)
  - id: airlq_temperature_value
    type: float
    restore_value: false
    initial_value: '20.0'

  # Primary humidity source (averaged from sensors)
  - id: airlq_humidity_value
    type: float
    restore_value: false
    initial_value: '50.0'

  # Formaldehyde alert threshold (ppb)
  - id: airlq_hcho_alert_threshold
    type: float
    restore_value: false
    initial_value: '100.0'

  # Air quality status (0=good, 1=moderate, 2=unhealthy, 3=very_unhealthy, 4=hazardous)
  - id: airlq_status
    type: int
    restore_value: false
    initial_value: '0'

# ============================================================================
# Interval for Sensor Data Processing
# ============================================================================
interval:
  - interval: 30s
    then:
      - lambda: |-
          // Average temperature from all available sensors
          float temp_scd4x = id(airlq_scd4x_temperature).state;
          float temp_sfa30 = id(airlq_sfa30_temperature).state;
          float temp_bmp390 = id(airlq_bmp390_temperature).state;
          int temp_count = 0;
          float temp_sum = 0.0f;

          if (!std::isnan(temp_scd4x)) {
            temp_sum += temp_scd4x;
            temp_count++;
          }
          if (!std::isnan(temp_sfa30)) {
            temp_sum += temp_sfa30;
            temp_count++;
          }
          if (!std::isnan(temp_bmp390)) {
            temp_sum += temp_bmp390;
            temp_count++;
          }

          if (temp_count > 0) {
            id(airlq_temperature_value) = temp_sum / temp_count;
          }

          // Average humidity from SCD4x and SFA30
          float hum_scd4x = id(airlq_scd4x_humidity).state;
          float hum_sfa30 = id(airlq_sfa30_humidity).state;
          int hum_count = 0;
          float hum_sum = 0.0f;

          if (!std::isnan(hum_scd4x)) {
            hum_sum += hum_scd4x;
            hum_count++;
          }
          if (!std::isnan(hum_sfa30)) {
            hum_sum += hum_sfa30;
            hum_count++;
          }

          if (hum_count > 0) {
            id(airlq_humidity_value) = hum_sum / hum_count;
          }

          // Calculate AQI based on PM2.5 (simplified US EPA breakpoints)
          float pm25 = id(airlq_pm2_5).state;
          int aqi = 0;

          if (!std::isnan(pm25)) {
            if (pm25 <= 12.0f) {
              aqi = (int)((50.0f / 12.0f) * pm25);
            } else if (pm25 <= 35.4f) {
              aqi = (int)(((100.0f - 51.0f) / (35.4f - 12.1f)) * (pm25 - 12.1f) + 51.0f);
            } else if (pm25 <= 55.4f) {
              aqi = (int)(((150.0f - 101.0f) / (55.4f - 35.5f)) * (pm25 - 35.5f) + 101.0f);
            } else if (pm25 <= 150.4f) {
              aqi = (int)(((200.0f - 151.0f) / (150.4f - 55.5f)) * (pm25 - 55.5f) + 151.0f);
            } else if (pm25 <= 250.4f) {
              aqi = (int)(((300.0f - 201.0f) / (250.4f - 150.5f)) * (pm25 - 150.5f) + 201.0f);
            } else {
              aqi = (int)(((500.0f - 301.0f) / (500.4f - 250.5f)) * (pm25 - 250.5f) + 301.0f);
            }
          }

          id(airlq_aqi_value) = aqi;

          // Determine overall air quality status
          int status = 0;  // Good
          float co2 = id(airlq_co2).state;
          float voc = id(airlq_voc_index).state;
          float hcho = id(airlq_formaldehyde).state;

          // Check CO2 levels (ppm)
          if (!std::isnan(co2)) {
            if (co2 > 2000) status = std::max(status, 3);      // Very unhealthy
            else if (co2 > 1500) status = std::max(status, 2); // Unhealthy
            else if (co2 > 1000) status = std::max(status, 1); // Moderate
          }

          // Check VOC Index (1-500 scale)
          if (!std::isnan(voc)) {
            if (voc > 400) status = std::max(status, 3);      // Very unhealthy
            else if (voc > 250) status = std::max(status, 2); // Unhealthy
            else if (voc > 150) status = std::max(status, 1); // Moderate
          }

          // Check formaldehyde (ppb)
          if (!std::isnan(hcho)) {
            if (hcho > 200) status = std::max(status, 3);     // Very unhealthy
            else if (hcho > 100) status = std::max(status, 2); // Unhealthy
            else if (hcho > 50) status = std::max(status, 1);  // Moderate
          }

          // Check AQI
          if (aqi > 200) status = std::max(status, 3);        // Very unhealthy
          else if (aqi > 100) status = std::max(status, 2);   // Unhealthy
          else if (aqi > 50) status = std::max(status, 1);    // Moderate

          id(airlq_status) = status;

          // Update status LED based on air quality
          if (status == 0) {
            // Good - LED off or steady
            id(airlq_status_led_output).turn_off();
          } else if (status >= 2) {
            // Unhealthy or worse - LED on
            id(airlq_status_led_output).turn_on();
          }

# ============================================================================
# Button for Manual SPS30 Fan Cleaning
# ============================================================================
button:
  - platform: template
    name: "${friendly_name} SPS30 Clean Fan"
    id: airlq_sps30_clean_button
    icon: mdi:fan
    internal: true
    on_press:
      then:
        - sps30.start_fan_autoclean: sps30_sensor
        - logger.log:
            level: INFO
            format: "AirLQ: SPS30 fan cleaning started"
