---
# ============================================================================
# SENSE360 BATHROOM EXPANSION MODULE - HARDWARE DRIVER
# ============================================================================
# Bathroom-specific air quality and ventilation monitoring:
# - SHT40 (I2C 0x44): Humidity (focus on spike detection for showers)
# - SCD41 (I2C 0x62): CO2 monitoring
# - SGP40 (I2C 0x59, optional): VOC/odor detection
# - BH1750 (I2C 0x23, optional): Light sensor for occupancy hints
#
# This file provides the base hardware setup. User-facing entities are defined
# in the bathroom_profile.yaml feature file.
#
# Expansion Bus Connection:
#   Pin 4 (SDA) → GPIO39
#   Pin 5 (SCL) → GPIO40
#   Pin 2 (3.3V) → Power
#   Pin 1 (GND) → Ground
#
# Power Requirements: 3.3V / 500mA max
# ============================================================================

substitutions:
  # I2C Configuration
  bathroom_i2c_sda: GPIO39
  bathroom_i2c_scl: GPIO40
  bathroom_i2c_id: i2c_bathroom

  # Sensor update intervals
  bathroom_sht40_update: 10s   # Fast updates for shower detection
  bathroom_scd41_update: 30s
  bathroom_sgp40_update: 10s
  bathroom_bh1750_update: 5s

  # Humidity thresholds
  shower_humidity_threshold: "75"      # Humidity % to detect shower
  shower_humidity_rate: "5"            # Rate of change to detect shower start
  mold_risk_humidity: "65"             # Sustained humidity for mold risk
  mold_risk_duration_minutes: "30"     # Duration for mold risk warning

# I2C Bus Configuration
i2c:
  - id: ${bathroom_i2c_id}
    sda: ${bathroom_i2c_sda}
    scl: ${bathroom_i2c_scl}
    scan: true
    frequency: 100kHz

# ============================================================================
# SENSORS
# ============================================================================
sensor:
  # ============================================================================
  # SHT40 - High-Accuracy Temperature/Humidity Sensor (Sensirion)
  # I2C Address: 0x44
  # Primary sensor for humidity spike detection
  # ============================================================================
  - platform: sht4x
    id: bathroom_sht40_sensor
    i2c_id: ${bathroom_i2c_id}
    address: 0x44

    temperature:
      id: bathroom_temperature
      name: "${friendly_name} Temperature"
      internal: true
      accuracy_decimals: 1
      filters:
        - throttle: ${bathroom_sht40_update}

    humidity:
      id: bathroom_humidity
      name: "${friendly_name} Humidity"
      internal: true
      accuracy_decimals: 1
      filters:
        - throttle: ${bathroom_sht40_update}

    precision: High
    heater_power: Off
    update_interval: ${bathroom_sht40_update}

  # ============================================================================
  # SCD41 - CO2 Sensor (Sensirion)
  # I2C Address: 0x62
  # ============================================================================
  - platform: scd4x
    id: bathroom_scd41_sensor
    i2c_id: ${bathroom_i2c_id}
    address: 0x62

    co2:
      id: bathroom_co2
      name: "${friendly_name} CO2"
      internal: true
      accuracy_decimals: 0
      filters:
        - throttle: ${bathroom_scd41_update}

    temperature:
      id: bathroom_scd41_temperature
      name: "${friendly_name} SCD41 Temperature"
      internal: true
      accuracy_decimals: 1
      filters:
        - throttle: ${bathroom_scd41_update}

    humidity:
      id: bathroom_scd41_humidity
      name: "${friendly_name} SCD41 Humidity"
      internal: true
      accuracy_decimals: 1
      filters:
        - throttle: ${bathroom_scd41_update}

    automatic_self_calibration: true
    measurement_mode: periodic
    update_interval: ${bathroom_scd41_update}

  # ============================================================================
  # SGP40 - VOC/Odor Sensor (Sensirion)
  # I2C Address: 0x59
  # Detects odors and bathroom-specific VOCs
  # ============================================================================
  - platform: sgp4x
    id: bathroom_sgp40_sensor
    i2c_id: ${bathroom_i2c_id}

    voc:
      id: bathroom_voc_index
      name: "${friendly_name} VOC Index"
      internal: true
      accuracy_decimals: 0
      filters:
        - throttle: ${bathroom_sgp40_update}

    # Compensation from SHT40 for better accuracy
    compensation:
      temperature_source: bathroom_temperature
      humidity_source: bathroom_humidity

    update_interval: ${bathroom_sgp40_update}

  # ============================================================================
  # BH1750 - Ambient Light Sensor (ROHM)
  # I2C Address: 0x23
  # Used for occupancy hints (light on = likely occupied)
  # ============================================================================
  - platform: bh1750
    id: bathroom_light_sensor
    i2c_id: ${bathroom_i2c_id}
    address: 0x23

    name: "${friendly_name} Illuminance"
    internal: true
    accuracy_decimals: 1
    update_interval: ${bathroom_bh1750_update}

  # ============================================================================
  # Calculated Sensors
  # ============================================================================
  # Humidity rate of change (for shower detection)
  - platform: template
    id: bathroom_humidity_rate
    name: "${friendly_name} Humidity Rate"
    internal: true
    unit_of_measurement: "%/min"
    accuracy_decimals: 1
    update_interval: 10s
    lambda: |-
      static float last_humidity = 0.0f;
      static unsigned long last_time = 0;

      float current_humidity = id(bathroom_humidity).state;
      unsigned long current_time = millis();

      if (std::isnan(current_humidity)) {
        return 0.0f;
      }

      if (last_time == 0) {
        last_humidity = current_humidity;
        last_time = current_time;
        return 0.0f;
      }

      float time_diff_min = (current_time - last_time) / 60000.0f;
      float humidity_diff = current_humidity - last_humidity;

      last_humidity = current_humidity;
      last_time = current_time;

      if (time_diff_min > 0) {
        return humidity_diff / time_diff_min;
      }
      return 0.0f;

# ============================================================================
# Globals for Bathroom Logic
# ============================================================================
globals:
  # Shower detected flag
  - id: bathroom_shower_active
    type: bool
    restore_value: false
    initial_value: 'false'

  # Mold risk level (0=none, 1=low, 2=medium, 3=high)
  - id: bathroom_mold_risk
    type: int
    restore_value: false
    initial_value: '0'

  # High humidity duration counter (minutes)
  - id: bathroom_high_humidity_minutes
    type: int
    restore_value: false
    initial_value: '0'

  # Odor detected flag
  - id: bathroom_odor_detected
    type: bool
    restore_value: false
    initial_value: 'false'

  # Light-based occupancy hint
  - id: bathroom_light_on
    type: bool
    restore_value: false
    initial_value: 'false'

  # Post-shower ventilation timer (minutes remaining)
  - id: bathroom_post_shower_timer
    type: int
    restore_value: false
    initial_value: '0'

  # Recommended fan speed (0-100)
  - id: bathroom_fan_recommendation
    type: int
    restore_value: false
    initial_value: '0'

# ============================================================================
# Binary Sensors
# ============================================================================
binary_sensor:
  # Shower detection
  - platform: template
    id: bathroom_shower_sensor
    name: "${friendly_name} Shower Active"
    internal: true
    device_class: moisture
    lambda: |-
      return id(bathroom_shower_active);

  # Mold risk warning
  - platform: template
    id: bathroom_mold_warning
    name: "${friendly_name} Mold Risk"
    internal: true
    device_class: problem
    lambda: |-
      return id(bathroom_mold_risk) >= 2;

  # Odor detection
  - platform: template
    id: bathroom_odor_sensor
    name: "${friendly_name} Odor Detected"
    internal: true
    device_class: gas
    lambda: |-
      return id(bathroom_odor_detected);

# ============================================================================
# Interval for Bathroom Logic
# ============================================================================
interval:
  # Fast interval for shower detection
  - interval: 10s
    then:
      - lambda: |-
          float humidity = id(bathroom_humidity).state;
          float humidity_rate = id(bathroom_humidity_rate).state;
          float voc = id(bathroom_voc_index).state;
          float lux = id(bathroom_light_sensor).state;

          if (std::isnan(humidity)) return;

          // Shower detection logic
          bool was_shower_active = id(bathroom_shower_active);

          // Start shower detection: rapid humidity increase OR high humidity
          if (!was_shower_active) {
            if (humidity_rate > ${shower_humidity_rate} || humidity > ${shower_humidity_threshold}) {
              id(bathroom_shower_active) = true;
              ESP_LOGI("bathroom", "Shower started - humidity: %.1f%%, rate: %.1f%%/min",
                       humidity, humidity_rate);
            }
          } else {
            // End shower detection: humidity dropping below threshold
            if (humidity < (${shower_humidity_threshold} - 10) && humidity_rate < 0) {
              id(bathroom_shower_active) = false;
              // Start post-shower timer (15 minutes default)
              id(bathroom_post_shower_timer) = 15;
              ESP_LOGI("bathroom", "Shower ended - starting post-shower ventilation");
            }
          }

          // Odor detection (VOC index > 150 indicates odor)
          if (!std::isnan(voc)) {
            id(bathroom_odor_detected) = (voc > 150);
          }

          // Light-based occupancy hint
          if (!std::isnan(lux)) {
            id(bathroom_light_on) = (lux > 50.0f);
          }

          // Calculate fan recommendation
          int fan_speed = 0;

          if (id(bathroom_shower_active)) {
            // During shower: high speed
            fan_speed = 100;
          } else if (id(bathroom_post_shower_timer) > 0) {
            // Post-shower: medium-high speed
            fan_speed = 70;
          } else if (id(bathroom_odor_detected)) {
            // Odor detected: medium speed
            fan_speed = 50;
          } else if (humidity > 60.0f) {
            // Elevated humidity: low speed
            fan_speed = 30;
          }

          id(bathroom_fan_recommendation) = fan_speed;

  # Slow interval for mold risk calculation
  - interval: 1min
    then:
      - lambda: |-
          float humidity = id(bathroom_humidity).state;

          if (std::isnan(humidity)) return;

          // Track duration of high humidity
          if (humidity > ${mold_risk_humidity}) {
            id(bathroom_high_humidity_minutes)++;
          } else {
            // Reset counter when humidity drops
            if (id(bathroom_high_humidity_minutes) > 0) {
              id(bathroom_high_humidity_minutes) = 0;
            }
          }

          // Calculate mold risk level
          int minutes = id(bathroom_high_humidity_minutes);
          if (minutes >= ${mold_risk_duration_minutes} * 2) {
            id(bathroom_mold_risk) = 3;  // High risk
          } else if (minutes >= ${mold_risk_duration_minutes}) {
            id(bathroom_mold_risk) = 2;  // Medium risk
          } else if (minutes >= ${mold_risk_duration_minutes} / 2) {
            id(bathroom_mold_risk) = 1;  // Low risk
          } else {
            id(bathroom_mold_risk) = 0;  // No risk
          }

          // Decrement post-shower timer
          if (id(bathroom_post_shower_timer) > 0) {
            id(bathroom_post_shower_timer)--;
          }
