---
# ============================================================================
# SENSE360 COMFORT CEILING EXPANSION MODULE - HARDWARE DRIVER
# ============================================================================
# Ceiling-mount environmental comfort monitoring module with:
# - VEML7700 (I2C 0x10): High-resolution ambient light sensor with interrupt
# - SHT4x (I2C 0x44): High-accuracy temperature and humidity sensor
#
# This is a simplified comfort module designed for ceiling installation,
# optimized for ambient light and climate monitoring without pressure/gas sensors.
#
# Schematic Reference: Comfort_Module/ceiling_sch
#
# ============================================================================
# CONNECTOR PINOUT (J1 - 5-pin)
# ============================================================================
# Pin | Signal    | Core GPIO | Description
# ----|-----------|-----------|------------------------------------------
#  1  | +3.3V     | -         | Power supply (3.3V regulated)
#  2  | ALS_INT   | GPIO3     | Ambient light sensor interrupt (active low)
#  3  | I2C_SDA   | GPIO39    | I2C data line (primary bus)
#  4  | I2C_SCL   | GPIO40    | I2C clock line (primary bus)
#  5  | GND       | -         | Ground reference
#
# ============================================================================
# I2C ADDRESS MAP
# ============================================================================
# Address | Device  | Function
# --------|---------|--------------------------------------------------
# 0x10    | VEML7700| Ambient light sensor (lux, white channel)
# 0x44    | SHT4x   | Temperature and humidity sensor
#
# Power Requirements: 3.3V / 50mA typical, 80mA max
# ============================================================================

substitutions:
  # I2C Configuration (defaults to Sense360 core halo bus)
  comfort_ceiling_i2c_sda: GPIO39
  comfort_ceiling_i2c_scl: GPIO40
  comfort_ceiling_i2c_id: halo_i2c

  # ALS Interrupt pin (directly to core GPIO)
  comfort_ceiling_als_int_pin: GPIO3

  # Sensor update intervals
  comfort_ceiling_veml7700_update: 10s
  comfort_ceiling_sht4x_update: 30s

  # Light level thresholds (lux)
  comfort_ceiling_lux_dark: "10"
  comfort_ceiling_lux_dim: "100"
  comfort_ceiling_lux_bright: "500"

# ============================================================================
# SENSORS
# ============================================================================
sensor:
  # ============================================================================
  # VEML7700 - High-Resolution Ambient Light Sensor (Vishay)
  # I2C Address: 0x10
  # ============================================================================
  # Features:
  # - 16-bit resolution
  # - Wide dynamic range: 0.0036 to 220,000+ lux
  # - White channel for color-neutral light measurement
  # - Configurable interrupt thresholds
  # ============================================================================
  - platform: veml7700
    id: comfort_ceiling_veml7700
    i2c_id: ${comfort_ceiling_i2c_id}
    address: 0x10
    update_interval: ${comfort_ceiling_veml7700_update}

    # Auto-adjusting lux measurement (compensated)
    ambient_light:
      id: comfort_ceiling_illuminance
      name: "${friendly_name} Illuminance"
      internal: true
      accuracy_decimals: 1
      unit_of_measurement: "lx"
      icon: mdi:brightness-5
      filters:
        - throttle: ${comfort_ceiling_veml7700_update}

    # Raw ambient light (for calibration/debugging)
    ambient_light_counts:
      id: comfort_ceiling_als_counts
      name: "${friendly_name} ALS Counts"
      internal: true
      accuracy_decimals: 0

    # Full spectrum (white channel) measurement
    full_spectrum:
      id: comfort_ceiling_full_spectrum
      name: "${friendly_name} Full Spectrum"
      internal: true
      accuracy_decimals: 1
      unit_of_measurement: "lx"

    # Full spectrum raw counts
    full_spectrum_counts:
      id: comfort_ceiling_fs_counts
      name: "${friendly_name} FS Counts"
      internal: true
      accuracy_decimals: 0

    # Sensor configuration
    auto_mode: true
    gain: 1X
    integration_time: 100ms

  # ============================================================================
  # SHT4x - High-Accuracy Temperature/Humidity Sensor (Sensirion)
  # I2C Address: 0x44
  # ============================================================================
  # Specifications:
  # - Temperature accuracy: +/- 0.2째C (typical)
  # - Humidity accuracy: +/- 1.8% RH (typical)
  # - Response time: 5.8s (humidity 63% step)
  # ============================================================================
  - platform: sht4x
    id: comfort_ceiling_sht4x
    i2c_id: ${comfort_ceiling_i2c_id}
    address: 0x44
    update_interval: ${comfort_ceiling_sht4x_update}

    temperature:
      id: comfort_ceiling_temperature
      name: "${friendly_name} Temperature"
      internal: true
      accuracy_decimals: 2
      unit_of_measurement: "째C"
      device_class: temperature
      state_class: measurement
      icon: mdi:thermometer
      filters:
        - throttle: ${comfort_ceiling_sht4x_update}

    humidity:
      id: comfort_ceiling_humidity
      name: "${friendly_name} Humidity"
      internal: true
      accuracy_decimals: 1
      unit_of_measurement: "%"
      device_class: humidity
      state_class: measurement
      icon: mdi:water-percent
      filters:
        - throttle: ${comfort_ceiling_sht4x_update}

    # High precision mode for best accuracy
    precision: High
    heater_power: "Low"

# ============================================================================
# AMBIENT LIGHT INTERRUPT (Optional - for threshold-based triggers)
# ============================================================================
binary_sensor:
  - platform: gpio
    id: comfort_ceiling_als_interrupt
    name: "${friendly_name} ALS Interrupt"
    internal: true
    pin:
      number: ${comfort_ceiling_als_int_pin}
      mode:
        input: true
        pullup: true
      inverted: true  # VEML7700 interrupt is active-low
    filters:
      - delayed_on: 10ms
      - delayed_off: 10ms
    on_press:
      then:
        - logger.log:
            level: DEBUG
            format: "VEML7700 interrupt triggered - light level threshold crossed"

# ============================================================================
# GLOBALS FOR COMFORT CEILING CALCULATIONS
# ============================================================================
globals:
  # Comfort ceiling module presence flag
  - id: module_comfort_ceiling_present
    type: bool
    restore_value: false
    initial_value: 'false'

  # Comfort index (0-100 scale)
  - id: comfort_ceiling_index_value
    type: float
    restore_value: false
    initial_value: '50.0'

  # Dew point temperature (calculated)
  - id: comfort_ceiling_dew_point
    type: float
    restore_value: false
    initial_value: '10.0'

  # Heat index / feels-like temperature
  - id: comfort_ceiling_heat_index
    type: float
    restore_value: false
    initial_value: '20.0'

  # Light level category (0=dark, 1=dim, 2=normal, 3=bright)
  - id: comfort_ceiling_light_level
    type: int
    restore_value: false
    initial_value: '2'

  # Power consumption tracking (mA)
  - id: power_comfort_ceiling_ma
    type: float
    restore_value: false
    initial_value: '50.0'

# ============================================================================
# INITIALIZATION
# ============================================================================
esphome:
  on_boot:
    - priority: 500
      then:
        - lambda: |-
            // Mark comfort ceiling module as present
            id(module_comfort_ceiling_present) = true;

            // Set power consumption for module
            id(power_comfort_ceiling_ma) = 50.0f;

            ESP_LOGI("comfort_ceiling", "Comfort Ceiling module initialized");
            ESP_LOGI("comfort_ceiling", "  - VEML7700 ALS at 0x10");
            ESP_LOGI("comfort_ceiling", "  - SHT4x Temp/Humidity at 0x44");

# ============================================================================
# INTERVAL FOR COMFORT CALCULATIONS
# ============================================================================
interval:
  - interval: 30s
    then:
      - lambda: |-
          float temp = id(comfort_ceiling_temperature).state;
          float humidity = id(comfort_ceiling_humidity).state;
          float lux = id(comfort_ceiling_illuminance).state;

          if (std::isnan(temp) || std::isnan(humidity)) {
            return;
          }

          // ================================================================
          // Calculate dew point (Magnus formula approximation)
          // ================================================================
          float alpha = ((17.27f * temp) / (237.7f + temp)) + log(humidity / 100.0f);
          float dew_point = (237.7f * alpha) / (17.27f - alpha);
          id(comfort_ceiling_dew_point) = dew_point;

          // ================================================================
          // Calculate heat index (simplified Rothfusz regression)
          // Only valid when temp > 26.7C and humidity > 40%
          // ================================================================
          float heat_index = temp;
          if (temp >= 26.7f && humidity >= 40.0f) {
            float t = temp;
            float h = humidity;
            heat_index = -8.784695f + 1.61139411f * t + 2.338549f * h
                         - 0.14611605f * t * h - 0.012308094f * t * t
                         - 0.016424828f * h * h + 0.002211732f * t * t * h
                         + 0.00072546f * t * h * h - 0.000003582f * t * t * h * h;
          }
          id(comfort_ceiling_heat_index) = heat_index;

          // ================================================================
          // Calculate comfort index (0-100)
          // Based on temperature (ideal 20-24C) and humidity (ideal 40-60%)
          // ================================================================
          float temp_score = 100.0f;
          if (temp < 18.0f) {
            temp_score = 100.0f - (18.0f - temp) * 10.0f;
          } else if (temp > 26.0f) {
            temp_score = 100.0f - (temp - 26.0f) * 10.0f;
          } else if (temp < 20.0f || temp > 24.0f) {
            temp_score = 90.0f;  // Slightly outside ideal range
          }
          if (temp_score < 0.0f) temp_score = 0.0f;

          float hum_score = 100.0f;
          if (humidity < 30.0f) {
            hum_score = 100.0f - (30.0f - humidity) * 2.0f;
          } else if (humidity > 70.0f) {
            hum_score = 100.0f - (humidity - 70.0f) * 2.0f;
          } else if (humidity < 40.0f || humidity > 60.0f) {
            hum_score = 90.0f;  // Slightly outside ideal range
          }
          if (hum_score < 0.0f) hum_score = 0.0f;

          // Combined comfort index (weighted average)
          float comfort = (temp_score * 0.5f) + (hum_score * 0.5f);
          id(comfort_ceiling_index_value) = comfort;

          // ================================================================
          // Light level categorization
          // ================================================================
          if (!std::isnan(lux)) {
            if (lux < ${comfort_ceiling_lux_dark}) {
              id(comfort_ceiling_light_level) = 0;  // Dark
            } else if (lux < ${comfort_ceiling_lux_dim}) {
              id(comfort_ceiling_light_level) = 1;  // Dim
            } else if (lux < ${comfort_ceiling_lux_bright}) {
              id(comfort_ceiling_light_level) = 2;  // Normal
            } else {
              id(comfort_ceiling_light_level) = 3;  // Bright
            }
          }

          ESP_LOGD("comfort_ceiling", "Comfort: %.1f%%, Temp: %.2f째C, Humidity: %.1f%%, Dew: %.1f째C, Lux: %.0f",
                   comfort, temp, humidity, dew_point, lux);
