# 12V PWM Fan Control Module
# Multi-channel fan control via SX1509 GPIO expander
#
# Features:
#   - 4 PWM fan channels
#   - Temperature-based auto mode
#   - Per-zone enable/disable
#   - Quiet and boost modes
#
# Requires: gpio_expander_sx1509.yaml

substitutions:
  sx1509_id: sx1509_expander
  fan_12v_min_speed: "20"
  fan_12v_max_speed: "100"
  fan_12v_default_speed: "50"
  fan_stall_rpm_threshold: "200"
  fan_temp_low: "25"
  fan_temp_high: "35"
  fan_temp_target: "30"

sensor:
  - platform: template
    id: fan_12v_rpm_0
    internal: true
    unit_of_measurement: "RPM"
    accuracy_decimals: 0
    update_interval: 2s
    lambda: |-
      if (id(sx1509_fan_0).state) {
        return (id(sx1509_fan_0).speed / 100.0f) * 3000.0f;
      }
      return 0.0f;

  - platform: template
    id: fan_12v_rpm_1
    internal: true
    unit_of_measurement: "RPM"
    accuracy_decimals: 0
    update_interval: 2s
    lambda: |-
      if (id(sx1509_fan_1).state) {
        return (id(sx1509_fan_1).speed / 100.0f) * 3000.0f;
      }
      return 0.0f;

  - platform: template
    id: fan_12v_rpm_2
    internal: true
    unit_of_measurement: "RPM"
    accuracy_decimals: 0
    update_interval: 2s
    lambda: |-
      if (id(sx1509_fan_2).state) {
        return (id(sx1509_fan_2).speed / 100.0f) * 3000.0f;
      }
      return 0.0f;

  - platform: template
    id: fan_12v_rpm_3
    internal: true
    unit_of_measurement: "RPM"
    accuracy_decimals: 0
    update_interval: 2s
    lambda: |-
      if (id(sx1509_fan_3).state) {
        return (id(sx1509_fan_3).speed / 100.0f) * 3000.0f;
      }
      return 0.0f;

  - platform: template
    id: fan_12v_total_power
    internal: true
    unit_of_measurement: "W"
    accuracy_decimals: 1
    update_interval: 5s
    lambda: |-
      float total = 0.0f;
      if (id(sx1509_fan_0).state) total += (id(sx1509_fan_0).speed / 100.0f) * 6.0f;
      if (id(sx1509_fan_1).state) total += (id(sx1509_fan_1).speed / 100.0f) * 6.0f;
      if (id(sx1509_fan_2).state) total += (id(sx1509_fan_2).speed / 100.0f) * 6.0f;
      if (id(sx1509_fan_3).state) total += (id(sx1509_fan_3).speed / 100.0f) * 6.0f;
      return total;

  - platform: template
    id: fan_12v_avg_speed
    internal: true
    unit_of_measurement: "%"
    accuracy_decimals: 0
    update_interval: 2s
    lambda: |-
      float sum = 0.0f;
      int count = 0;
      if (id(sx1509_fan_0).state) { sum += id(sx1509_fan_0).speed; count++; }
      if (id(sx1509_fan_1).state) { sum += id(sx1509_fan_1).speed; count++; }
      if (id(sx1509_fan_2).state) { sum += id(sx1509_fan_2).speed; count++; }
      if (id(sx1509_fan_3).state) { sum += id(sx1509_fan_3).speed; count++; }
      return count > 0 ? sum / count : 0.0f;

globals:
  - id: fan_12v_temperature_input
    type: float
    restore_value: false
    initial_value: '25.0'

  - id: fan_12v_auto_enabled
    type: bool
    restore_value: true
    initial_value: 'false'

  - id: fan_12v_stall_0
    type: bool
    restore_value: false
    initial_value: 'false'

  - id: fan_12v_stall_1
    type: bool
    restore_value: false
    initial_value: 'false'

  - id: fan_12v_stall_2
    type: bool
    restore_value: false
    initial_value: 'false'

  - id: fan_12v_stall_3
    type: bool
    restore_value: false
    initial_value: 'false'

  - id: fan_12v_quiet_mode
    type: bool
    restore_value: true
    initial_value: 'false'

  - id: fan_12v_boost_mode
    type: bool
    restore_value: false
    initial_value: 'false'

  - id: fan_12v_zone_0_enabled
    type: bool
    restore_value: true
    initial_value: 'true'

  - id: fan_12v_zone_1_enabled
    type: bool
    restore_value: true
    initial_value: 'true'

  - id: fan_12v_zone_2_enabled
    type: bool
    restore_value: true
    initial_value: 'true'

  - id: fan_12v_zone_3_enabled
    type: bool
    restore_value: true
    initial_value: 'true'

binary_sensor:
  - platform: template
    id: fan_12v_stall_alarm
    internal: true
    device_class: problem
    lambda: |-
      return id(fan_12v_stall_0) || id(fan_12v_stall_1) ||
             id(fan_12v_stall_2) || id(fan_12v_stall_3);

  - platform: template
    id: fan_12v_any_running
    internal: true
    lambda: |-
      return id(sx1509_fan_0).state || id(sx1509_fan_1).state ||
             id(sx1509_fan_2).state || id(sx1509_fan_3).state;

switch:
  - platform: template
    name: "${friendly_name} 12V Fans Auto Mode"
    id: fan_12v_auto_switch
    internal: true
    optimistic: true
    restore_mode: RESTORE_DEFAULT_OFF
    turn_on_action:
      - lambda: 'id(fan_12v_auto_enabled) = true;'
    turn_off_action:
      - lambda: 'id(fan_12v_auto_enabled) = false;'

  - platform: template
    name: "${friendly_name} 12V Fans Quiet Mode"
    id: fan_12v_quiet_switch
    internal: true
    optimistic: true
    restore_mode: RESTORE_DEFAULT_OFF
    turn_on_action:
      - lambda: 'id(fan_12v_quiet_mode) = true;'
    turn_off_action:
      - lambda: 'id(fan_12v_quiet_mode) = false;'

  - platform: template
    name: "${friendly_name} 12V Fans Boost Mode"
    id: fan_12v_boost_switch
    internal: true
    optimistic: true
    restore_mode: RESTORE_DEFAULT_OFF
    turn_on_action:
      - lambda: 'id(fan_12v_boost_mode) = true;'
    turn_off_action:
      - lambda: 'id(fan_12v_boost_mode) = false;'

script:
  - id: fan_12v_calculate_auto_speed
    mode: single
    then:
      - lambda: |-
          if (!id(fan_12v_auto_enabled)) return;

          float temp = id(fan_12v_temperature_input);
          int speed = 0;

          if (temp <= ${fan_temp_low}) {
            speed = ${fan_12v_min_speed};
          } else if (temp >= ${fan_temp_high}) {
            speed = ${fan_12v_max_speed};
          } else {
            float range = ${fan_temp_high} - ${fan_temp_low};
            float ratio = (temp - ${fan_temp_low}) / range;
            speed = ${fan_12v_min_speed} + (int)(ratio * (${fan_12v_max_speed} - ${fan_12v_min_speed}));
          }

          if (id(fan_12v_quiet_mode) && speed > 50) speed = 50;
          if (id(fan_12v_boost_mode)) speed = std::min(100, speed + 20);

          esphome::fan::Fan* fans[] = {id(sx1509_fan_0), id(sx1509_fan_1), id(sx1509_fan_2), id(sx1509_fan_3)};
          bool* zones[] = {&id(fan_12v_zone_0_enabled), &id(fan_12v_zone_1_enabled),
                           &id(fan_12v_zone_2_enabled), &id(fan_12v_zone_3_enabled)};

          for (int i = 0; i < 4; i++) {
            if (*zones[i]) {
              if (speed == 0) {
                fans[i]->turn_off().perform();
              } else {
                auto call = fans[i]->turn_on();
                call.set_speed(speed);
                call.perform();
              }
            }
          }

  - id: fan_12v_set_temperature
    mode: single
    parameters:
      temperature: float
    then:
      - lambda: 'id(fan_12v_temperature_input) = temperature;'
      - script.execute: fan_12v_calculate_auto_speed

  - id: fan_12v_emergency_stop
    mode: single
    then:
      - lambda: |-
          id(sx1509_fan_0).turn_off().perform();
          id(sx1509_fan_1).turn_off().perform();
          id(sx1509_fan_2).turn_off().perform();
          id(sx1509_fan_3).turn_off().perform();

interval:
  - interval: 10s
    then:
      - if:
          condition:
            lambda: 'return id(fan_12v_auto_enabled);'
          then:
            - script.execute: fan_12v_calculate_auto_speed
