---
# ============================================================================
# SENSE360 12V PWM FAN EXPANSION MODULE - MULTI-CHANNEL
# ============================================================================
# Professional 12V PWM fan control via GPIO expander:
# - 4x PWM fan outputs (25kHz via SX1509 expander)
# - 4x Tachometer inputs for RPM monitoring
# - UART passthrough for additional communication
#
# This module is designed for 12V 4-wire PWM fans commonly used in:
# - Server/rack cooling
# - HVAC systems
# - Industrial ventilation
# - High-airflow applications
#
# Hardware Requirements:
# - 12V DC power supply (separate from 5V/3.3V logic)
# - SX1509 GPIO expander module (or direct ESP32 GPIOs)
# - MOSFET driver circuit for 12V fan power switching
# - Optionally: Optocouplers for tachometer isolation
#
# 12V PWM Fan Connector Pinout (as per schematic):
#   Pin 1: TachD (Tachometer Fan 4)
#   Pin 2: TachPWM1
#   Pin 3: PwlCon1 (PWM Control 1)
#   Pin 4: TachPWM2
#   Pin 5: PwlCon2 (PWM Control 2)
#   Pin 6: TachPWM3
#   Pin 7: PwlCon3 (PWM Control 3)
#   Pin 8: TachPWM4
#   Pin 9: PwlCon4 (PWM Control 4)
#   Pin 10: UART_RX
#   Pin 11: UART_TX
#   Pin 12: GND
#
# Power Requirements: 12V / up to 4A (depending on fan specifications)
# ============================================================================

substitutions:
  # SX1509 expander reference (must be included separately)
  sx1509_id: sx1509_expander

  # PWM Pin assignments (SX1509 IO pins)
  fan_12v_pwm_pin_0: "0"   # IO0 - Fan 1 PWM
  fan_12v_pwm_pin_1: "1"   # IO1 - Fan 2 PWM
  fan_12v_pwm_pin_2: "2"   # IO2 - Fan 3 PWM
  fan_12v_pwm_pin_3: "3"   # IO3 - Fan 4 PWM

  # Tachometer Pin assignments (SX1509 IO pins)
  fan_12v_tach_pin_0: "4"  # IO4 - Fan 1 Tach
  fan_12v_tach_pin_1: "5"  # IO5 - Fan 2 Tach
  fan_12v_tach_pin_2: "6"  # IO6 - Fan 3 Tach
  fan_12v_tach_pin_3: "7"  # IO7 - Fan 4 Tach

  # Fan speed limits
  fan_12v_min_speed: "20"    # Minimum speed % (prevent stall)
  fan_12v_max_speed: "100"   # Maximum speed %
  fan_12v_default_speed: "50"

  # Stall detection threshold (RPM below this = stalled)
  fan_stall_rpm_threshold: "200"

  # Temperature thresholds for auto mode (Celsius)
  fan_temp_low: "25"    # Below this: fans off/minimum
  fan_temp_high: "35"   # Above this: fans at maximum
  fan_temp_target: "30" # Target temperature for PID-like control

# ============================================================================
# PWM OUTPUTS (via SX1509 GPIO Expander)
# ============================================================================
# Note: This requires the gpio_expander_sx1509.yaml to be included
# The outputs are already defined there. This file adds higher-level
# fan control logic and monitoring.
# ============================================================================

# ============================================================================
# TEMPLATE SENSORS FOR RPM CALCULATION
# ============================================================================
# Note: SX1509 doesn't support hardware pulse counting.
# For accurate RPM, use ESP32 direct GPIO or external counter IC.
# These template sensors estimate running state from PWM duty cycle.
# ============================================================================

sensor:
  # Estimated RPM based on PWM duty cycle (requires calibration)
  - platform: template
    id: fan_12v_rpm_0
    name: "${friendly_name} 12V Fan 1 RPM (Est)"
    internal: true
    unit_of_measurement: "RPM"
    accuracy_decimals: 0
    update_interval: 2s
    lambda: |-
      // Estimate RPM from duty cycle (typical relationship)
      // Actual RPM requires tachometer pulse counting
      if (id(sx1509_fan_0).state) {
        float duty = id(sx1509_fan_0).speed;
        // Typical 12V fan: 0% = 0 RPM, 100% = 3000 RPM
        return (duty / 100.0f) * 3000.0f;
      }
      return 0.0f;

  - platform: template
    id: fan_12v_rpm_1
    name: "${friendly_name} 12V Fan 2 RPM (Est)"
    internal: true
    unit_of_measurement: "RPM"
    accuracy_decimals: 0
    update_interval: 2s
    lambda: |-
      if (id(sx1509_fan_1).state) {
        float duty = id(sx1509_fan_1).speed;
        return (duty / 100.0f) * 3000.0f;
      }
      return 0.0f;

  - platform: template
    id: fan_12v_rpm_2
    name: "${friendly_name} 12V Fan 3 RPM (Est)"
    internal: true
    unit_of_measurement: "RPM"
    accuracy_decimals: 0
    update_interval: 2s
    lambda: |-
      if (id(sx1509_fan_2).state) {
        float duty = id(sx1509_fan_2).speed;
        return (duty / 100.0f) * 3000.0f;
      }
      return 0.0f;

  - platform: template
    id: fan_12v_rpm_3
    name: "${friendly_name} 12V Fan 4 RPM (Est)"
    internal: true
    unit_of_measurement: "RPM"
    accuracy_decimals: 0
    update_interval: 2s
    lambda: |-
      if (id(sx1509_fan_3).state) {
        float duty = id(sx1509_fan_3).speed;
        return (duty / 100.0f) * 3000.0f;
      }
      return 0.0f;

  # Total power consumption estimate (based on typical fan specs)
  - platform: template
    id: fan_12v_total_power
    name: "${friendly_name} 12V Fans Total Power"
    internal: true
    unit_of_measurement: "W"
    accuracy_decimals: 1
    update_interval: 5s
    lambda: |-
      // Estimate power: each fan ~6W at full speed
      float total = 0.0f;
      if (id(sx1509_fan_0).state)
        total += (id(sx1509_fan_0).speed / 100.0f) * 6.0f;
      if (id(sx1509_fan_1).state)
        total += (id(sx1509_fan_1).speed / 100.0f) * 6.0f;
      if (id(sx1509_fan_2).state)
        total += (id(sx1509_fan_2).speed / 100.0f) * 6.0f;
      if (id(sx1509_fan_3).state)
        total += (id(sx1509_fan_3).speed / 100.0f) * 6.0f;
      return total;

  # Average fan speed
  - platform: template
    id: fan_12v_avg_speed
    name: "${friendly_name} 12V Fans Average Speed"
    internal: true
    unit_of_measurement: "%"
    accuracy_decimals: 0
    update_interval: 2s
    lambda: |-
      float sum = 0.0f;
      int count = 0;
      if (id(sx1509_fan_0).state) {
        sum += id(sx1509_fan_0).speed;
        count++;
      }
      if (id(sx1509_fan_1).state) {
        sum += id(sx1509_fan_1).speed;
        count++;
      }
      if (id(sx1509_fan_2).state) {
        sum += id(sx1509_fan_2).speed;
        count++;
      }
      if (id(sx1509_fan_3).state) {
        sum += id(sx1509_fan_3).speed;
        count++;
      }
      return count > 0 ? sum / count : 0.0f;

# ============================================================================
# GLOBALS FOR 12V FAN CONTROL
# ============================================================================
globals:
  # Auto mode temperature source (set by external sensor)
  - id: fan_12v_temperature_input
    type: float
    restore_value: false
    initial_value: '25.0'

  # Auto mode enabled
  - id: fan_12v_auto_enabled
    type: bool
    restore_value: true
    initial_value: 'false'

  # Stall detection for each fan
  - id: fan_12v_stall_0
    type: bool
    restore_value: false
    initial_value: 'false'

  - id: fan_12v_stall_1
    type: bool
    restore_value: false
    initial_value: 'false'

  - id: fan_12v_stall_2
    type: bool
    restore_value: false
    initial_value: 'false'

  - id: fan_12v_stall_3
    type: bool
    restore_value: false
    initial_value: 'false'

  # Quiet mode (limits max speed)
  - id: fan_12v_quiet_mode
    type: bool
    restore_value: true
    initial_value: 'false'

  # Boost mode (minimum speed increase for higher airflow)
  - id: fan_12v_boost_mode
    type: bool
    restore_value: false
    initial_value: 'false'

  # Zone control enables (can disable individual fans)
  - id: fan_12v_zone_0_enabled
    type: bool
    restore_value: true
    initial_value: 'true'

  - id: fan_12v_zone_1_enabled
    type: bool
    restore_value: true
    initial_value: 'true'

  - id: fan_12v_zone_2_enabled
    type: bool
    restore_value: true
    initial_value: 'true'

  - id: fan_12v_zone_3_enabled
    type: bool
    restore_value: true
    initial_value: 'true'

# ============================================================================
# BINARY SENSORS FOR STALL ALERTS
# ============================================================================
binary_sensor:
  - platform: template
    id: fan_12v_stall_alarm
    name: "${friendly_name} 12V Fan Stall Alert"
    internal: true
    device_class: problem
    lambda: |-
      return id(fan_12v_stall_0) || id(fan_12v_stall_1) ||
             id(fan_12v_stall_2) || id(fan_12v_stall_3);

  - platform: template
    id: fan_12v_any_running
    name: "${friendly_name} 12V Fans Running"
    internal: true
    lambda: |-
      return id(sx1509_fan_0).state || id(sx1509_fan_1).state ||
             id(sx1509_fan_2).state || id(sx1509_fan_3).state;

# ============================================================================
# SWITCHES FOR MODE CONTROL
# ============================================================================
switch:
  - platform: template
    name: "${friendly_name} 12V Fans Auto Mode"
    id: fan_12v_auto_switch
    internal: true
    optimistic: true
    restore_mode: RESTORE_DEFAULT_OFF
    turn_on_action:
      - lambda: 'id(fan_12v_auto_enabled) = true;'
    turn_off_action:
      - lambda: 'id(fan_12v_auto_enabled) = false;'

  - platform: template
    name: "${friendly_name} 12V Fans Quiet Mode"
    id: fan_12v_quiet_switch
    internal: true
    optimistic: true
    restore_mode: RESTORE_DEFAULT_OFF
    turn_on_action:
      - lambda: 'id(fan_12v_quiet_mode) = true;'
    turn_off_action:
      - lambda: 'id(fan_12v_quiet_mode) = false;'

  - platform: template
    name: "${friendly_name} 12V Fans Boost Mode"
    id: fan_12v_boost_switch
    internal: true
    optimistic: true
    restore_mode: RESTORE_DEFAULT_OFF
    turn_on_action:
      - lambda: 'id(fan_12v_boost_mode) = true;'
    turn_off_action:
      - lambda: 'id(fan_12v_boost_mode) = false;'

# ============================================================================
# SCRIPTS FOR FAN CONTROL
# ============================================================================
script:
  # Calculate fan speed based on temperature (for auto mode)
  - id: fan_12v_calculate_auto_speed
    mode: single
    then:
      - lambda: |-
          if (!id(fan_12v_auto_enabled)) return;

          float temp = id(fan_12v_temperature_input);
          int speed = 0;

          // Temperature-based speed calculation
          if (temp <= ${fan_temp_low}) {
            speed = ${fan_12v_min_speed};  // Minimum speed
          } else if (temp >= ${fan_temp_high}) {
            speed = ${fan_12v_max_speed};  // Maximum speed
          } else {
            // Linear interpolation between low and high
            float range = ${fan_temp_high} - ${fan_temp_low};
            float ratio = (temp - ${fan_temp_low}) / range;
            speed = ${fan_12v_min_speed} + (int)(ratio * (${fan_12v_max_speed} - ${fan_12v_min_speed}));
          }

          // Apply quiet mode limit
          if (id(fan_12v_quiet_mode) && speed > 50) {
            speed = 50;
          }

          // Apply boost mode increase
          if (id(fan_12v_boost_mode)) {
            speed = std::min(100, speed + 20);
          }

          // Apply speed to all enabled zones
          if (id(fan_12v_zone_0_enabled)) {
            if (speed == 0) {
              auto call = id(sx1509_fan_0).turn_off();
              call.perform();
            } else {
              auto call = id(sx1509_fan_0).turn_on();
              call.set_speed(speed);
              call.perform();
            }
          }
          if (id(fan_12v_zone_1_enabled)) {
            if (speed == 0) {
              auto call = id(sx1509_fan_1).turn_off();
              call.perform();
            } else {
              auto call = id(sx1509_fan_1).turn_on();
              call.set_speed(speed);
              call.perform();
            }
          }
          if (id(fan_12v_zone_2_enabled)) {
            if (speed == 0) {
              auto call = id(sx1509_fan_2).turn_off();
              call.perform();
            } else {
              auto call = id(sx1509_fan_2).turn_on();
              call.set_speed(speed);
              call.perform();
            }
          }
          if (id(fan_12v_zone_3_enabled)) {
            if (speed == 0) {
              auto call = id(sx1509_fan_3).turn_off();
              call.perform();
            } else {
              auto call = id(sx1509_fan_3).turn_on();
              call.set_speed(speed);
              call.perform();
            }
          }

          ESP_LOGD("fan_12v", "Auto mode: temp=%.1fC, speed=%d%%", temp, speed);

  # Set temperature input (call from external sensor)
  - id: fan_12v_set_temperature
    mode: single
    parameters:
      temperature: float
    then:
      - lambda: |-
          id(fan_12v_temperature_input) = temperature;
      - script.execute: fan_12v_calculate_auto_speed

  # Emergency stop all 12V fans
  - id: fan_12v_emergency_stop
    mode: single
    then:
      - lambda: |-
          auto call0 = id(sx1509_fan_0).turn_off();
          call0.perform();
          auto call1 = id(sx1509_fan_1).turn_off();
          call1.perform();
          auto call2 = id(sx1509_fan_2).turn_off();
          call2.perform();
          auto call3 = id(sx1509_fan_3).turn_off();
          call3.perform();
          ESP_LOGW("fan_12v", "Emergency stop - all 12V fans stopped");

# ============================================================================
# INTERVAL FOR AUTO MODE AND MONITORING
# ============================================================================
interval:
  - interval: 10s
    then:
      # Run auto mode calculation if enabled
      - if:
          condition:
            lambda: 'return id(fan_12v_auto_enabled);'
          then:
            - script.execute: fan_12v_calculate_auto_speed

  - interval: 30s
    then:
      # Log fan status
      - lambda: |-
          ESP_LOGD("fan_12v", "Fan status: F1=%s(%d%%) F2=%s(%d%%) F3=%s(%d%%) F4=%s(%d%%)",
            id(sx1509_fan_0).state ? "ON" : "OFF",
            id(sx1509_fan_0).state ? (int)id(sx1509_fan_0).speed : 0,
            id(sx1509_fan_1).state ? "ON" : "OFF",
            id(sx1509_fan_1).state ? (int)id(sx1509_fan_1).speed : 0,
            id(sx1509_fan_2).state ? "ON" : "OFF",
            id(sx1509_fan_2).state ? (int)id(sx1509_fan_2).speed : 0,
            id(sx1509_fan_3).state ? "ON" : "OFF",
            id(sx1509_fan_3).state ? (int)id(sx1509_fan_3).speed : 0);
