---
# SX1509 GPIO/PWM Expander Module
# 16-channel I2C GPIO expander with PWM support
#
# Pin Layout:
#   IO0-IO3:  Fan PWM outputs (4 channels)
#   IO4-IO7:  Tachometer inputs
#   IO8-IO11: Auxiliary PWM outputs
#   IO12-IO15: General purpose inputs
#
# Connection: I2C Secondary bus (GPIO21/18), Address 0x3E

substitutions:
  sx1509_i2c_sda: GPIO21
  sx1509_i2c_scl: GPIO18
  sx1509_i2c_id: i2c_expander
  sx1509_address: "0x3E"
  sx1509_interrupt_pin: GPIO3

i2c:
  - id: ${sx1509_i2c_id}
    sda: ${sx1509_i2c_sda}
    scl: ${sx1509_i2c_scl}
    scan: true
    frequency: 400kHz

sx1509:
  - id: sx1509_expander
    i2c_id: ${sx1509_i2c_id}
    address: ${sx1509_address}

# PWM Outputs
output:
  - platform: sx1509
    sx1509_id: sx1509_expander
    id: sx1509_pwm_fan_0
    pin: 0

  - platform: sx1509
    sx1509_id: sx1509_expander
    id: sx1509_pwm_fan_1
    pin: 1

  - platform: sx1509
    sx1509_id: sx1509_expander
    id: sx1509_pwm_fan_2
    pin: 2

  - platform: sx1509
    sx1509_id: sx1509_expander
    id: sx1509_pwm_fan_3
    pin: 3

  - platform: sx1509
    sx1509_id: sx1509_expander
    id: sx1509_pwm_aux_0
    pin: 8

  - platform: sx1509
    sx1509_id: sx1509_expander
    id: sx1509_pwm_aux_1
    pin: 9

  - platform: sx1509
    sx1509_id: sx1509_expander
    id: sx1509_pwm_aux_2
    pin: 10

  - platform: sx1509
    sx1509_id: sx1509_expander
    id: sx1509_pwm_aux_3
    pin: 11

# Fan Controllers
fan:
  - platform: speed
    id: sx1509_fan_0
    name: "${friendly_name} Expander Fan 1"
    output: sx1509_pwm_fan_0
    speed_count: 100
    restore_mode: RESTORE_DEFAULT_OFF

  - platform: speed
    id: sx1509_fan_1
    name: "${friendly_name} Expander Fan 2"
    output: sx1509_pwm_fan_1
    speed_count: 100
    restore_mode: RESTORE_DEFAULT_OFF

  - platform: speed
    id: sx1509_fan_2
    name: "${friendly_name} Expander Fan 3"
    output: sx1509_pwm_fan_2
    speed_count: 100
    restore_mode: RESTORE_DEFAULT_OFF

  - platform: speed
    id: sx1509_fan_3
    name: "${friendly_name} Expander Fan 4"
    output: sx1509_pwm_fan_3
    speed_count: 100
    restore_mode: RESTORE_DEFAULT_OFF

# Digital Inputs
binary_sensor:
  - platform: gpio
    id: sx1509_tach_0
    internal: true
    pin:
      sx1509: sx1509_expander
      number: 4
      mode:
        input: true
        pullup: true
      inverted: true

  - platform: gpio
    id: sx1509_tach_1
    internal: true
    pin:
      sx1509: sx1509_expander
      number: 5
      mode:
        input: true
        pullup: true
      inverted: true

  - platform: gpio
    id: sx1509_tach_2
    internal: true
    pin:
      sx1509: sx1509_expander
      number: 6
      mode:
        input: true
        pullup: true
      inverted: true

  - platform: gpio
    id: sx1509_tach_3
    internal: true
    pin:
      sx1509: sx1509_expander
      number: 7
      mode:
        input: true
        pullup: true
      inverted: true

  - platform: gpio
    id: sx1509_input_0
    internal: true
    pin:
      sx1509: sx1509_expander
      number: 12
      mode:
        input: true
        pullup: true
      inverted: true

  - platform: gpio
    id: sx1509_input_1
    internal: true
    pin:
      sx1509: sx1509_expander
      number: 13
      mode:
        input: true
        pullup: true
      inverted: true

  - platform: gpio
    id: sx1509_input_2
    internal: true
    pin:
      sx1509: sx1509_expander
      number: 14
      mode:
        input: true
        pullup: true
      inverted: true

  - platform: gpio
    id: sx1509_input_3
    internal: true
    pin:
      sx1509: sx1509_expander
      number: 15
      mode:
        input: true
        pullup: true
      inverted: true

# Auxiliary LED outputs
light:
  - platform: monochromatic
    id: sx1509_led_0
    output: sx1509_pwm_aux_0
    internal: true
    default_transition_length: 200ms

  - platform: monochromatic
    id: sx1509_led_1
    output: sx1509_pwm_aux_1
    internal: true
    default_transition_length: 200ms

  - platform: monochromatic
    id: sx1509_led_2
    output: sx1509_pwm_aux_2
    internal: true
    default_transition_length: 200ms

  - platform: monochromatic
    id: sx1509_led_3
    output: sx1509_pwm_aux_3
    internal: true
    default_transition_length: 200ms

# Speed sensors
sensor:
  - platform: template
    id: sx1509_fan_0_speed
    internal: true
    unit_of_measurement: "%"
    accuracy_decimals: 0
    update_interval: 2s
    lambda: |-
      return id(sx1509_fan_0).state ? id(sx1509_fan_0).speed : 0.0f;

  - platform: template
    id: sx1509_fan_1_speed
    internal: true
    unit_of_measurement: "%"
    accuracy_decimals: 0
    update_interval: 2s
    lambda: |-
      return id(sx1509_fan_1).state ? id(sx1509_fan_1).speed : 0.0f;

  - platform: template
    id: sx1509_fan_2_speed
    internal: true
    unit_of_measurement: "%"
    accuracy_decimals: 0
    update_interval: 2s
    lambda: |-
      return id(sx1509_fan_2).state ? id(sx1509_fan_2).speed : 0.0f;

  - platform: template
    id: sx1509_fan_3_speed
    internal: true
    unit_of_measurement: "%"
    accuracy_decimals: 0
    update_interval: 2s
    lambda: |-
      return id(sx1509_fan_3).state ? id(sx1509_fan_3).speed : 0.0f;

globals:
  - id: sx1509_online
    type: bool
    restore_value: false
    initial_value: 'false'

  - id: sx1509_fan_0_target
    type: int
    restore_value: true
    initial_value: '0'

  - id: sx1509_fan_1_target
    type: int
    restore_value: true
    initial_value: '0'

  - id: sx1509_fan_2_target
    type: int
    restore_value: true
    initial_value: '0'

  - id: sx1509_fan_3_target
    type: int
    restore_value: true
    initial_value: '0'

  - id: sx1509_fans_linked
    type: bool
    restore_value: true
    initial_value: 'false'

  - id: sx1509_fan_auto_mode
    type: bool
    restore_value: true
    initial_value: 'false'

script:
  - id: sx1509_set_fan_speed
    mode: single
    parameters:
      fan_num: int
      speed: int
    then:
      - lambda: |-
          int target = std::max(0, std::min(100, speed));
          esphome::fan::Fan *fan = nullptr;
          int *target_var = nullptr;

          switch (fan_num) {
            case 0: fan = id(sx1509_fan_0); target_var = &id(sx1509_fan_0_target); break;
            case 1: fan = id(sx1509_fan_1); target_var = &id(sx1509_fan_1_target); break;
            case 2: fan = id(sx1509_fan_2); target_var = &id(sx1509_fan_2_target); break;
            case 3: fan = id(sx1509_fan_3); target_var = &id(sx1509_fan_3_target); break;
            default: return;
          }
          *target_var = target;
          if (target == 0) {
            fan->turn_off().perform();
          } else {
            auto call = fan->turn_on();
            call.set_speed(target);
            call.perform();
          }

  - id: sx1509_set_all_fans
    mode: single
    parameters:
      speed: int
    then:
      - script.execute:
          id: sx1509_set_fan_speed
          fan_num: 0
          speed: !lambda 'return speed;'
      - script.execute:
          id: sx1509_set_fan_speed
          fan_num: 1
          speed: !lambda 'return speed;'
      - script.execute:
          id: sx1509_set_fan_speed
          fan_num: 2
          speed: !lambda 'return speed;'
      - script.execute:
          id: sx1509_set_fan_speed
          fan_num: 3
          speed: !lambda 'return speed;'

  - id: sx1509_emergency_stop
    mode: single
    then:
      - fan.turn_off: sx1509_fan_0
      - fan.turn_off: sx1509_fan_1
      - fan.turn_off: sx1509_fan_2
      - fan.turn_off: sx1509_fan_3
      - lambda: |-
          id(sx1509_fan_0_target) = 0;
          id(sx1509_fan_1_target) = 0;
          id(sx1509_fan_2_target) = 0;
          id(sx1509_fan_3_target) = 0;

interval:
  - interval: 5s
    then:
      - lambda: |-
          if (id(sx1509_fans_linked)) {
            int master = id(sx1509_fan_0_target);
            if (id(sx1509_fan_1_target) != master ||
                id(sx1509_fan_2_target) != master ||
                id(sx1509_fan_3_target) != master) {
              id(sx1509_fan_1_target) = master;
              id(sx1509_fan_2_target) = master;
              id(sx1509_fan_3_target) = master;
              for (int i = 1; i <= 3; i++) {
                auto *fan = (i == 1) ? id(sx1509_fan_1) :
                            (i == 2) ? id(sx1509_fan_2) : id(sx1509_fan_3);
                if (master == 0) {
                  fan->turn_off().perform();
                } else {
                  auto call = fan->turn_on();
                  call.set_speed(master);
                  call.perform();
                }
              }
            }
          }
