---
# ============================================================================
# SENSE360 PRESENCE EXPANSION MODULE - LD2450 (Multi-Target)
# ============================================================================
# HLK-LD2450 24GHz mmWave Radar Sensor for presence detection
# - Multi-target tracking (up to 3 simultaneous targets)
# - Zone configuration support
# - Static vs moving target differentiation
# - UART interface at 256000 baud
#
# This file provides the base hardware setup. User-facing entities are defined
# in the feature profile files (basic or advanced).
#
# Expansion Bus Connection:
#   Pin 6 (UART TX) → GPIO1 (ESP RX)
#   Pin 7 (UART RX) → GPIO2 (ESP TX)
#   Pin 3 (5V) → Power
#   Pin 1 (GND) → Ground
#
# Power Requirements: 5V / 150mA max
# ============================================================================

substitutions:
  # UART Configuration
  ld2450_uart_id: uart_bus
  ld2450_tx_pin: GPIO1
  ld2450_rx_pin: GPIO2
  ld2450_baud: "256000"

  # Apply UART settings to the shared expansion bus
  uart_tx_pin: ${ld2450_tx_pin}
  uart_rx_pin: ${ld2450_rx_pin}
  uart_baud: ${ld2450_baud}

  # Presence detection settings
  presence_timeout: 30s

# LD2450 Base Component
LD2450:
  id: ld2450_radar
  uart_id: ${ld2450_uart_id}
  # Target count sensor
  target_count:
    id: ld2450_target_count
    name: "${friendly_name} Target Count"
    internal: true
  # Occupancy sensor (internal - use presence_binary from profile)
  occupancy:
    id: ld2450_occupancy
    name: "${friendly_name} Radar Occupancy"
    internal: true
  # Three targets tracking
  targets:
    - target:
        id: ld2450_t1
        x_position:
          id: ld2450_t1_x
          name: "${friendly_name} Target 1 X"
          internal: true
        y_position:
          id: ld2450_t1_y
          name: "${friendly_name} Target 1 Y"
          internal: true
        speed:
          id: ld2450_t1_speed
          name: "${friendly_name} Target 1 Speed"
          internal: true
        distance:
          id: ld2450_t1_distance
          name: "${friendly_name} Target 1 Distance"
          internal: true
        angle:
          id: ld2450_t1_angle
          name: "${friendly_name} Target 1 Angle"
          internal: true
    - target:
        id: ld2450_t2
        x_position:
          id: ld2450_t2_x
          name: "${friendly_name} Target 2 X"
          internal: true
        y_position:
          id: ld2450_t2_y
          name: "${friendly_name} Target 2 Y"
          internal: true
        speed:
          id: ld2450_t2_speed
          name: "${friendly_name} Target 2 Speed"
          internal: true
        distance:
          id: ld2450_t2_distance
          name: "${friendly_name} Target 2 Distance"
          internal: true
        angle:
          id: ld2450_t2_angle
          name: "${friendly_name} Target 2 Angle"
          internal: true
    - target:
        id: ld2450_t3
        x_position:
          id: ld2450_t3_x
          name: "${friendly_name} Target 3 X"
          internal: true
        y_position:
          id: ld2450_t3_y
          name: "${friendly_name} Target 3 Y"
          internal: true
        speed:
          id: ld2450_t3_speed
          name: "${friendly_name} Target 3 Speed"
          internal: true
        distance:
          id: ld2450_t3_distance
          name: "${friendly_name} Target 3 Distance"
          internal: true
        angle:
          id: ld2450_t3_angle
          name: "${friendly_name} Target 3 Angle"
          internal: true

# ============================================================================
# Globals for Presence Detection
# ============================================================================
globals:
  - id: presence_confidence
    type: float
    restore_value: false
    initial_value: '0.0'

  # Closest target distance (for zone-based logic)
  - id: presence_closest_distance
    type: float
    restore_value: false
    initial_value: '0.0'

  # Number of people detected
  - id: presence_people_count
    type: int
    restore_value: false
    initial_value: '0'

  # Moving/still counts (computed from speed)
  - id: ld2450_still_count
    type: int
    restore_value: false
    initial_value: '0'

  - id: ld2450_moving_count
    type: int
    restore_value: false
    initial_value: '0'

# Update presence confidence based on sensor data
interval:
  - interval: 1s
    then:
      - lambda: |-
          // LD2450 presence detection logic
          int targets = id(ld2450_target_count).state;

          // Calculate moving/still from speeds
          int moving = 0;
          int still = 0;
          float speed_threshold = 0.1f;

          if (id(ld2450_t1_speed).has_state() && abs(id(ld2450_t1_speed).state) > speed_threshold) {
            moving++;
          } else if (id(ld2450_t1_distance).has_state() && id(ld2450_t1_distance).state > 0) {
            still++;
          }

          if (id(ld2450_t2_speed).has_state() && abs(id(ld2450_t2_speed).state) > speed_threshold) {
            moving++;
          } else if (id(ld2450_t2_distance).has_state() && id(ld2450_t2_distance).state > 0) {
            still++;
          }

          if (id(ld2450_t3_speed).has_state() && abs(id(ld2450_t3_speed).state) > speed_threshold) {
            moving++;
          } else if (id(ld2450_t3_distance).has_state() && id(ld2450_t3_distance).state > 0) {
            still++;
          }

          id(ld2450_still_count) = still;
          id(ld2450_moving_count) = moving;

          // Update people count
          id(presence_people_count) = targets;

          if (targets > 0) {
            // Someone is present
            if (moving > 0) {
              // Movement detected - high confidence
              id(presence_confidence) = 0.95f;
            } else if (still > 0) {
              // Still presence - medium-high confidence
              id(presence_confidence) = 0.7f;
            } else {
              // Target detected but not classified
              id(presence_confidence) = 0.6f;
            }

            // Calculate closest target distance
            float min_dist = 9999.0f;
            float d1 = id(ld2450_t1_distance).state;
            float d2 = id(ld2450_t2_distance).state;
            float d3 = id(ld2450_t3_distance).state;

            if (!std::isnan(d1) && d1 > 0 && d1 < min_dist) min_dist = d1;
            if (!std::isnan(d2) && d2 > 0 && d2 < min_dist) min_dist = d2;
            if (!std::isnan(d3) && d3 > 0 && d3 < min_dist) min_dist = d3;

            if (min_dist < 9999.0f) {
              id(presence_closest_distance) = min_dist;
            }
          } else {
            // No one detected
            id(presence_confidence) = 0.1f;
            id(presence_closest_distance) = 0.0f;
          }
