---
# ============================================================================
# SENSE360 PRESENCE MODULE - WALL/DESK VARIANT
# ============================================================================
# SKU: S360-PRES-W
#
# mmWave radar-based presence detection for wall-mounted/desk installations.
#
# Supported Sensors:
# - HLK-LD2450 (UART): 24GHz mmWave radar, multi-target tracking (default)
# - DFRobot C4001 (UART/I2C): 24GHz FMCW radar, 16m presence range, speed measurement
#
# This config uses HLK-LD2450. For C4001, use presence_dfrobot_c4001.yaml instead.
#
# Features (LD2450):
# - Up to 3 simultaneous targets
# - Still and moving target differentiation
# - Zone-based detection
# - Distance and angle measurement
#
# Expansion Bus Connection (Wall/Desk):
#   Pin 6 (UART TX) → GPIO1 (ESP RX)
#   Pin 7 (UART RX) → GPIO2 (ESP TX)
#   Pin 3 (5V) → Power
#   Pin 1 (GND) → Ground
#
# Power Requirements: 5V / 150mA max (LD2450), 5V / 250mA max (C4001)
#
# Requires external component from: https://github.com/TillFleisch/ESPHome-HLK-LD2450
# ============================================================================

# External component for LD2450 radar (TillFleisch implementation)
external_components:
  - source:
      type: git
      url: https://github.com/TillFleisch/ESPHome-HLK-LD2450
      ref: main
    components: [ld2450]
    refresh: 1d

substitutions:
  module_sku: S360-PRES-W
  module_variant: wall

  # UART Configuration (Wall reuses shared expansion UART)
  ld2450_uart_id: uart_bus
  ld2450_baud: "115200"  # Wall uses 115200 baud

  # Presence detection settings
  presence_timeout: 30s

# LD2450 Base Component with TillFleisch API
ld2450:
  id: ld2450_radar
  uart_id: ${ld2450_uart_id}
  # Target sensor configuration
  target_count:
    id: ld2450_target_count
    name: "${friendly_name} Target Count"
    internal: true
  # Three targets tracking
  targets:
    - id: ld2450_t1
      x_position:
        id: ld2450_t1_x
        name: "${friendly_name} Target 1 X"
        internal: true
      y_position:
        id: ld2450_t1_y
        name: "${friendly_name} Target 1 Y"
        internal: true
      speed:
        id: ld2450_t1_speed
        name: "${friendly_name} Target 1 Speed"
        internal: true
      distance:
        id: ld2450_t1_distance
        name: "${friendly_name} Target 1 Distance"
        internal: true
      angle:
        id: ld2450_t1_angle
        name: "${friendly_name} Target 1 Angle"
        internal: true
    - id: ld2450_t2
      x_position:
        id: ld2450_t2_x
        name: "${friendly_name} Target 2 X"
        internal: true
      y_position:
        id: ld2450_t2_y
        name: "${friendly_name} Target 2 Y"
        internal: true
      speed:
        id: ld2450_t2_speed
        name: "${friendly_name} Target 2 Speed"
        internal: true
      distance:
        id: ld2450_t2_distance
        name: "${friendly_name} Target 2 Distance"
        internal: true
      angle:
        id: ld2450_t2_angle
        name: "${friendly_name} Target 2 Angle"
        internal: true
    - id: ld2450_t3
      x_position:
        id: ld2450_t3_x
        name: "${friendly_name} Target 3 X"
        internal: true
      y_position:
        id: ld2450_t3_y
        name: "${friendly_name} Target 3 Y"
        internal: true
      speed:
        id: ld2450_t3_speed
        name: "${friendly_name} Target 3 Speed"
        internal: true
      distance:
        id: ld2450_t3_distance
        name: "${friendly_name} Target 3 Distance"
        internal: true
      angle:
        id: ld2450_t3_angle
        name: "${friendly_name} Target 3 Angle"
        internal: true
  # Occupancy binary sensor
  occupancy:
    id: ld2450_occupancy
    name: "${friendly_name} Presence"
    device_class: occupancy

# ============================================================================
# Globals for Presence Detection
# ============================================================================
globals:
  - id: presence_confidence
    type: float
    restore_value: false
    initial_value: '0.0'

  - id: presence_closest_distance
    type: float
    restore_value: false
    initial_value: '0.0'

  - id: presence_people_count
    type: int
    restore_value: false
    initial_value: '0'

  - id: ld2450_still_count
    type: int
    restore_value: false
    initial_value: '0'

  - id: ld2450_moving_count
    type: int
    restore_value: false
    initial_value: '0'

# Update presence data
interval:
  - interval: 1s
    then:
      - lambda: |-
          int targets = id(ld2450_target_count).state;
          int moving = 0;
          int still = 0;

          // Speed threshold: > 0.1 m/s is considered moving
          float speed_threshold = 0.1f;

          // Check each target's speed to determine if moving or still
          if (id(ld2450_t1_speed).has_state() && abs(id(ld2450_t1_speed).state) > speed_threshold) {
            moving++;
          } else if (id(ld2450_t1_distance).has_state() && id(ld2450_t1_distance).state > 0) {
            still++;
          }

          if (id(ld2450_t2_speed).has_state() && abs(id(ld2450_t2_speed).state) > speed_threshold) {
            moving++;
          } else if (id(ld2450_t2_distance).has_state() && id(ld2450_t2_distance).state > 0) {
            still++;
          }

          if (id(ld2450_t3_speed).has_state() && abs(id(ld2450_t3_speed).state) > speed_threshold) {
            moving++;
          } else if (id(ld2450_t3_distance).has_state() && id(ld2450_t3_distance).state > 0) {
            still++;
          }

          id(ld2450_still_count) = still;
          id(ld2450_moving_count) = moving;
          id(presence_people_count) = targets;

          if (targets > 0) {
            if (moving > 0) {
              id(presence_confidence) = 0.95f;
            } else if (still > 0) {
              id(presence_confidence) = 0.7f;
            } else {
              id(presence_confidence) = 0.6f;
            }

            float min_dist = 9999.0f;
            float d1 = id(ld2450_t1_distance).state;
            float d2 = id(ld2450_t2_distance).state;
            float d3 = id(ld2450_t3_distance).state;

            if (!std::isnan(d1) && d1 > 0 && d1 < min_dist) min_dist = d1;
            if (!std::isnan(d2) && d2 > 0 && d2 < min_dist) min_dist = d2;
            if (!std::isnan(d3) && d3 > 0 && d3 < min_dist) min_dist = d3;

            if (min_dist < 9999.0f) {
              id(presence_closest_distance) = min_dist;
            }
          } else {
            id(presence_confidence) = 0.1f;
            id(presence_closest_distance) = 0.0f;
          }

text_sensor:
  - platform: template
    name: "${friendly_name} Presence Module SKU"
    lambda: |-
      return {"${module_sku}"};
    update_interval: never
    entity_category: diagnostic
