---
# Sense360 Power Management
# Tracks power consumption per rail and module
#
# Power Rails:
#   3.3V: 500mA max (MCU, sensors, expander)
#   5V:   2000mA max (presence radar, USB)
#   12V:  4000mA max (external fans)
#
# Module Power Draw (typical/max mA):
#   ESP32-S3:  150/500   Presence:  80/150
#   AirIQ:     150/500   Comfort:   50/200
#   GP8403:    20/50     SX1509:    30/50
#   12V Fan:   200/500 each

substitutions:
  power_budget_3v3_max: "500"
  power_budget_5v_max: "2000"
  power_budget_12v_max: "4000"
  power_warning_threshold: "80"
  power_critical_threshold: "95"

globals:
  - id: power_source_name
    type: std::string
    restore_value: false
    initial_value: '"Unknown"'

  - id: power_3v3_consumption
    type: float
    restore_value: false
    initial_value: '150.0'

  - id: power_5v_consumption
    type: float
    restore_value: false
    initial_value: '0.0'

  - id: power_12v_consumption
    type: float
    restore_value: false
    initial_value: '0.0'

  - id: power_presence_module_ma
    type: float
    restore_value: false
    initial_value: '0.0'

  - id: power_airiq_module_ma
    type: float
    restore_value: false
    initial_value: '0.0'

  - id: power_comfort_module_ma
    type: float
    restore_value: false
    initial_value: '0.0'

  - id: power_fan_dac_module_ma
    type: float
    restore_value: false
    initial_value: '0.0'

  - id: power_expander_module_ma
    type: float
    restore_value: false
    initial_value: '0.0'

  - id: power_12v_fans_ma
    type: float
    restore_value: false
    initial_value: '0.0'

  - id: power_3v3_overload
    type: bool
    restore_value: false
    initial_value: 'false'

  - id: power_5v_overload
    type: bool
    restore_value: false
    initial_value: 'false'

  - id: power_12v_overload
    type: bool
    restore_value: false
    initial_value: 'false'

sensor:
  - platform: template
    id: power_3v3_utilization
    name: "${friendly_name} 3.3V Load"
    internal: true
    unit_of_measurement: "%"
    accuracy_decimals: 0
    update_interval: 5s
    lambda: |-
      return (id(power_3v3_consumption) / ${power_budget_3v3_max}) * 100.0f;

  - platform: template
    id: power_3v3_current
    name: "${friendly_name} 3.3V Current"
    internal: true
    unit_of_measurement: "mA"
    accuracy_decimals: 0
    update_interval: 5s
    lambda: |-
      return id(power_3v3_consumption);

  - platform: template
    id: power_5v_utilization
    name: "${friendly_name} 5V Load"
    internal: true
    unit_of_measurement: "%"
    accuracy_decimals: 0
    update_interval: 5s
    lambda: |-
      return (id(power_5v_consumption) / ${power_budget_5v_max}) * 100.0f;

  - platform: template
    id: power_5v_current
    name: "${friendly_name} 5V Current"
    internal: true
    unit_of_measurement: "mA"
    accuracy_decimals: 0
    update_interval: 5s
    lambda: |-
      return id(power_5v_consumption);

  - platform: template
    id: power_12v_utilization
    name: "${friendly_name} 12V Load"
    internal: true
    unit_of_measurement: "%"
    accuracy_decimals: 0
    update_interval: 5s
    lambda: |-
      if (${power_budget_12v_max} > 0) {
        return (id(power_12v_consumption) / ${power_budget_12v_max}) * 100.0f;
      }
      return 0.0f;

  - platform: template
    id: power_total_watts
    name: "${friendly_name} Total Power"
    internal: true
    unit_of_measurement: "W"
    accuracy_decimals: 2
    update_interval: 5s
    lambda: |-
      float p3v3 = (id(power_3v3_consumption) / 1000.0f) * 3.3f;
      float p5v = (id(power_5v_consumption) / 1000.0f) * 5.0f;
      float p12v = (id(power_12v_consumption) / 1000.0f) * 12.0f;
      return p3v3 + p5v + p12v;

binary_sensor:
  - platform: template
    id: power_3v3_warning
    internal: true
    device_class: problem
    lambda: |-
      return (id(power_3v3_consumption) / ${power_budget_3v3_max}) * 100.0f >= ${power_warning_threshold};

  - platform: template
    id: power_5v_warning
    internal: true
    device_class: problem
    lambda: |-
      return (id(power_5v_consumption) / ${power_budget_5v_max}) * 100.0f >= ${power_warning_threshold};

  - platform: template
    id: power_any_overload
    internal: true
    device_class: problem
    lambda: |-
      return id(power_3v3_overload) || id(power_5v_overload) || id(power_12v_overload);

text_sensor:
  - platform: template
    id: power_budget_status
    name: "${friendly_name} Power Status"
    internal: true
    update_interval: 10s
    lambda: |-
      float u3v3 = (id(power_3v3_consumption) / ${power_budget_3v3_max}) * 100.0f;
      float u5v = (id(power_5v_consumption) / ${power_budget_5v_max}) * 100.0f;
      if (u3v3 >= ${power_critical_threshold} || u5v >= ${power_critical_threshold}) {
        return {"CRITICAL"};
      } else if (u3v3 >= ${power_warning_threshold} || u5v >= ${power_warning_threshold}) {
        return {"WARNING"};
      }
      return {"OK"};

script:
  - id: power_register_module
    mode: single
    parameters:
      module_name: string
      rail_3v3_ma: float
      rail_5v_ma: float
      rail_12v_ma: float
    then:
      - lambda: |-
          if (module_name == "presence") id(power_presence_module_ma) = rail_5v_ma;
          else if (module_name == "airiq") id(power_airiq_module_ma) = rail_3v3_ma;
          else if (module_name == "comfort") id(power_comfort_module_ma) = rail_3v3_ma;
          else if (module_name == "fan_dac") id(power_fan_dac_module_ma) = rail_3v3_ma;
          else if (module_name == "expander") id(power_expander_module_ma) = rail_3v3_ma;
          else if (module_name == "12v_fans") id(power_12v_fans_ma) = rail_12v_ma;

          id(power_3v3_consumption) = 150.0f +
            id(power_airiq_module_ma) + id(power_comfort_module_ma) +
            id(power_fan_dac_module_ma) + id(power_expander_module_ma);
          id(power_5v_consumption) = id(power_presence_module_ma);
          id(power_12v_consumption) = id(power_12v_fans_ma);

          id(power_3v3_overload) = id(power_3v3_consumption) > ${power_budget_3v3_max};
          id(power_5v_overload) = id(power_5v_consumption) > ${power_budget_5v_max};
          id(power_12v_overload) = id(power_12v_consumption) > ${power_budget_12v_max};

  - id: power_unregister_module
    mode: single
    parameters:
      module_name: string
    then:
      - script.execute:
          id: power_register_module
          module_name: !lambda 'return module_name;'
          rail_3v3_ma: 0.0
          rail_5v_ma: 0.0
          rail_12v_ma: 0.0

esphome:
  on_boot:
    - priority: 700
      then:
        - lambda: |-
            id(power_3v3_consumption) = 150.0f;
            id(power_5v_consumption) = 0.0f;
            id(power_12v_consumption) = 0.0f;
