# Sense360 Core - 240V AC Power Configuration
#
# This package configures the Sense360 Core board for 240V AC mains power.
#
# Hardware:
# - Onboard AC-DC converter (HLK-PM01 or similar)
# - Input: 100-240V AC, 50/60Hz
# - Output: 5V DC, 2A (10W)
# - Isolation: 3000VAC
# - Protection: Overcurrent, overvoltage, short-circuit
#
# Safety Notes:
# - This configuration assumes proper electrical isolation
# - Ensure device enclosure meets electrical safety standards
# - AC input should have appropriate fusing (1A recommended)
# - Follow local electrical codes and regulations
#
# Power Monitoring:
# - Optional current sensor (e.g., ACS712) for power consumption monitoring
# - GPIO for power source detection
#
# Recommended for:
# - Permanently installed devices
# - Wall-mounted installations
# - Ceiling-mounted installations
# - Where PoE is not available

substitutions:
  power_source: "240v_ac"

# Global variable for power source identification
globals:
  - id: power_source_type
    type: std::string
    restore_value: false
    initial_value: '"240V AC"'

# Power monitoring sensor (optional, if current sensor installed)
sensor:
  # Voltage (fixed at 5V output from AC-DC converter)
  - platform: template
    name: "${friendly_name} Supply Voltage"
    id: supply_voltage
    icon: mdi:lightning-bolt
    unit_of_measurement: "V"
    device_class: voltage
    state_class: measurement
    accuracy_decimals: 1
    lambda: |-
      return 5.0;  // Fixed 5V output
    update_interval: 60s

# Power source indicator and configuration notes
text_sensor:
  - platform: template
    name: "${friendly_name} Power Source"
    id: power_source_indicator
    icon: mdi:power-plug
    lambda: |-
      return {"240V AC"};
    update_interval: 60s

  - platform: template
    name: "${friendly_name} Power Configuration"
    id: power_config_info
    icon: mdi:information
    lambda: |-
      return {"240V AC mains power with onboard AC-DC converter (5V/2A output)"};
    update_interval: never
    entity_category: diagnostic

# Binary sensor for AC power status
binary_sensor:
  - platform: template
    name: "${friendly_name} AC Power Connected"
    id: ac_power_connected
    icon: mdi:power-plug
    device_class: power
    lambda: |-
      // Assume always connected for 240V AC configuration
      // If you have a power detection circuit, implement it here
      return true;

# Debug logging for power configuration
logger:
  logs:
    sensor: INFO
    power: ${log_level}
