---
# ============================================================================
# LD2450 Radar Sensor Hardware Configuration
# ============================================================================
# HLK-LD2450 24GHz mmWave Radar Sensor
# - Multi-target tracking (up to 3 simultaneous targets)
# - Zone configuration support
# - Static vs moving target differentiation
# - UART interface at 256000 baud
#
# NOTE: Uses native ESPHome LD2450 support (no external component required)
# ============================================================================

substitutions:
  presence_timeout: 30s

# UART for LD2450 Radar Sensor
uart:
  - id: ${ld2450_uart_id}
    tx_pin: ${ld2450_tx_pin}
    rx_pin: ${ld2450_rx_pin}
    baud_rate: ${ld2450_baud}
    parity: NONE
    stop_bits: 1

# ============================================================================
# LD2450 Radar Component (Native ESPHome)
# ============================================================================
ld2450:
  id: ld2450_radar
  uart_id: ${ld2450_uart_id}

# ============================================================================
# Binary Sensors - Presence Detection
# ============================================================================
binary_sensor:
  - platform: ld2450
    ld2450_id: ld2450_radar
    has_target:
      id: ld2450_occupancy
      name: "${friendly_name} Radar Presence"
      internal: true
      device_class: occupancy
    has_moving_target:
      id: ld2450_has_moving
      name: "${friendly_name} Moving Target"
      internal: true
    has_still_target:
      id: ld2450_has_still
      name: "${friendly_name} Still Target"
      internal: true

# ============================================================================
# Sensors - Target Tracking
# ============================================================================
sensor:
  - platform: ld2450
    ld2450_id: ld2450_radar
    target_count:
      id: ld2450_target_count
      internal: true
    still_target_count:
      id: ld2450_still_target_count
      internal: true
    moving_target_count:
      id: ld2450_moving_target_count
      internal: true
    # Target 1
    target_1:
      x:
        id: ld2450_t1_x
        internal: true
      y:
        id: ld2450_t1_y
        internal: true
      speed:
        id: ld2450_t1_speed
        internal: true
      distance:
        id: ld2450_t1_distance
        internal: true
    # Target 2
    target_2:
      x:
        id: ld2450_t2_x
        internal: true
      y:
        id: ld2450_t2_y
        internal: true
      speed:
        id: ld2450_t2_speed
        internal: true
      distance:
        id: ld2450_t2_distance
        internal: true
    # Target 3
    target_3:
      x:
        id: ld2450_t3_x
        internal: true
      y:
        id: ld2450_t3_y
        internal: true
      speed:
        id: ld2450_t3_speed
        internal: true
      distance:
        id: ld2450_t3_distance
        internal: true

# Globals for presence detection
globals:
  - id: presence_confidence
    type: float
    restore_value: false
    initial_value: '0.0'
  - id: ld2450_still_count
    type: int
    restore_value: false
    initial_value: '0'
  - id: ld2450_moving_count
    type: int
    restore_value: false
    initial_value: '0'

# Update presence confidence and movement counts based on sensor data
interval:
  - interval: 1s
    then:
      - lambda: |-
          // Get counts from native LD2450 component
          int targets = id(ld2450_target_count).state;
          int moving = id(ld2450_moving_target_count).state;
          int still = id(ld2450_still_target_count).state;

          id(ld2450_still_count) = still;
          id(ld2450_moving_count) = moving;

          // Update presence confidence
          if (targets > 0) {
            if (moving > 0) {
              // Movement detected - high confidence
              id(presence_confidence) = 0.9f;
            } else if (still > 0) {
              // Still presence - medium confidence
              id(presence_confidence) = 0.6f;
            } else {
              id(presence_confidence) = 0.5f;
            }
          } else {
            // No one detected
            id(presence_confidence) = 0.1f;
          }
