---
# LD2450 Radar Sensor Hardware Configuration
# Requires external component from: https://github.com/TillFleisch/ESPHome-HLK-LD2450

substitutions:
  presence_timeout: 30s

# External component for LD2450 radar (TillFleisch implementation)
external_components:
  - source:
      type: git
      url: https://github.com/TillFleisch/ESPHome-HLK-LD2450
      ref: main
    components: [ld2450]
    refresh: 1d

# UART for LD2450 Radar Sensor
uart:
  - id: ${ld2450_uart_id}
    tx_pin: ${ld2450_tx_pin}
    rx_pin: ${ld2450_rx_pin}
    baud_rate: ${ld2450_baud}
    parity: NONE
    stop_bits: 1

# LD2450 Base Component
ld2450:
  id: ld2450_radar
  uart_id: ${ld2450_uart_id}
  # Target sensor configuration
  target_count:
    id: ld2450_target_count
    internal: true
  # Three targets tracking
  targets:
    - id: ld2450_t1
      x_position:
        id: ld2450_t1_x
        internal: true
      y_position:
        id: ld2450_t1_y
        internal: true
      speed:
        id: ld2450_t1_speed
        internal: true
      distance:
        id: ld2450_t1_distance
        internal: true
    - id: ld2450_t2
      x_position:
        id: ld2450_t2_x
        internal: true
      y_position:
        id: ld2450_t2_y
        internal: true
      speed:
        id: ld2450_t2_speed
        internal: true
      distance:
        id: ld2450_t2_distance
        internal: true
    - id: ld2450_t3
      x_position:
        id: ld2450_t3_x
        internal: true
      y_position:
        id: ld2450_t3_y
        internal: true
      speed:
        id: ld2450_t3_speed
        internal: true
      distance:
        id: ld2450_t3_distance
        internal: true
  # Occupancy binary sensor
  occupancy:
    id: ld2450_occupancy
    name: "${friendly_name} Presence"
    device_class: occupancy

# Globals for presence detection (for compatibility with existing profiles)
globals:
  - id: ld2450_still_count
    type: int
    restore_value: false
    initial_value: '0'
  - id: ld2450_moving_count
    type: int
    restore_value: false
    initial_value: '0'

# Update presence confidence and movement counts based on sensor data
interval:
  - interval: 1s
    then:
      - lambda: |-
          // Calculate target counts from speeds
          int targets = id(ld2450_target_count).state;
          int moving = 0;
          int still = 0;

          // Check each target's speed to determine if moving or still
          // Speed threshold: > 0.1 m/s is considered moving
          float speed_threshold = 0.1f;

          if (id(ld2450_t1_speed).has_state() && abs(id(ld2450_t1_speed).state) > speed_threshold) {
            moving++;
          } else if (id(ld2450_t1_distance).has_state() && id(ld2450_t1_distance).state > 0) {
            still++;
          }

          if (id(ld2450_t2_speed).has_state() && abs(id(ld2450_t2_speed).state) > speed_threshold) {
            moving++;
          } else if (id(ld2450_t2_distance).has_state() && id(ld2450_t2_distance).state > 0) {
            still++;
          }

          if (id(ld2450_t3_speed).has_state() && abs(id(ld2450_t3_speed).state) > speed_threshold) {
            moving++;
          } else if (id(ld2450_t3_distance).has_state() && id(ld2450_t3_distance).state > 0) {
            still++;
          }

          id(ld2450_still_count) = still;
          id(ld2450_moving_count) = moving;

          // Update presence confidence
          if (targets > 0) {
            if (moving > 0) {
              // Movement detected - high confidence
              id(presence_confidence) = 0.9f;
            } else if (still > 0) {
              // Still presence - medium confidence
              id(presence_confidence) = 0.6f;
            } else {
              id(presence_confidence) = 0.5f;
            }
          } else {
            // No one detected
            id(presence_confidence) = 0.1f;
          }
