# ============================================================================
# DFROBOT C4001/SEN0609 24GHz mmWave RADAR - HARDWARE CONFIGURATION
# ============================================================================
# DFRobot C4001 (SEN0609) 24GHz FMCW mmWave Human Presence Detection Sensor
#
# Key Specifications:
# - Frequency: 24GHz FMCW (Frequency Modulated Continuous Wave)
# - Presence Detection Range: up to 16 meters
# - Motion Detection Range: up to 25 meters
# - Distance Measurement: 1.2m - 25m
# - Speed Measurement: 0.1 - 10 m/s
# - Detection Angle: 100 degrees horizontal
# - Interface: UART (115200 baud) or I2C (0x32)
# - Power: 5V DC, 180-250mA
#
# This file provides the base hardware setup. Sensor entities are defined
# in the expansion module or feature profile files.
#
# ============================================================================
# UART PROTOCOL OVERVIEW
# ============================================================================
# The C4001 uses a binary protocol over UART:
# - Frame Header: 0xAA 0x55
# - Data includes: presence status, distance, speed, angle
# - Baud Rate: 115200 (default)
# - Settings can be configured via UART commands
#
# For simple setups, the digital OUT pin provides direct presence detection
# without UART parsing.
#
# ============================================================================

substitutions:
  # UART Configuration
  c4001_uart_id: uart_presence
  c4001_tx_pin: GPIO1   # ESP TX -> Sensor RX
  c4001_rx_pin: GPIO2   # ESP RX <- Sensor TX
  c4001_baud: "115200"

  # GPIO Configuration (digital presence output)
  c4001_gpio_pin: GPIO5  # out1@ms11 signal

  # Detection settings
  c4001_presence_timeout: 30s
  c4001_update_interval: 500ms

  # Detection thresholds
  c4001_max_distance: "16"      # Maximum presence detection distance (m)
  c4001_min_distance: "0.3"     # Minimum detection distance (m)
  c4001_sensitivity: "5"        # Sensitivity 0-9 (higher = more sensitive)

# ============================================================================
# UART BUS FOR C4001
# ============================================================================
uart:
  - id: ${c4001_uart_id}
    tx_pin: ${c4001_tx_pin}
    rx_pin: ${c4001_rx_pin}
    baud_rate: ${c4001_baud}
    parity: NONE
    stop_bits: 1
    # Enable debug to troubleshoot communication if needed
    # debug:
    #   direction: BOTH
    #   dummy_receiver: false

# ============================================================================
# BINARY SENSORS
# ============================================================================
binary_sensor:
  # Primary presence detection via GPIO (digital output from C4001)
  - platform: gpio
    id: c4001_presence_gpio
    name: "${friendly_name} C4001 Presence"
    pin:
      number: ${c4001_gpio_pin}
      mode:
        input: true
        pulldown: true
    device_class: occupancy
    internal: true
    filters:
      - delayed_on: 100ms
      - delayed_off: ${c4001_presence_timeout}
    on_press:
      then:
        - lambda: |-
            id(presence_sensor_type) = 2;  // C4001
            id(presence_confidence) = 0.8f;
            id(presence_last_detection_ms) = millis();
            id(presence_people_count) = 1;
            ESP_LOGD("c4001", "Presence detected via GPIO");
    on_release:
      then:
        - lambda: |-
            // Decay confidence on release
            id(presence_confidence) = 0.2f;
            ESP_LOGD("c4001", "Presence cleared via GPIO");

# ============================================================================
# UART TEXT SENSOR (Raw data parsing - alternative approach)
# ============================================================================
# For parsing C4001 data frames without the dedicated component
# The C4001 outputs presence/distance data that can be parsed from UART
#
text_sensor:
  - platform: template
    id: c4001_raw_status
    name: "${friendly_name} C4001 Status"
    internal: true
    icon: mdi:radar

# ============================================================================
# SENSORS (Template sensors for unified interface)
# ============================================================================
sensor:
  # Detection distance (populated by UART parsing or estimated from GPIO)
  - platform: template
    id: c4001_distance
    name: "${friendly_name} C4001 Distance"
    unit_of_measurement: "m"
    accuracy_decimals: 2
    icon: mdi:ruler-square-compass
    internal: true
    update_interval: ${c4001_update_interval}
    lambda: |-
      return id(presence_distance);

  # Detection speed (if available from sensor)
  - platform: template
    id: c4001_speed
    name: "${friendly_name} C4001 Speed"
    unit_of_measurement: "m/s"
    accuracy_decimals: 2
    icon: mdi:speedometer
    internal: true
    update_interval: ${c4001_update_interval}
    lambda: |-
      // Speed data would come from UART parsing
      // Return 0 if not available
      return 0.0f;

# ============================================================================
# SWITCHES (Sensor control)
# ============================================================================
switch:
  # Sensor power control
  - platform: template
    id: c4001_power
    name: "${friendly_name} C4001 Power"
    internal: true
    optimistic: true
    restore_mode: RESTORE_DEFAULT_ON

# ============================================================================
# INTERVAL - C4001 Data Processing
# ============================================================================
interval:
  - interval: ${c4001_update_interval}
    then:
      - lambda: |-
          // C4001 presence detection logic
          // Using GPIO-based detection as primary method

          bool gpio_presence = id(c4001_presence_gpio).state;

          if (gpio_presence) {
            // Presence detected
            id(presence_sensor_type) = 2;  // Mark as C4001

            // Increase confidence based on detection duration
            float current = id(presence_confidence);
            if (current < 0.9f) {
              id(presence_confidence) = std::min(0.9f, current + 0.1f);
            }

            // Update detection timestamp
            id(presence_last_detection_ms) = millis();

            // Set minimum people count
            if (id(presence_people_count) < 1) {
              id(presence_people_count) = 1;
            }

          } else {
            // No presence - decay confidence
            float current = id(presence_confidence);
            if (current > 0.1f) {
              id(presence_confidence) = std::max(0.1f, current - 0.05f);
            }

            // Clear people count when confidence drops
            if (id(presence_confidence) <= 0.2f) {
              id(presence_people_count) = 0;
            }
          }

# ============================================================================
# BOOT INITIALIZATION
# ============================================================================
esphome:
  on_boot:
    - priority: 600
      then:
        - lambda: |-
            ESP_LOGI("c4001", "DFRobot C4001 radar initializing...");
            id(presence_sensor_type) = 2;  // Pre-set to C4001
    - priority: -100
      then:
        - lambda: |-
            ESP_LOGI("c4001", "DFRobot C4001 radar ready");

# ============================================================================
# NOTES
# ============================================================================
# UART Parsing Enhancement:
# For full C4001 functionality including distance/speed measurements,
# implement UART frame parsing. The C4001 protocol uses:
#
# Frame Format:
#   Header:    0xAA 0x55
#   Length:    1 byte
#   Type:      1 byte (0x01=presence, 0x02=distance, etc.)
#   Data:      Variable length
#   Checksum:  1 byte (XOR of all bytes)
#
# To implement full parsing, create a custom component or use
# the uart: read_bytes lambda approach.
#
# I2C Alternative:
# The C4001 also supports I2C at address 0x32. To use I2C instead of UART:
# 1. Remove the uart section
# 2. Add i2c sensor configuration
# 3. Wire SDA/SCL instead of TX/RX
#
# ============================================================================
