---
# Sense360 Core Ceiling - Ceiling-Mounted Smart Home Hub
#
# This is the ceiling-mounted variant of the Sense360 Core board.
# Designed for recessed ceiling installation with halo LED ring.
#
# Hardware Features:
# - ESP32-S3-WROOM-1 (8MB Flash, 2MB PSRAM)
# - WiFi 2.4GHz, Bluetooth 5.0 LE
# - Power: 240V AC / PoE (via separate power packages)
# - Dual I2C buses (halo LED ring + expansion modules)
# - UART for presence/radar sensors
# - Built-in relay for load switching (ceiling fan, lights)
# - GPIO expansion pins
# - RGB LED halo ring and status LED
#
# Pin Assignments (ESP32-S3):
# - I2C0 (Halo LED):  SDA=GPIO39, SCL=GPIO40
# - I2C1 (Expansion): SDA=GPIO21, SCL=GPIO18
# - UART:             TX=GPIO1, RX=GPIO2
# - Relay:            GPIO4 (10A AC/DC for ceiling fan/light)
# - GPIO Expansion:   GPIO5, GPIO6, GPIO7, GPIO8
# - Status LED:       GPIO48 (center indicator)
# - PIR/Motion:       GPIO47 (optional backup motion sensor)
#
# Form Factor:
# - Ceiling recessed mount
# - Halo LED ring for ambient feedback
# - Downward-facing sensors (presence, air quality)
# - Top-side power and expansion connectors
#
# Expansion Bus Pinout (10-pin connector):
# 1. GND
# 2. 3.3V (500mA max)
# 3. 5V (1A max)
# 4. I2C1 SDA (GPIO21) - for expansion modules
# 5. I2C1 SCL (GPIO18) - for expansion modules
# 6. UART TX (GPIO1)
# 7. UART RX (GPIO2)
# 8. GPIO5 (expansion)
# 9. GPIO6 (expansion)
# 10. GPIO7 (expansion/IRQ)

substitutions:
  device_name: sense360-ceiling
  friendly_name: Sense360 Ceiling
  timezone: "America/New_York"

  # Pin definitions
  # I2C buses
  halo_i2c_sda_pin: GPIO39
  halo_i2c_scl_pin: GPIO40
  expansion_i2c_sda_pin: GPIO21
  expansion_i2c_scl_pin: GPIO18

  # UART for expansion modules
  uart_tx_pin: GPIO1
  uart_rx_pin: GPIO2
  uart_baud: "256000"

  # Relay (ceiling fan/light control)
  relay_pin: GPIO4
  relay_max_current: "10A"

  # GPIO expansion pins
  expansion_gpio1: GPIO5
  expansion_gpio2: GPIO6
  expansion_gpio3: GPIO7
  expansion_gpio4: GPIO8

  # Status indicator
  status_led_pin: GPIO48
  pir_sensor_pin: GPIO47  # Optional PIR backup sensor

esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}
  project:
    name: sense360.ceiling
    version: 1.0.0
  on_boot:
    - priority: 600
      then:
        - logger.log: "Sense360 Ceiling board initializing..."
    - priority: -100
      then:
        - logger.log: "Sense360 Ceiling board ready"

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: esp-idf
    version: recommended
    sdkconfig_options:
      CONFIG_COMPILER_OPTIMIZATION_SIZE: y
      # Enable PSRAM
      CONFIG_ESP32S3_SPIRAM_SUPPORT: y
      CONFIG_SPIRAM_MODE_OCT: y

# I2C bus for Halo LED ring (primary use)
i2c:
  - id: halo_i2c
    sda: ${halo_i2c_sda_pin}
    scl: ${halo_i2c_scl_pin}
    scan: true
    frequency: 400kHz

  # I2C bus for expansion modules (air quality, comfort, etc.)
  - id: expansion_i2c
    sda: ${expansion_i2c_sda_pin}
    scl: ${expansion_i2c_scl_pin}
    scan: true
    frequency: 400kHz

# UART for expansion modules (presence sensors, etc.)
uart:
  - id: uart_bus
    tx_pin: ${uart_tx_pin}
    rx_pin: ${uart_rx_pin}
    baud_rate: ${uart_baud}

# Status LED (center indicator on ceiling unit)
status_led:
  pin:
    number: ${status_led_pin}
    inverted: true

# Main relay for ceiling fan or light control
switch:
  - platform: gpio
    name: "${friendly_name} Relay"
    id: main_relay
    pin: ${relay_pin}
    restore_mode: RESTORE_DEFAULT_OFF
    icon: mdi:electric-switch
    on_turn_on:
      - logger.log: "Ceiling relay turned ON"
    on_turn_off:
      - logger.log: "Ceiling relay turned OFF"

# Binary sensors
binary_sensor:
  - platform: status
    name: "${friendly_name} Status"
    id: system_status

  # Optional: PIR motion sensor (backup for mmWave radar)
  # Uncomment if PIR sensor is installed on GPIO47
  # - platform: gpio
    #   name: "${friendly_name} PIR Motion"
    #   id: pir_motion
    #   pin:
      #     number: ${pir_sensor_pin}
      #     mode:
        #       input: true
        #       pulldown: true
    #   device_class: motion
    #   filters:
      #     - delayed_on: 100ms
      #     - delayed_off: 5s

# System controls
button:
  - platform: restart
    id: reset_button
    name: "${friendly_name} Restart"
    icon: mdi:restart

  - platform: safe_mode
    name: "${friendly_name} Safe Mode"
    icon: mdi:safety-goggles

  - platform: factory_reset
    name: "${friendly_name} Factory Reset"
    id: factory_reset_btn
    icon: mdi:delete-forever
    disabled_by_default: true

# System sensors
sensor:
  - platform: wifi_signal
    name: "${friendly_name} WiFi Signal"
    id: wifi_signal_sensor
    update_interval: 60s
    icon: mdi:wifi

  - platform: uptime
    name: "${friendly_name} Uptime"
    id: uptime_sensor
    update_interval: 60s
    icon: mdi:clock-outline

  # Internal temperature sensor (ESP32-S3)
  - platform: internal_temperature
    name: "${friendly_name} Internal Temperature"
    id: internal_temp
    update_interval: 60s
    icon: mdi:thermometer

text_sensor:
  - platform: wifi_info
    ip_address:
      name: "${friendly_name} IP Address"
      icon: mdi:ip-network
    ssid:
      name: "${friendly_name} SSID"
      icon: mdi:wifi
    mac_address:
      name: "${friendly_name} MAC Address"
      icon: mdi:network-outline

  - platform: version
    name: "${friendly_name} ESPHome Version"
    hide_timestamp: true
    icon: mdi:information-outline
