---
# Sense360 Core - Hardware Pin Mapping
# ESP32-S3-WROOM-1-N16R8 (16MB Flash, 8MB PSRAM)
#
# Pin Map:
#   I2C Primary:   SDA=GPIO39, SCL=GPIO40 (sensors)
#   I2C Secondary: SDA=GPIO21, SCL=GPIO18 (expander)
#   UART Presence: TX=GPIO1, RX=GPIO2
#   UART Aux:      TX=GPIO43, RX=GPIO44
#   Fan PWM:       GPIO4 (output), GPIO5 (tach)
#   Relay:         GPIO10
#   Status LED:    GPIO48 (RGB), GPIO47 (simple)
#   User Button:   GPIO9
#   Expander INT:  GPIO3

substitutions:
  device_name: sense360-core
  friendly_name: Sense360 Core
  device_version: "1.0.0"
  timezone: "America/Los_Angeles"

  # I2C Primary (sensors)
  i2c0_sda_pin: GPIO39
  i2c0_scl_pin: GPIO40
  i2c0_frequency: "100000"

  # I2C Secondary (expander)
  i2c1_sda_pin: GPIO21
  i2c1_scl_pin: GPIO18
  i2c1_frequency: "400000"

  # UART Presence (LD2450: 256000, LD2412: 115200)
  uart_presence_tx_pin: GPIO1
  uart_presence_rx_pin: GPIO2
  uart_presence_baud: "256000"

  # UART Auxiliary
  uart_aux_tx_pin: GPIO43
  uart_aux_rx_pin: GPIO44
  uart_aux_baud: "115200"

  # Fan control
  fan_pwm_pin: GPIO4
  fan_tach_pin: GPIO5
  fan_pwm_frequency: "25000"

  # Outputs
  relay_pin: GPIO10
  status_led_rgb_pin: GPIO48
  status_led_simple_pin: GPIO47

  # Inputs
  user_button_pin: GPIO9
  boot_button_pin: GPIO0
  expander_int_pin: GPIO3

  # Expansion GPIOs
  expansion_gpio1: GPIO6
  expansion_gpio2: GPIO7
  expansion_gpio3: GPIO8

esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}
  project:
    name: sense360.core
    version: ${device_version}
  on_boot:
    - priority: 800
      then:
        - logger.log: "Sense360 Core initializing..."
    - priority: -100
      then:
        - logger.log: "Sense360 Core ready"

esp32:
  board: esp32-s3-devkitc-1
  variant: esp32s3
  flash_size: 16MB
  framework:
    type: esp-idf
    version: recommended
    sdkconfig_options:
      CONFIG_COMPILER_OPTIMIZATION_SIZE: y
      CONFIG_ESP32S3_SPIRAM_SUPPORT: y
      CONFIG_SPIRAM_MODE_OCT: y
      CONFIG_SPIRAM_SPEED_80M: y
      CONFIG_ESP32S3_DEFAULT_CPU_FREQ_240: y

psram:
  mode: octal
  speed: 80MHz

i2c:
  - id: i2c_primary
    sda: ${i2c0_sda_pin}
    scl: ${i2c0_scl_pin}
    scan: true
    frequency: ${i2c0_frequency}Hz

  - id: i2c_expander
    sda: ${i2c1_sda_pin}
    scl: ${i2c1_scl_pin}
    scan: true
    frequency: ${i2c1_frequency}Hz

uart:
  - id: uart_presence
    tx_pin: ${uart_presence_tx_pin}
    rx_pin: ${uart_presence_rx_pin}
    baud_rate: ${uart_presence_baud}
    parity: NONE
    stop_bits: 1

  - id: uart_auxiliary
    tx_pin: ${uart_aux_tx_pin}
    rx_pin: ${uart_aux_rx_pin}
    baud_rate: ${uart_aux_baud}
    parity: NONE
    stop_bits: 1

output:
  - platform: ledc
    id: fan_pwm_output
    pin: ${fan_pwm_pin}
    frequency: ${fan_pwm_frequency}Hz

switch:
  - platform: gpio
    name: "${friendly_name} Relay"
    id: main_relay
    pin: ${relay_pin}
    restore_mode: RESTORE_DEFAULT_OFF

  - platform: gpio
    id: expansion_out_1
    pin: ${expansion_gpio1}
    restore_mode: RESTORE_DEFAULT_OFF
    internal: true

  - platform: gpio
    id: expansion_out_2
    pin: ${expansion_gpio2}
    restore_mode: RESTORE_DEFAULT_OFF
    internal: true

  - platform: gpio
    id: expansion_out_3
    pin: ${expansion_gpio3}
    restore_mode: RESTORE_DEFAULT_OFF
    internal: true

# Simple Status LED
status_led:
  pin:
    number: ${status_led_simple_pin}
    inverted: true

# RGB Status LED
light:
  - platform: esp32_rmt_led_strip
    id: status_led_rgb
    rgb_order: GRB
    chipset: WS2812
    pin: ${status_led_rgb_pin}
    num_leds: 1
    name: "${friendly_name} Status LED"
    internal: true
    default_transition_length: 100ms

binary_sensor:
  - platform: status
    name: "${friendly_name} Status"
    id: system_status

  - platform: gpio
    name: "${friendly_name} User Button"
    id: user_button
    pin:
      number: ${user_button_pin}
      mode:
        input: true
        pullup: true
      inverted: true
    filters:
      - delayed_on: 10ms
      - delayed_off: 10ms
    on_multi_click:
      - timing:
          - ON for at most 500ms
          - OFF for at least 300ms
        then:
          - switch.toggle: main_relay
      - timing:
          - ON for at most 500ms
          - OFF for at most 300ms
          - ON for at most 500ms
          - OFF for at least 300ms
        then:
          - button.press: restart_button

  - platform: gpio
    id: expander_interrupt
    pin:
      number: ${expander_int_pin}
      mode:
        input: true
        pullup: true
      inverted: true
    internal: true

button:
  - platform: restart
    id: restart_button
    name: "${friendly_name} Restart"

  # Internal alias used by shared API actions expecting a reset_button ID
  - platform: template
    id: reset_button
    internal: true
    on_press:
      - button.press: restart_button

  - platform: safe_mode
    name: "${friendly_name} Safe Mode"

  - platform: factory_reset
    name: "${friendly_name} Factory Reset"
    id: factory_reset_btn
    disabled_by_default: true

sensor:
  - platform: wifi_signal
    name: "${friendly_name} WiFi Signal"
    id: wifi_signal_sensor
    update_interval: 60s

  - platform: uptime
    name: "${friendly_name} Uptime"
    id: uptime_sensor
    update_interval: 60s

  - platform: internal_temperature
    name: "${friendly_name} MCU Temperature"
    id: mcu_temperature
    update_interval: 60s

  - platform: pulse_counter
    id: fan_tach_sensor
    pin:
      number: ${fan_tach_pin}
      mode:
        input: true
        pullup: true
    name: "${friendly_name} Fan RPM"
    internal: true
    unit_of_measurement: "RPM"
    accuracy_decimals: 0
    update_interval: 2s
    filters:
      - multiply: 30.0

text_sensor:
  - platform: wifi_info
    ip_address:
      name: "${friendly_name} IP Address"
    ssid:
      name: "${friendly_name} SSID"
    mac_address:
      name: "${friendly_name} MAC Address"

  - platform: version
    name: "${friendly_name} ESPHome Version"
    hide_timestamp: true

globals:
  - id: i2c_primary_healthy
    type: bool
    restore_value: false
    initial_value: 'true'

  - id: i2c_expander_healthy
    type: bool
    restore_value: false
    initial_value: 'true'

  - id: uart_presence_connected
    type: bool
    restore_value: false
    initial_value: 'false'

  - id: module_airiq_present
    type: bool
    restore_value: false
    initial_value: 'false'

  - id: module_comfort_present
    type: bool
    restore_value: false
    initial_value: 'false'

  - id: module_presence_present
    type: bool
    restore_value: false
    initial_value: 'false'

  - id: module_fan_gp8403_present
    type: bool
    restore_value: false
    initial_value: 'false'

  - id: module_gpio_expander_present
    type: bool
    restore_value: false
    initial_value: 'false'

  - id: module_comfort_ceiling_present
    type: bool
    restore_value: false
    initial_value: 'false'

# ============================================================================
# I2C ADDRESS MAP (Reference)
# ============================================================================
# Address | Device           | Module          | Notes
# --------|------------------|-----------------|-----------------------------
# 0x10    | VEML7700         | Comfort Ceiling | Ambient light sensor (lux)
# 0x23    | BH1750           | Comfort         | Light sensor
# 0x44    | SHT40/SHT30      | Comfort/AirIQ   | Temp/Humidity (conflict!)
# 0x58    | GP8403           | Fan DAC         | Channel 0x58 or 0x59
# 0x59    | GP8403 alt/SGP40 | Fan DAC/Bath    | Address conflict possible
# 0x62    | SCD41            | AirIQ           | CO2 sensor
# 0x69    | SEN55            | AirIQ           | PM/VOC/NOx sensor
# 0x3E    | SX1509           | GPIO Expander   | Default address
# 0x3F    | SX1509 alt       | GPIO Expander   | Alternate address
# 0x70    | TCA9548A         | I2C Mux         | For multi-module support
# 0x76    | BME680           | Comfort         | Pressure/Gas sensor
# ============================================================================
