# ============================================================================
# Sense360 Mini Core - ESP32-S3 Hardware Configuration
# ============================================================================
# Hardware: ESP32-S3-WROOM-2
# Form Factor: Mini sensor board with AirIQ and presence detection
#
# Pin Assignments (from schematic):
# - I2C SDA: GPIO48
# - I2C SCL: GPIO45 (strapping pin - warning expected)
# - UART TX: GPIO43 (to radar RX via JST3_UART)
# - UART RX: GPIO44 (from radar TX via JST3_UART)
# - LED Data: GPIO8 (4x WS2812B via 74LVC1G07 level shifter)
# - Boot Button: GPIO0
#
# Onboard Sensors (configured in mini_onboard_sensors.yaml):
# - U4: LTR-303ALS-01 (I2C 0x29) - Ambient Light Sensor
# - U3: SHT30-DIS (I2C 0x44) - Temperature & Humidity
# - U5: SCD40-D-R2 (I2C 0x62) - CO2 Sensor
#
# External Connectors:
# - JST3_UART: TX/RX for LD2412 radar (115200 baud)
# - JST4_SEN: I2C SDA/SCL for external sensors (e.g., SEN55 @ 0x69)
# - JST4_RADAR: GPIO11/GPIO12 for TRIG/ECHO (not used with LD2412)
# ============================================================================

substitutions:
  device_name: sense360-mini
  friendly_name: Sense360 Mini
  timezone: "UTC"

  # I2C Bus Pins
  i2c_sda_pin: GPIO48
  i2c_scl_pin: GPIO45

  # UART Pins (for presence sensor)
  uart_tx_pin: GPIO43
  uart_rx_pin: GPIO44

  # LED Data Pin (WS2812B via level shifter)
  led_data_pin: GPIO8

  # Boot Button
  boot_button_pin: GPIO0

esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}
  min_version: 2024.11.0
  project:
    name: sense360.mini
    version: 3.0.0

esp32:
  board: esp32-s3-devkitc-1
  variant: esp32s3
  flash_size: 16MB
  framework:
    type: esp-idf
    version: recommended
    sdkconfig_options:
      CONFIG_ESPTOOLPY_FLASHSIZE_16MB: y
      CONFIG_ESPTOOLPY_FLASHFREQ_80M: y
      CONFIG_ESPTOOLPY_FLASHMODE_QIO: y

# ----------------------------------------------------------------------------
# I2C BUS - For sensors (SEN55, SCD40, SHT30, LTR-303)
# ----------------------------------------------------------------------------
i2c:
  - id: i2c0
    sda: ${i2c_sda_pin}
    scl: ${i2c_scl_pin}
    scan: true
    frequency: 100kHz

# ----------------------------------------------------------------------------
# SYSTEM SENSORS
# ----------------------------------------------------------------------------
binary_sensor:
  - platform: status
    name: "${friendly_name} Status"

button:
  - platform: restart
    id: reset_button
    name: "${friendly_name} Restart"
  - platform: safe_mode
    name: "${friendly_name} Safe Mode"

sensor:
  - platform: wifi_signal
    name: "${friendly_name} WiFi Signal"
    update_interval: 60s
  - platform: uptime
    name: "${friendly_name} Uptime"
    update_interval: 60s
  - platform: internal_temperature
    name: "${friendly_name} MCU Temperature"
    update_interval: 60s
