# ============================================================================
# SENSE360 CUSTOMER CONFIGURATION EXAMPLE
# ============================================================================
# Ready-to-use template for Sense360 devices with clear basic/advanced options.
# Copy this to your ESPHome dashboard and customize for your room.
#
# Filename suggestion: sense360-<room-name>.yaml
# Example: sense360-living-room.yaml, sense360-bedroom.yaml
# ============================================================================

# ----------------------------------------------------------------------------
# DEVICE IDENTIFICATION & MQTT
# ----------------------------------------------------------------------------
substitutions:
  # === REQUIRED: Customize these for your device ===
  device_name: sense360-living-room      # Unique name (lowercase, no spaces)
  friendly_name: "Living Room Sense360"  # Display name in Home Assistant

  # === MQTT Configuration (Required for AirIQ features) ===
  # Uncomment and configure these for MQTT air quality publishing:
  # airiq_mqtt_broker: !secret mqtt_broker
  # airiq_mqtt_port: "1883"  # Standard port (use 8883 for TLS)
  # airiq_mqtt_username: !secret mqtt_username
  # airiq_mqtt_password: !secret mqtt_password

# ----------------------------------------------------------------------------
# ESPHOME CONFIGURATION
# ----------------------------------------------------------------------------
esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}
  min_version: 2024.11.0  # Minimum ESPHome version required

# ----------------------------------------------------------------------------
# CHOOSE YOUR FIRMWARE VERSION
# ----------------------------------------------------------------------------
# Select ONE of the following based on your needs:
#
# BASIC VERSIONS (Recommended for most users):
# ✓ Simple, user-friendly interface
# ✓ No technical jargon
# ✓ Easy to understand readings
#
# ADVANCED VERSIONS (For power users):
# ✓ All technical sensors and data
# ✓ Customizable thresholds
# ✓ Calibration controls
# ✓ Detailed diagnostics
# ----------------------------------------------------------------------------

packages:
  sense360_firmware:
    url: https://github.com/sense360store/esphome-public
    ref: main  # Use 'main' for latest stable version
    files:
      # ═══════════════════════════════════════════════════════════════
      # OPTION 1: BASIC - Air Quality Only (Simplest)
      # ═══════════════════════════════════════════════════════════════
      # Shows: Air Quality (Excellent/Good/Fair/Poor)
      #        Temperature & Humidity
      #        Simple recommendations
      # Perfect for: Bedrooms, living rooms, general home monitoring
      # ───────────────────────────────────────────────────────────────
      - products/sense360-mini-airiq-basic.yaml

      # ═══════════════════════════════════════════════════════════════
      # OPTION 2: BASIC - Presence Detection Only
      # ═══════════════════════════════════════════════════════════════
      # Shows: Room Occupied (Yes/No)
      #        Activity Level (Still/Moving)
      # Perfect for: Smart lighting, occupancy automation
      # ───────────────────────────────────────────────────────────────
      # - products/sense360-mini-presence-basic.yaml

      # ═══════════════════════════════════════════════════════════════
      # OPTION 3: ADVANCED - Air Quality (Full Technical Suite)
      # ═══════════════════════════════════════════════════════════════
      # Shows: CO₂ (ppm), PM1.0, PM2.5, PM4.0, PM10 (µg/m³)
      #        VOC & NOx Index, Temperature, Humidity, Pressure
      #        Light Level, Customizable thresholds, Calibration
      # Perfect for: HVAC control, research, commercial applications
      # ───────────────────────────────────────────────────────────────
      # - products/sense360-mini-airiq-advanced.yaml

      # ═══════════════════════════════════════════════════════════════
      # OPTION 4: ADVANCED - Presence Detection (Full Controls)
      # ═══════════════════════════════════════════════════════════════
      # Shows: Multi-zone tracking, Individual targets (up to 3)
      #        Distance measurements, Sensitivity controls
      #        Zone configuration, Full diagnostics
      # Perfect for: Complex automations, commercial spaces
      # ───────────────────────────────────────────────────────────────
      # - products/sense360-mini-presence-advanced.yaml

    refresh: 1d  # Check for updates daily

# ----------------------------------------------------------------------------
# WIFI CONFIGURATION
# ----------------------------------------------------------------------------
# Add these values to your secrets.yaml file:
# wifi_ssid: "YourNetworkName"
# wifi_password: "YourWiFiPassword"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Fallback access point (if WiFi fails)
  ap:
    ssid: "${device_name} Fallback"
    password: "sense360config"  # Change this if desired

# ----------------------------------------------------------------------------
# HOME ASSISTANT API
# ----------------------------------------------------------------------------
# Add this to your secrets.yaml:
# api_encryption_key: "GENERATE_WITH_ESPHOME_WIZARD"

api:
  encryption:
    key: !secret api_encryption_key

# ----------------------------------------------------------------------------
# OVER-THE-AIR UPDATES
# ----------------------------------------------------------------------------
# Add this to your secrets.yaml:
# ota_password: "your-secure-password"

ota:
  - platform: esphome
    password: !secret ota_password

# ----------------------------------------------------------------------------
# MQTT CONFIGURATION (Required for AirIQ Air Quality Publishing)
# ----------------------------------------------------------------------------
# If using the AirIQ air quality features, MQTT is required to publish data.
# For Home Assistant's Mosquitto add-on:
# 1. Install Mosquitto broker add-on in Home Assistant
# 2. Create a user in: Settings > Add-ons > Mosquitto broker > Configuration
# 3. Add credentials to your secrets.yaml:
#    mqtt_broker: "192.168.x.x"    # Your Home Assistant IP
#    mqtt_port: "1883"             # Default MQTT port
#    mqtt_username: "your_mqtt_user"
#    mqtt_password: "your_mqtt_password"

# To disable MQTT entirely (if not using AirIQ features), add:
# mqtt: null

# ----------------------------------------------------------------------------
# OPTIONAL: ADVANCED THRESHOLD CUSTOMIZATION
# ----------------------------------------------------------------------------
# Only needed if you're using an ADVANCED version and want custom thresholds.
# Uncomment and adjust any values you want to change:

# substitutions:
#   # Air Quality Thresholds (Advanced version only)
#   co2_good_limit: "800"            # Default: 750 ppm
#   co2_moderate_limit: "1000"       # Default: 950 ppm
#   co2_unhealthy_limit: "1500"      # Default: 1400 ppm
#
#   pm2_5_good_limit: "12"           # Default: 10 µg/m³
#   pm2_5_moderate_limit: "30"       # Default: 25 µg/m³
#   pm2_5_unhealthy_limit: "60"      # Default: 55 µg/m³
#
#   voc_good_limit: "100"            # Default: 80 (index)
#   voc_moderate_limit: "150"        # Default: 120 (index)
#
#   # Presence Detection Settings (Advanced version only)
#   presence_timeout: "60"           # Default: 30 seconds
#   detection_threshold: "25"        # Default: 30 percent

# ----------------------------------------------------------------------------
# OPTIONAL: CUSTOM AUTOMATIONS
# ----------------------------------------------------------------------------
# Add your custom sensors, automations, or overrides below this line.

# Example: High CO2 Alert (Advanced version only)
# binary_sensor:
#   - platform: template
#     name: "${friendly_name} High CO2 Alert"
#     lambda: |-
#       return id(co2_ppm).state > 1200;

# Example: Automatic Ventilation Control (Advanced version only)
# switch:
#   - platform: gpio
#     name: "${friendly_name} Exhaust Fan"
#     pin: GPIO25
#     on_turn_on:
#       - delay: 600s  # Run for 10 minutes
#       - switch.turn_off: exhaust_fan

# Example: Occupancy-Based Lighting (Basic version works)
# light:
#   - platform: binary
#     name: "${friendly_name} Auto Light"
#     output: light_output
#     on_turn_on:
#       - if:
#           condition:
#             binary_sensor.is_on: room_occupied
#           then:
#             - light.turn_on: auto_light

# ============================================================================
# QUICK START GUIDE
# ============================================================================
#
# STEP 1: Choose your version
# ────────────────────────────
# Uncomment ONE of the product files above based on your needs:
# - Basic Air Quality: Simple air quality monitoring
# - Basic Presence: Simple room occupancy detection
# - Advanced Air Quality: Full technical air quality suite
# - Advanced Presence: Advanced presence detection with zones
#
# STEP 2: Update device name
# ────────────────────────────
# Change 'device_name' and 'friendly_name' to match your room
#
# STEP 3: Add secrets
# ────────────────────────────
# Add to your secrets.yaml:
#   wifi_ssid: "YourNetwork"
#   wifi_password: "YourPassword"
#   api_encryption_key: "GENERATE_THIS_WITH_ESPHOME"
#   ota_password: "your-password"
#
# STEP 4: Upload to device
# ────────────────────────────
# Connect via USB and upload using ESPHome dashboard
#
# ============================================================================
# SUPPORT & DOCUMENTATION
# ============================================================================
# Installation Guide:
#   https://github.com/sense360store/esphome-public/blob/main/docs/installation.md
# Configuration:
#   https://github.com/sense360store/esphome-public/blob/main/docs/configuration.md
# Troubleshooting:
#   https://github.com/sense360store/esphome-public/blob/main/docs/troubleshooting.md
# Support:
#   https://github.com/sense360store/esphome-public/issues
# ============================================================================
