---
# ============================================================================
# SENSE360 MINI - AIR QUALITY (ADVANCED)
# ============================================================================
# Advanced air quality monitoring with full sensor suite and technical controls.
# Perfect for: IAQ monitoring, HVAC optimization, research, commercial use
#
# Features:
# - All individual sensors (CO2, PM1.0, PM2.5, PM4.0, PM10, VOC, NOx)
# - Temperature, Humidity, Pressure, Light level
# - Customizable thresholds for every sensor
# - Sensor calibration controls
# - Historical data and trends
# - HVAC integration readiness
# - Full diagnostic information
#
# For technical users who want complete air quality data and control.
# ============================================================================

substitutions:
  # Device identity (override these for your install)
  device_name: sense360-mini-airiq-adv  # Lowercase letters, numbers, hyphens, or underscores
  friendly_name: Sense360 Mini AirIQ  # Customize the display name shown in dashboards
  timezone: UTC  # Set to your local timezone, e.g., America/New_York

  # Hardware pins (ESP32-S3 DevKit)
  board_variant: esp32-s3-devkitc-1

  # I2C Bus for sensors
  i2c_sda_pin: GPIO21
  i2c_scl_pin: GPIO22
  i2c_frequency: 100kHz

  # Status LED
  status_led_pin: GPIO2

  # WiFi & Logging
  wifi_fast_connect: "true"
  log_level: DEBUG  # Detailed logging for advanced users

  # Customizable thresholds (users can override)
  co2_good_limit: "750"
  co2_moderate_limit: "950"
  co2_unhealthy_limit: "1400"

  pm2_5_good_limit: "10"
  pm2_5_moderate_limit: "25"
  pm2_5_unhealthy_limit: "55"

  voc_good_limit: "80"
  voc_moderate_limit: "120"
  voc_unhealthy_limit: "180"

# ----------------------------------------------------------------------------
# ESPHOME CORE
# ----------------------------------------------------------------------------
esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}
  min_version: 2024.11.0
  project:
    name: sense360.mini-airiq-advanced
    version: "3.0.0"

# ----------------------------------------------------------------------------
# ESP32 CONFIGURATION
# ----------------------------------------------------------------------------
esp32:
  board: ${board_variant}
  framework:
    type: esp-idf
    version: recommended
    sdkconfig_options:
      CONFIG_ESPTOOLPY_FLASHSIZE_16MB: y
      CONFIG_ESPTOOLPY_FLASHFREQ_80M: y
      CONFIG_ESPTOOLPY_FLASHMODE_QIO: y

# ----------------------------------------------------------------------------
# BASE PACKAGES - Core system components
# ----------------------------------------------------------------------------
packages:
  base_wifi: !include ../packages/base/wifi.yaml
  base_api: !include ../packages/base/api_encrypted.yaml
  base_ota: !include ../packages/base/ota.yaml
  base_time: !include ../packages/base/time.yaml
  base_logging: !include ../packages/base/logging.yaml
  base_bluetooth: !include ../packages/base/bluetooth_proxy.yaml
  # AIR QUALITY FEATURES - Advanced Profile
  airiq_features: !include ../packages/features/airiq_advanced.yaml
  # Device Health & Diagnostics
  device_health: !include ../packages/features/device_health.yaml
  diagnostics: !include ../packages/features/diagnostics.yaml

# ----------------------------------------------------------------------------
# I2C BUS - For air quality sensors
# ----------------------------------------------------------------------------
i2c:
  - id: i2c0
    sda: ${i2c_sda_pin}
    scl: ${i2c_scl_pin}
    scan: true
    frequency: ${i2c_frequency}

# ----------------------------------------------------------------------------
# FULL SENSOR SUITE
# ----------------------------------------------------------------------------
sensor:
  # ===== SEN55 - Complete Particulate Matter + Environmental Suite =====
  - platform: sen5x
    id: sen55
    i2c_id: i2c0
    address: 0x69
    update_interval: 30s  # Faster updates for advanced users

    # PM1.0 - Finest particles
    pm_1_0:
      id: sen55_pm1
      internal: true
      accuracy_decimals: 1
      filters:
        - sliding_window_moving_average:
            window_size: 5
            send_every: 1
      on_value:
        then:
          - lambda: 'id(pm1_0).publish_state(x);'
          - script.execute: calculate_advanced_aqi

    # PM2.5 - Most health-relevant
    pm_2_5:
      id: sen55_pm25
      internal: true
      accuracy_decimals: 1
      filters:
        - sliding_window_moving_average:
            window_size: 5
            send_every: 1
      on_value:
        then:
          - lambda: 'id(pm2_5).publish_state(x);'
          - script.execute: calculate_advanced_aqi

    # PM4.0 - Respirable particles
    pm_4_0:
      id: sen55_pm4
      internal: true
      accuracy_decimals: 1
      on_value:
        then:
          - lambda: 'id(pm4_0).publish_state(x);'

    # PM10 - Inhalable particles
    pm_10_0:
      id: sen55_pm10
      internal: true
      accuracy_decimals: 1
      on_value:
        then:
          - lambda: 'id(pm10).publish_state(x);'

    # Temperature from SEN55
    temperature:
      id: sen55_temp
      name: "${friendly_name} Temperature (SEN55)"
      accuracy_decimals: 1
      on_value:
        then:
          - lambda: 'id(room_temperature).publish_state(x);'

    # Humidity from SEN55
    humidity:
      id: sen55_humidity
      name: "${friendly_name} Humidity (SEN55)"
      accuracy_decimals: 1
      on_value:
        then:
          - lambda: 'id(room_humidity).publish_state(x);'

    # VOC Index (0-500)
    voc:
      id: sen55_voc
      internal: true
      on_value:
        then:
          - lambda: 'id(voc_index).publish_state(x);'
          - script.execute: calculate_advanced_aqi

    # NOx Index (0-500)
    nox:
      id: sen55_nox
      internal: true
      on_value:
        then:
          - lambda: 'id(nox_index).publish_state(x);'

  # ===== SCD4x - Precision CO2 Sensor =====
  - platform: scd4x
    id: scd4x_sensor
    i2c_id: i2c0
    address: 0x62
    update_interval: 30s
    automatic_self_calibration: true
    altitude_compensation: 0m  # Users can adjust this
    ambient_pressure_compensation_source: pressure_sensor

    co2:
      id: scd4x_co2
      internal: true
      on_value:
        then:
          - lambda: 'id(co2_ppm).publish_state(x);'
          - script.execute: calculate_advanced_aqi

    temperature:
      id: scd4x_temp
      name: "${friendly_name} Temperature (SCD4x)"
      accuracy_decimals: 2

    humidity:
      id: scd4x_humidity
      name: "${friendly_name} Humidity (SCD4x)"
      accuracy_decimals: 1

  # ===== BMP280 - Atmospheric Pressure =====
  - platform: bmp280_i2c
    i2c_id: i2c0
    address: 0x76
    update_interval: 60s

    temperature:
      id: bmp280_temp
      name: "${friendly_name} Temperature (BMP280)"
      accuracy_decimals: 1

    pressure:
      id: pressure_sensor
      internal: true
      accuracy_decimals: 1
      on_value:
        then:
          - lambda: 'id(atmospheric_pressure).publish_state(x);'

  # ===== LTR303 - Light Sensor =====
  - platform: ltr390
    i2c_id: i2c0
    address: 0x53
    ambient_light:
      id: light_sensor
      internal: true
      on_value:
        then:
          - lambda: 'id(illuminance).publish_state(x);'

  # ===== STATISTICS & TRENDS (24-hour moving averages) =====
  - platform: template
    name: "${friendly_name} CO₂ 24h Average"
    icon: "mdi:chart-line"
    unit_of_measurement: "ppm"
    accuracy_decimals: 0
    state_class: measurement
    update_interval: 300s
    lambda: |-
      if (id(scd4x_co2).has_state()) {
        return id(scd4x_co2).state;
      }
      return {};
    filters:
      - sliding_window_moving_average:
          window_size: 288  # 24 hours at 5-minute intervals
          send_every: 1

  - platform: template
    name: "${friendly_name} PM2.5 24h Average"
    icon: "mdi:chart-line"
    unit_of_measurement: "µg/m³"
    accuracy_decimals: 1
    state_class: measurement
    update_interval: 300s
    lambda: |-
      if (id(sen55_pm25).has_state()) {
        return id(sen55_pm25).state;
      }
      return {};
    filters:
      - sliding_window_moving_average:
          window_size: 288
          send_every: 1

# ----------------------------------------------------------------------------
# ADVANCED AQI CALCULATION
# ----------------------------------------------------------------------------
script:
  - id: calculate_advanced_aqi
    mode: restart
    then:
      - script.execute: evaluate_air_quality

# ----------------------------------------------------------------------------
# SENSOR CALIBRATION CONTROLS
# ----------------------------------------------------------------------------
button:
  # CO2 Sensor Calibration
  - platform: template
    name: "${friendly_name} Calibrate CO₂ (400ppm)"
    icon: "mdi:molecule-co2"
    entity_category: config
    on_press:
      - scd4x.perform_forced_calibration:
          id: scd4x_sensor
          value: 400
      - logger.log: "CO2 sensor calibrated to 400ppm (outdoor air)"

  - platform: template
    name: "${friendly_name} Calibrate CO₂ (Custom)"
    icon: "mdi:molecule-co2"
    entity_category: config
    on_press:
      - scd4x.perform_forced_calibration:
          id: scd4x_sensor
          value: !lambda 'return id(co2_calibration_value).state;'
      - logger.log:
          format: "CO2 sensor calibrated to %.0fppm"
          args: ['id(co2_calibration_value).state']

  # Factory reset CO2 sensor
  - platform: template
    name: "${friendly_name} Factory Reset CO₂"
    icon: "mdi:restore"
    entity_category: config
    on_press:
      - scd4x.factory_reset:
          id: scd4x_sensor
      - logger.log: "CO2 sensor factory reset"
      - delay: 2s
      - component.update: scd4x_sensor

  # SEN55 Fan Cleaning
  - platform: template
    name: "${friendly_name} Clean SEN55 Fan"
    icon: "mdi:fan-auto"
    entity_category: diagnostic
    on_press:
      - sen5x.start_fan_autoclean:
          id: sen55
      - logger.log: "SEN55 fan cleaning started (10 seconds)"

  # Restart all sensors
  - platform: template
    name: "${friendly_name} Restart Sensors"
    icon: "mdi:restart"
    entity_category: diagnostic
    on_press:
      - logger.log: "Restarting all sensors..."
      - component.update: sen55
      - component.update: scd4x_sensor

# ----------------------------------------------------------------------------
# ADVANCED CALIBRATION INPUTS
# ----------------------------------------------------------------------------
number:
  # Custom CO2 calibration value
  - platform: template
    id: co2_calibration_value
    name: "${friendly_name} CO₂ Calibration Value"
    icon: "mdi:molecule-co2"
    unit_of_measurement: "ppm"
    entity_category: config
    min_value: 400
    max_value: 5000
    step: 50
    mode: box
    optimistic: true
    restore_value: true
    initial_value: 400

  # Altitude compensation for CO2 sensor
  - platform: template
    id: altitude_compensation
    name: "${friendly_name} Altitude"
    icon: "mdi:elevation-rise"
    unit_of_measurement: "m"
    entity_category: config
    min_value: 0
    max_value: 3000
    step: 100
    mode: box
    optimistic: true
    restore_value: true
    initial_value: 0

# ----------------------------------------------------------------------------
# STATUS LED
# ----------------------------------------------------------------------------
light:
  - platform: status_led
    id: device_status_led
    name: "${friendly_name} Status LED"
    pin: ${status_led_pin}
    restore_mode: ALWAYS_ON

# ----------------------------------------------------------------------------
# ADVANCED CONTROLS
# ----------------------------------------------------------------------------
# Note: Restart and Safe Mode buttons are provided by hardware config

switch:
  # Automatic calibration toggle
  - platform: template
    name: "${friendly_name} Auto Calibration"
    icon: "mdi:auto-mode"
    entity_category: config
    optimistic: true
    restore_value: true
    initial_state: true

  # Data logging (for research/analysis)
  - platform: template
    name: "${friendly_name} Extended Logging"
    icon: "mdi:math-log"
    entity_category: diagnostic
    optimistic: true
    restore_value: true
    initial_state: false
    on_turn_on:
      - logger.log:
          level: INFO
          format: "Extended logging enabled"
    on_turn_off:
      - logger.log:
          level: INFO
          format: "Extended logging disabled"

# ----------------------------------------------------------------------------
# HVAC INTEGRATION HELPERS
# ----------------------------------------------------------------------------
binary_sensor:
  # Ventilation needed signal
  - platform: template
    name: "${friendly_name} Ventilation Needed"
    icon: "mdi:air-filter"
    device_class: problem
    lambda: |-
      // Trigger when CO2 > 1200ppm OR PM2.5 > 35µg/m³
      bool needs_vent = false;
      if (id(co2_ppm).has_state() && id(co2_ppm).state > 1200) {
        needs_vent = true;
      }
      if (id(pm2_5).has_state() && id(pm2_5).state > 35) {
        needs_vent = true;
      }
      return needs_vent;

# ----------------------------------------------------------------------------
# NOTES FOR ADVANCED USERS
# ----------------------------------------------------------------------------
# To use this configuration:
#
# 1. Create your device config (e.g., sense360-office.yaml)
# 2. Add this package:
#
#    packages:
#      sense360_firmware:
#        url: https://github.com/sense360store/esphome-public
#        ref: v3.0.0
#        files:
#          - products/sense360-mini-airiq-advanced.yaml
#        refresh: 1d
#
# 3. Customize with your parameters:
#
#    substitutions:
#      device_name: sense360-office
#      friendly_name: "Office IAQ Monitor"
#      co2_good_limit: "800"  # Custom threshold
#      altitude_compensation: "500"  # Your altitude in meters
#
# Advanced features:
# - All individual sensor readings (CO2, PM1/2.5/4/10, VOC, NOx)
# - Customizable thresholds for every parameter
# - Sensor calibration controls
# - 24-hour trend analysis
# - HVAC integration readiness
# - Extended diagnostic logging
# ============================================================================
