# ============================================================================
# SENSE360 CORE WALL - PRESENCE ONLY
# ============================================================================
# SKU: S360-CORE-W + S360-PRES-W
#
# Wall/desk-mounted occupancy and presence detection.
# Ideal for lighting automation and HVAC optimization.
#
# Hardware: ESP32-S3-WROOM-1 (8MB Flash, 2MB PSRAM)
#
# Included Modules:
# - Presence: HLK-LD2450 or DFRobot C4001 mmWave Radar
# - LED Ring: Wall LED for visual feedback
# - Physical Buttons: For manual control
#
# Supported Presence Sensors:
# - HLK-LD2450: Multi-target tracking (up to 3 targets), distance/angle
# - DFRobot C4001: 16m presence range, 25m motion range, speed measurement
#
# Customer usage in their ESPHome config:
# packages:
#   sense360_firmware:
#     url: https://github.com/sense360store/esphome-public
#     ref: v2.2.0
#     files:
#       - products/sense360-core-wall-presence.yaml
#     refresh: 1d
# ============================================================================

substitutions:
  # === Device Configuration ===
  device_name: sense360-core-wall-presence
  friendly_name: Sense360 Core Wall Presence
  timezone: "America/New_York"

  # === Logging ===
  log_level: INFO

  # === WiFi Behavior ===
  wifi_fast_connect: "false"

  # === Security (users MUST define these in their config) ===
  api_key: !secret api_encryption_key
  ota_password: !secret ota_password
  fallback_ap_password: "Sense360Fallback"

# ============================================================================
# PACKAGE INCLUDES
# ============================================================================
packages:
  # === External Components (LD2450 radar support) ===
  external_components: !include ../packages/base/external_components.yaml

  # === Base System Components ===
  base_wifi: !include ../packages/base/wifi.yaml
  base_logging: !include ../packages/base/logging.yaml
  base_api: !include ../packages/base/api_encrypted.yaml
  base_ota: !include ../packages/base/ota.yaml
  base_time: !include ../packages/base/time.yaml

  # === Core Hardware (Wall Board) ===
  core_hardware: !include ../packages/hardware/sense360_core_wall.yaml

  # === LED Ring ===
  led_ring: !include ../packages/hardware/led_ring_wall.yaml

  # === Presence Module (mmWave radar) ===
  presence_module: !include ../packages/expansions/presence_wall.yaml
  presence_profile: !include ../packages/features/presence_basic_profile.yaml

  # === Device Health & Diagnostics ===
  health: !include ../packages/features/device_health.yaml
