---
# Sense360 Core - Basic Test Configuration
#
# This is a minimal test configuration for the Sense360 Core board.
# It includes only the core board and base packages to verify functionality.
#
# Use this for:
# - Initial board testing
# - Development and debugging
# - Validating core board functionality
#
# This configuration uses PoE power by default.

packages:
  # Base system packages
  base: !include ../packages/base/complete.yaml

  # Core board hardware
  core: !include ../packages/hardware/sense360_core.yaml

  # Power configuration (choose one)
  power: !include ../packages/hardware/power_poe.yaml
  # power: !include ../packages/hardware/power_240v.yaml
  # power: !include ../packages/hardware/power_usb.yaml

substitutions:
  device_name: sense360-core-test
  friendly_name: "Sense360 Core Test"

  # Logging configuration
  log_level: INFO

  # Override timezone if needed
  timezone: "America/Los_Angeles"

# Optional: Add WiFi credentials here or use secrets
# wifi:
#   ssid: !secret wifi_ssid
#   password: !secret wifi_password
