---
# ============================================================================
# SENSE360 CEILING + PRESENCE (DFRobot C4001) - PRODUCT CONFIGURATION
# ============================================================================
# This configuration is for ceiling-mounted Sense360 with DFRobot C4001
# long-range mmWave presence detection (up to 25m motion, 16m presence).
#
# Hardware: Presence_Module_ceiling with DFRobot SEN0609/C4001 sensor
#
# Customer usage:
# packages:
#   sense360_firmware:
#     url: https://github.com/sense360store/esphome-public
#     ref: v2.2.0
#     files:
#       - products/sense360-ceiling-presence-c4001.yaml
#
# ============================================================================
# SENSOR COMPARISON
# ============================================================================
# DFRobot C4001 vs Hi-Link LD2450:
#
# C4001 Advantages:
#   - Longer range: 25m motion / 16m presence (vs 6m for LD2450)
#   - Wider angle: 100 degrees horizontal
#   - Speed measurement: 0.1 - 10 m/s
#   - Simpler GPIO-based presence output
#
# LD2450 Advantages:
#   - Multi-target tracking (up to 3 people)
#   - Zone configuration
#   - Coordinates for each target (X, Y)
#   - Better for complex presence logic
#
# Choose C4001 for: Large rooms, high ceilings, simple presence detection
# Choose LD2450 for: Multi-occupancy tracking, zone-based automation
# ============================================================================

substitutions:
  # === Hardware Configuration ===
  board_variant: esp32-s3-devkitc-1
  log_level: INFO
  timezone: "UTC"

  # === Device Naming ===
  device_name: sense360-ceiling-c4001
  friendly_name: Sense360 Ceiling C4001

  # === I2C Bus Pins (Ceiling Core Board) ===
  i2c_sda_pin: GPIO21
  i2c_scl_pin: GPIO18

  # === C4001 Presence Sensor Configuration ===
  c4001_uart_id: uart_presence
  c4001_tx_pin: GPIO1
  c4001_rx_pin: GPIO2
  c4001_baud: "115200"
  c4001_gpio_pin: GPIO5  # Digital presence output (out1@ms11)

  # === Detection Settings ===
  c4001_max_distance: "16"     # Presence detection range (m)
  c4001_sensitivity: "5"       # 0-9 (higher = more sensitive)
  presence_timeout: 30s

  # === WiFi Behavior ===
  wifi_fast_connect: "true"

  # === Security (users MUST define these in secrets.yaml) ===
  api_key: !secret api_encryption_key
  ota_password: !secret ota_password

# ----------------------------------------------------------------------------
# PACKAGE INCLUDES
# ----------------------------------------------------------------------------

packages:
  # === Base System ===
  base_wifi: !include ../base/wifi.yaml
  base_logging: !include ../base/logging.yaml
  base_api: !include ../base/api_encrypted.yaml
  base_ota: !include ../base/ota.yaml
  base_time: !include ../base/time.yaml
  base_bluetooth: !include ../base/bluetooth_proxy.yaml

  # === Hardware (Ceiling variant) ===
  core_hardware: !include ../hardware/sense360_core_ceiling.yaml

  # === Presence Module Ceiling Expansion ===
  presence_expansion: !include ../packages/expansions/presence_module_ceiling.yaml

  # === C4001 Radar Hardware Driver ===
  presence_hardware: !include ../hardware/presence_dfrobot_c4001.yaml

  # === Features (Basic presence profile for ceiling) ===
  presence_detection: !include ../features/presence_basic_profile.yaml

# ----------------------------------------------------------------------------
# ADDITIONAL CONFIGURATION
# ----------------------------------------------------------------------------

esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}
  comment: "Sense360 Ceiling with DFRobot C4001 25m Presence Detection"
  project:
    name: sense360.ceiling-c4001
    version: "1.0.0"

# Override UART configuration for C4001 baud rate
uart:
  - id: ${c4001_uart_id}
    tx_pin: ${c4001_tx_pin}
    rx_pin: ${c4001_rx_pin}
    baud_rate: ${c4001_baud}
    parity: NONE
    stop_bits: 1

# Additional sensors specific to C4001 long-range detection
sensor:
  # Room occupancy estimation based on detection patterns
  - platform: template
    id: room_occupancy_estimate
    name: "${friendly_name} Room Occupancy"
    unit_of_measurement: "people"
    accuracy_decimals: 0
    icon: mdi:account-multiple
    lambda: |-
      return id(presence_people_count);
    update_interval: 5s

# Binary sensors
binary_sensor:
  # Long-range presence (C4001 specialty)
  - platform: template
    id: long_range_presence
    name: "${friendly_name} Long Range Presence"
    device_class: occupancy
    lambda: |-
      return id(presence_confidence) >= 0.4f;

# Text sensors
text_sensor:
  # Detection zone indicator
  - platform: template
    id: detection_zone
    name: "${friendly_name} Detection Zone"
    icon: mdi:map-marker-radius
    lambda: |-
      float dist = id(presence_distance);
      if (dist <= 0) {
        return std::string("No Detection");
      } else if (dist < 3.0f) {
        return std::string("Near (0-3m)");
      } else if (dist < 8.0f) {
        return std::string("Mid (3-8m)");
      } else if (dist < 16.0f) {
        return std::string("Far (8-16m)");
      } else {
        return std::string("Extended (16m+)");
      }
    update_interval: 2s
