# =============================================================================
# SENSE360 MINI + PRESENCE ONLY (LD2412) - PRODUCT CONFIGURATION
# =============================================================================
# This configuration uses the LD2412 radar with the basic presence profile.
#
# Customer usage:
# packages:
#   sense360_firmware:
#     url: https://github.com/sense360store/esphome-public
#     ref: v2.1.0
#     files:
#       - products/sense360-mini-presence-ld2412.yaml
# =============================================================================

substitutions:
  # === Hardware Configuration ===
  board_variant: esp32-s3-devkitc-1
  log_level: INFO
  timezone: "UTC"

  # === I2C Bus Pins (Mini Core Board) ===
  i2c_sda_pin: GPIO48
  i2c_scl_pin: GPIO45

  # === LD2412 Presence Sensor UART ===
  ld2412_uart_id: uart_ld2412
  ld2412_tx_pin: GPIO12
  ld2412_rx_pin: GPIO13
  ld2412_baud: "115200"

  # === WiFi Behavior ===
  wifi_fast_connect: "true"

  # === Security (users MUST define these) ===
  api_key: !secret api_encryption_key
  ota_password: !secret ota_password

# ----------------------------------------------------------------------------
# PACKAGE INCLUDES
# ----------------------------------------------------------------------------

packages:
  # === External Components ===
  external_components: !include ../packages/base/external_components.yaml

  # === Base System ===
  base_wifi: !include ../packages/base/wifi.yaml
  base_logging: !include ../packages/base/logging.yaml
  base_api: !include ../packages/base/api_encrypted.yaml
  base_ota: !include ../packages/base/ota.yaml
  base_time: !include ../packages/base/time.yaml
  base_bluetooth: !include ../packages/base/bluetooth_proxy.yaml

  # === Hardware ===
  core_hardware: !include ../packages/hardware/sense360_core_mini.yaml
  presence_hardware: !include ../packages/hardware/presence_ld2412.yaml

  # === Features ===
  presence_detection: !include ../packages/features/presence_basic_profile_ld2412.yaml
