# =============================================================================
# SENSE360 MINI + AIRIQ (LD2412) - COMPLETE PRODUCT CONFIGURATION
# =============================================================================
# This is the main configuration file for Sense360 Mini with full AirIQ sensor
# suite and LD2412 presence detection.
# Audience: **Internal use.** Legacy Mini product configuration.
# For modular composition, see packages/ directory structure.
#
# Customer usage in their ESPHome config:
# packages:
#   sense360_firmware:
#     url: https://github.com/sense360store/esphome-public
#     ref: v2.1.0
#     files:
#       - products/sense360-mini-airiq-ld2412.yaml
#     refresh: 1d
# =============================================================================

# ----------------------------------------------------------------------------
# DEFAULT SUBSTITUTIONS
# Users can override any of these in their main config file
# ----------------------------------------------------------------------------

substitutions:
  # === Hardware Configuration ===
  board_variant: esp32-s3-devkitc-1
  log_level: INFO
  timezone: "UTC"

  # === I2C Bus Pins (Mini Core Board) ===
  i2c_sda_pin: GPIO48
  i2c_scl_pin: GPIO45

  # === LD2412 Presence Sensor UART ===
  ld2412_uart_id: uart_ld2412
  ld2412_tx_pin: GPIO43
  ld2412_rx_pin: GPIO44
  ld2412_baud: "115200"

  # === Addressable LED Configuration (4x WS2812B via level shifter) ===
  led_data_pin: GPIO8
  led_count: "4"
  led_chipset: WS2812
  led_rgb_order: GRB

  # === WiFi Behavior ===
  wifi_fast_connect: "true"  # Skip SSID scan for faster connection

  # === MQTT Configuration ===
  # Users MUST configure these in their device config to enable MQTT publishing.
  # Leave broker empty to disable MQTT, or set to your broker's IP address.
  # Example for Home Assistant Mosquitto add-on:
  #   airiq_mqtt_broker: "192.168.x.x"  # Your Home Assistant IP
  #   airiq_mqtt_port: "1883"           # Standard MQTT port
  #   airiq_mqtt_username: !secret mqtt_username
  #   airiq_mqtt_password: !secret mqtt_password
  airiq_mqtt_broker: ""
  # airiq_mqtt_username and airiq_mqtt_password inherit from airiq_basic_profile.yaml

  # === CO2 Air Quality Thresholds (ppm) ===
  co2_good_limit: "750"  # Good: < 750 ppm
  co2_moderate_limit: "950"  # Moderate: 750-950 ppm
  co2_unhealthy_limit: "1400"  # Unhealthy: 950-1400 ppm (Poor: > 1400)

  # === PM1.0 Thresholds (µg/m³) ===
  sen55_pm1_good_limit: "5"
  sen55_pm1_moderate_limit: "12"
  sen55_pm1_unhealthy_limit: "35"

  # === PM2.5 Thresholds (µg/m³) ===
  sen55_pm2_5_good_limit: "10"  # WHO guideline: 10 µg/m³
  sen55_pm2_5_moderate_limit: "25"
  sen55_pm2_5_unhealthy_limit: "55"

  # === PM4.0 Thresholds (µg/m³) ===
  sen55_pm4_0_good_limit: "15"
  sen55_pm4_0_moderate_limit: "30"
  sen55_pm4_0_unhealthy_limit: "60"

  # === PM10 Thresholds (µg/m³) ===
  sen55_pm10_good_limit: "20"
  sen55_pm10_moderate_limit: "50"
  sen55_pm10_unhealthy_limit: "100"

  # === VOC Index Thresholds (0-500 scale) ===
  sen55_voc_good_limit: "80"
  sen55_voc_moderate_limit: "120"
  sen55_voc_unhealthy_limit: "180"

  # === NOx Index Thresholds (0-500 scale) ===
  sen55_nox_good_limit: "80"
  sen55_nox_moderate_limit: "120"
  sen55_nox_unhealthy_limit: "180"

# ----------------------------------------------------------------------------
# PACKAGE INCLUDES
# Load all firmware components from the repository
# ----------------------------------------------------------------------------

packages:
  # === External Components ===
  external_components: !include ../packages/base/external_components.yaml

  # === Base System Configuration ===
  base_wifi: !include ../packages/base/wifi.yaml
  base_logging: !include ../packages/base/logging.yaml
  base_api: !include ../packages/base/api_encrypted.yaml
  base_ota: !include ../packages/base/ota.yaml
  base_time: !include ../packages/base/time.yaml
  base_bluetooth: !include ../packages/base/bluetooth_proxy.yaml

  # === Hardware Drivers ===
  core_hardware: !include ../packages/hardware/sense360_core_mini.yaml
  presence_hardware: !include ../packages/hardware/presence_ld2412.yaml
  # Onboard sensors: LTR-303 (Lux), SHT30 (Temp/Humidity), SCD40 (CO2)
  onboard_sensors: !include ../packages/hardware/mini_onboard_sensors.yaml

  # === Feature Profiles ===
  airiq_sensors: !include ../packages/features/airiq_advanced.yaml
  presence_detection: !include ../packages/features/presence_basic_profile_ld2412.yaml
  status_leds: !include ../packages/features/mini_four_leds_air_quality.yaml

# ----------------------------------------------------------------------------
# USAGE NOTES FOR CUSTOMERS
# ----------------------------------------------------------------------------

# To use this configuration in your device:
#
# 1. Create your device config file (e.g., sense360-living-room.yaml)
# 2. Add this package reference:
#
#    packages:
#      sense360_firmware:
#        url: https://github.com/sense360store/esphome-public
#        ref: v2.1.0
#        files:
#          - products/sense360-mini-airiq-ld2412.yaml
#        refresh: 1d
#
# 3. Define your device name and secrets:
#
#    substitutions:
#      device_name: sense360-living-room
#      friendly_name: "Living Room Sense360"
#
#    wifi:
#      ssid: !secret wifi_ssid
#      password: !secret wifi_password
#
#    api:
#      encryption:
#        key: !secret api_encryption_key
#
#    ota:
#      - platform: esphome
#        password: !secret ota_password
#
# 4. Optionally override any thresholds:
#
#    substitutions:
#      co2_good_limit: "800"  # Custom CO2 threshold
#      sen55_pm2_5_good_limit: "12"  # Custom PM2.5 threshold
#
# For full documentation, visit:
# https://github.com/sense360store/esphome-public/blob/main/docs/installation.md
