---
substitutions:
  air_quality_topic: ${device_name}/air_quality
  # Provide MQTT credentials through substitutions or secrets; leave blank if your
  # broker does not require authentication.
  airiq_mqtt_username: ""
  airiq_mqtt_password: ""

packages:
  device_health: !include device_health.yaml

bme680_bsec:
  address: 0x77
  i2c_id: i2c0

external_components:
  - source:
      type: tar
      url: https://github.com/boschsensortec/BSEC2-ESPHome/archive/refs/tags/v1.4.2500.tar.gz
      path: BSEC2-ESPHome-1.4.2500/components
    components: [bme680_bsec]

sensor:
  - platform: bme680_bsec
    i2c_id: i2c0
    temperature:
      name: "${friendly_name} Temperature"
      accuracy_decimals: 1
    pressure:
      name: "${friendly_name} Pressure"
      accuracy_decimals: 1
    humidity:
      name: "${friendly_name} Humidity"
      accuracy_decimals: 1
    iaq:
      name: "${friendly_name} IAQ"
      id: ${device_name}_iaq
    co2_equivalent:
      name: "${friendly_name} eCO₂"
    breath_voc_equivalent:
      name: "${friendly_name} bVOC"

text_sensor:
  - platform: template
    id: air_quality_state
    name: "${friendly_name} Air Quality State"
    lambda: |-
      if (!id(${device_name}_iaq).has_state()) {
        return {"unknown"};
      }
      const float iaq = id(${device_name}_iaq).state;
      if (iaq < 50) {
        return {"excellent"};
      } else if (iaq < 100) {
        return {"good"};
      } else if (iaq < 150) {
        return {"lightly polluted"};
      } else if (iaq < 200) {
        return {"moderately polluted"};
      } else {
        return {"heavily polluted"};
      }
    update_interval: 60s

# To disable MQTT publishing when importing this profile, override `mqtt: null`
# in your product configuration. Provide credentials via substitutions or
# standard ESPHome secrets.
mqtt:
  broker: ${airiq_mqtt_broker}
  username: ${airiq_mqtt_username}
  password: ${airiq_mqtt_password}
  discovery: false
  topic_prefix: ${air_quality_topic}
