---
substitutions:
  air_quality_topic: ${device_name}/air_quality
  # Provide MQTT credentials through substitutions or secrets; leave blank if your
  # broker does not require authentication.
  airiq_mqtt_username: ""
  airiq_mqtt_password: ""

text_sensor:
  - platform: template
    id: air_quality_state
    name: "${friendly_name} Air Quality State"
    lambda: |-
      // Placeholder - no IAQ sensor configured
      return {"unknown"};
    update_interval: 60s

# To disable MQTT publishing when importing this profile, override `mqtt: null`
# in your product configuration. Provide credentials via substitutions or
# standard ESPHome secrets.
mqtt:
  broker: ${airiq_mqtt_broker}
  username: ${airiq_mqtt_username}
  password: ${airiq_mqtt_password}
  discovery: false
  topic_prefix: ${air_quality_topic}
