substitutions:
  air_quality_topic: ${device_name}/air_quality
  # =========================================================================
  # MQTT CONFIGURATION
  # =========================================================================
  # Set the broker address to enable MQTT publishing.
  # To disable MQTT entirely, set: mqtt: null in your device config.
  #
  # IMPORTANT: If your MQTT broker requires authentication (most do, including
  # Home Assistant's Mosquitto add-on), you MUST configure credentials.
  #
  # Option 1 - Set credentials via substitutions in your device config:
  #   substitutions:
  #     airiq_mqtt_broker: "192.168.x.x"
  #     airiq_mqtt_username: "your_mqtt_user"
  #     airiq_mqtt_password: "your_mqtt_password"
  #
  # Option 2 - Override mqtt block to use secrets.yaml:
  #   mqtt:
  #     username: !secret mqtt_username
  #     password: !secret mqtt_password
  #
  # Note: Empty username/password may cause authentication failures on
  # brokers that require credentials.
  # =========================================================================
  airiq_mqtt_broker: ""
  airiq_mqtt_port: "1883"
  airiq_mqtt_username: ""
  airiq_mqtt_password: ""

text_sensor:
  - platform: template
    id: air_quality_state
    name: "${friendly_name} Air Quality State"
    lambda: |-
      // Placeholder - no IAQ sensor configured
      return {"unknown"};
    update_interval: 60s

# To disable MQTT publishing when importing this profile, override `mqtt: null`
# in your product configuration. Provide credentials via substitutions or
# standard ESPHome secrets.
mqtt:
  broker: ${airiq_mqtt_broker}
  port: ${airiq_mqtt_port}
  username: ${airiq_mqtt_username}
  password: ${airiq_mqtt_password}
  discovery: false
  topic_prefix: ${air_quality_topic}
