---
# ============================================================================
# AIR QUALITY MONITORING - ADVANCED PROFILE
# ============================================================================
# Advanced air quality monitoring with full technical controls and sensors.
# Includes: All individual sensors (CO2, PM1.0, PM2.5, PM4.0, PM10, VOC, NOx)
#          Customizable thresholds for each sensor
#          Sensor calibration controls
#          Historical trends and statistics
# For technical users who want detailed monitoring and tuning capabilities.
# ============================================================================

# Include basic profile as foundation
packages:
  airiq_base: !include airiq_basic.yaml

substitutions:
  # Default thresholds (users can override these)
  # CO2 levels in parts per million (ppm)
  co2_good_limit: "750"
  co2_moderate_limit: "950"
  co2_unhealthy_limit: "1400"

  # Particulate Matter (PM) levels in µg/m³
  pm1_0_good_limit: "5"
  pm1_0_moderate_limit: "12"
  pm1_0_unhealthy_limit: "35"

  pm2_5_good_limit: "10"
  pm2_5_moderate_limit: "25"
  pm2_5_unhealthy_limit: "55"

  pm4_0_good_limit: "15"
  pm4_0_moderate_limit: "30"
  pm4_0_unhealthy_limit: "60"

  pm10_good_limit: "20"
  pm10_moderate_limit: "50"
  pm10_unhealthy_limit: "100"

  # VOC and NOx Index (0-500 scale)
  voc_good_limit: "80"
  voc_moderate_limit: "120"
  voc_unhealthy_limit: "180"

  nox_good_limit: "80"
  nox_moderate_limit: "120"
  nox_unhealthy_limit: "180"

# ----------------------------------------------------------------------------
# THRESHOLD GLOBALS - Store customizable limits
# ----------------------------------------------------------------------------
globals:
  # CO2 thresholds (ppm)
  - id: g_co2_good
    type: float
    restore_value: true
    initial_value: ${co2_good_limit}
  - id: g_co2_moderate
    type: float
    restore_value: true
    initial_value: ${co2_moderate_limit}
  - id: g_co2_unhealthy
    type: float
    restore_value: true
    initial_value: ${co2_unhealthy_limit}

  # PM2.5 thresholds (µg/m³) - Most important for health
  - id: g_pm25_good
    type: float
    restore_value: true
    initial_value: ${pm2_5_good_limit}
  - id: g_pm25_moderate
    type: float
    restore_value: true
    initial_value: ${pm2_5_moderate_limit}
  - id: g_pm25_unhealthy
    type: float
    restore_value: true
    initial_value: ${pm2_5_unhealthy_limit}

  # VOC thresholds
  - id: g_voc_good
    type: float
    restore_value: true
    initial_value: ${voc_good_limit}
  - id: g_voc_moderate
    type: float
    restore_value: true
    initial_value: ${voc_moderate_limit}
  - id: g_voc_unhealthy
    type: float
    restore_value: true
    initial_value: ${voc_unhealthy_limit}

# ----------------------------------------------------------------------------
# ALL SENSORS - CO2, PM, VOC, NOx, Environmental
# Note: These template sensors receive values via publish_state() from either
# expansion modules (airiq.yaml) or direct product sensor definitions.
# ----------------------------------------------------------------------------
sensor:
  # CO2 SENSOR - Carbon Dioxide (SCD4x)
  - platform: template
    id: co2_ppm
    name: "${friendly_name} CO₂"
    icon: "mdi:molecule-co2"
    unit_of_measurement: "ppm"
    accuracy_decimals: 0
    state_class: measurement
    device_class: carbon_dioxide

  # PARTICULATE MATTER SENSORS
  # PM1.0 - Finest particles
  - platform: template
    id: pm1_0
    name: "${friendly_name} PM1.0"
    icon: "mdi:blur"
    unit_of_measurement: "µg/m³"
    accuracy_decimals: 1
    state_class: measurement
    device_class: pm1

  # PM2.5 - Most health-relevant
  - platform: template
    id: pm2_5
    name: "${friendly_name} PM2.5"
    icon: "mdi:blur"
    unit_of_measurement: "µg/m³"
    accuracy_decimals: 1
    state_class: measurement
    device_class: pm25

  # PM4.0
  - platform: template
    id: pm4_0
    name: "${friendly_name} PM4.0"
    icon: "mdi:blur"
    unit_of_measurement: "µg/m³"
    accuracy_decimals: 1
    state_class: measurement

  # PM10 - Coarsest particles
  - platform: template
    id: pm10
    name: "${friendly_name} PM10"
    icon: "mdi:blur"
    unit_of_measurement: "µg/m³"
    accuracy_decimals: 1
    state_class: measurement
    device_class: pm10

  # VOC & NOx SENSORS
  # VOC Index (0-500)
  - platform: template
    id: voc_index
    name: "${friendly_name} VOC Index"
    icon: "mdi:chemical-weapon"
    unit_of_measurement: "index"
    accuracy_decimals: 0
    state_class: measurement
    device_class: volatile_organic_compounds

  # NOx Index (0-500)
  - platform: template
    id: nox_index
    name: "${friendly_name} NOx Index"
    icon: "mdi:smog"
    unit_of_measurement: "index"
    accuracy_decimals: 0
    state_class: measurement
    device_class: nitrogen_dioxide

  # ADDITIONAL ENVIRONMENTAL SENSORS
  # Atmospheric Pressure
  - platform: template
    id: atmospheric_pressure
    name: "${friendly_name} Pressure"
    icon: "mdi:gauge"
    unit_of_measurement: "hPa"
    accuracy_decimals: 1
    state_class: measurement
    device_class: atmospheric_pressure

  # Light Level (LTR303 sensor)
  - platform: template
    id: illuminance
    name: "${friendly_name} Illuminance"
    icon: "mdi:brightness-6"
    unit_of_measurement: "lx"
    accuracy_decimals: 0
    state_class: measurement
    device_class: illuminance

  # DIAGNOSTIC SENSORS
  # Air Quality Index (AQI) calculated from all sensors
  - platform: template
    id: calculated_aqi
    name: "${friendly_name} Air Quality Index"
    icon: "mdi:air-filter"
    unit_of_measurement: "AQI"
    accuracy_decimals: 0
    state_class: measurement
    update_interval: 60s
    lambda: |-
      // Calculate composite AQI from multiple sensors
      // This is a simplified calculation
      return id(overall_air_quality_index);

# ----------------------------------------------------------------------------
# ALL TEXT SENSORS - Level Classifications and Diagnostics
# ----------------------------------------------------------------------------
text_sensor:
  # CO2 Level Classification
  - platform: template
    id: co2_level
    name: "${friendly_name} CO₂ Level"
    icon: "mdi:gauge"
    update_interval: 30s
    lambda: |-
      if (!id(co2_ppm).has_state()) return {"unknown"};
      float co2 = id(co2_ppm).state;

      if (co2 < id(g_co2_good)) {
        return {"Good"};
      } else if (co2 < id(g_co2_moderate)) {
        return {"Moderate"};
      } else if (co2 < id(g_co2_unhealthy)) {
        return {"Unhealthy"};
      } else {
        return {"Poor"};
      }

  # PM2.5 Level Classification (most important)
  - platform: template
    id: pm25_level
    name: "${friendly_name} PM2.5 Level"
    icon: "mdi:gauge"
    update_interval: 30s
    lambda: |-
      if (!id(pm2_5).has_state()) return {"unknown"};
      float pm = id(pm2_5).state;

      if (pm < id(g_pm25_good)) {
        return {"Good"};
      } else if (pm < id(g_pm25_moderate)) {
        return {"Moderate"};
      } else if (pm < id(g_pm25_unhealthy)) {
        return {"Unhealthy"};
      } else {
        return {"Poor"};
      }

  # VOC Level Classification
  - platform: template
    id: voc_level
    name: "${friendly_name} VOC Level"
    icon: "mdi:gauge"
    update_interval: 30s
    lambda: |-
      if (!id(voc_index).has_state()) return {"unknown"};
      float voc = id(voc_index).state;

      if (voc < id(g_voc_good)) {
        return {"Good"};
      } else if (voc < id(g_voc_moderate)) {
        return {"Moderate"};
      } else if (voc < id(g_voc_unhealthy)) {
        return {"Unhealthy"};
      } else {
        return {"Poor"};
      }

  # Detailed diagnostics
  - platform: template
    id: sensor_diagnostics
    name: "${friendly_name} Sensor Diagnostics"
    icon: "mdi:information-outline"
    internal: true
    update_interval: 60s
    lambda: |-
      char buffer[512];
      snprintf(buffer, sizeof(buffer),
        "CO2: %.0f ppm | PM2.5: %.1f µg/m³ | VOC: %.0f | Temp: %.1f°C | RH: %.0f%%",
        id(co2_ppm).state,
        id(pm2_5).state,
        id(voc_index).state,
        id(room_temperature).state,
        id(room_humidity).state
      );
      return {buffer};

# ----------------------------------------------------------------------------
# CUSTOMIZABLE THRESHOLD CONTROLS
# ----------------------------------------------------------------------------
number:
  # CO2 Thresholds
  - platform: template
    id: co2_good_threshold
    name: "${friendly_name} CO₂ Good Limit"
    icon: "mdi:carbon-dioxide"
    unit_of_measurement: "ppm"
    min_value: 400
    max_value: 2000
    step: 50
    mode: box
    optimistic: true
    restore_value: true
    initial_value: ${co2_good_limit}
    on_value:
      then:
        - lambda: 'id(g_co2_good) = x;'

  - platform: template
    id: co2_moderate_threshold
    name: "${friendly_name} CO₂ Moderate Limit"
    icon: "mdi:carbon-dioxide"
    unit_of_measurement: "ppm"
    min_value: 400
    max_value: 2000
    step: 50
    mode: box
    optimistic: true
    restore_value: true
    initial_value: ${co2_moderate_limit}
    on_value:
      then:
        - lambda: 'id(g_co2_moderate) = x;'

  # PM2.5 Thresholds
  - platform: template
    id: pm25_good_threshold
    name: "${friendly_name} PM2.5 Good Limit"
    icon: "mdi:blur"
    unit_of_measurement: "µg/m³"
    min_value: 0
    max_value: 100
    step: 5
    mode: box
    optimistic: true
    restore_value: true
    initial_value: ${pm2_5_good_limit}
    on_value:
      then:
        - lambda: 'id(g_pm25_good) = x;'

  - platform: template
    id: pm25_moderate_threshold
    name: "${friendly_name} PM2.5 Moderate Limit"
    icon: "mdi:blur"
    unit_of_measurement: "µg/m³"
    min_value: 0
    max_value: 100
    step: 5
    mode: box
    optimistic: true
    restore_value: true
    initial_value: ${pm2_5_moderate_limit}
    on_value:
      then:
        - lambda: 'id(g_pm25_moderate) = x;'

  # VOC Threshold
  - platform: template
    id: voc_good_threshold
    name: "${friendly_name} VOC Good Limit"
    icon: "mdi:chemical-weapon"
    unit_of_measurement: "index"
    min_value: 0
    max_value: 500
    step: 10
    mode: box
    optimistic: true
    restore_value: true
    initial_value: ${voc_good_limit}
    on_value:
      then:
        - lambda: 'id(g_voc_good) = x;'

# ----------------------------------------------------------------------------
# CALIBRATION CONTROLS
# ----------------------------------------------------------------------------
button:
  # Force CO2 sensor calibration (400ppm baseline)
  - platform: template
    name: "${friendly_name} Calibrate CO₂ Sensor"
    icon: "mdi:tune-vertical"
    on_press:
      - logger.log: "CO2 sensor calibration initiated"
      # Actual calibration command will be added by hardware package

  # Reset all thresholds to defaults
  - platform: template
    name: "${friendly_name} Reset Thresholds"
    icon: "mdi:restore"
    on_press:
      - lambda: |-
          id(g_co2_good) = ${co2_good_limit};
          id(g_co2_moderate) = ${co2_moderate_limit};
          id(g_pm25_good) = ${pm2_5_good_limit};
          id(g_pm25_moderate) = ${pm2_5_moderate_limit};
          id(g_voc_good) = ${voc_good_limit};
          id(g_voc_moderate) = ${voc_moderate_limit};
          ESP_LOGI("airiq", "Thresholds reset to defaults");

# ----------------------------------------------------------------------------
# AUTO-VENTILATION LOGIC (Advanced)
# ----------------------------------------------------------------------------
script:
  - id: evaluate_air_quality
    mode: restart
    then:
      - lambda: |-
          // Calculate overall air quality index from all sensors
          float co2_score = 100.0f;
          float pm_score = 100.0f;
          float voc_score = 100.0f;

          // CO2 scoring
          if (id(co2_ppm).has_state()) {
            float co2 = id(co2_ppm).state;
            if (co2 < id(g_co2_good)) {
              co2_score = 100.0f;
            } else if (co2 < id(g_co2_moderate)) {
              co2_score = 75.0f;
            } else if (co2 < id(g_co2_unhealthy)) {
              co2_score = 50.0f;
            } else {
              co2_score = 25.0f;
            }
          }

          // PM2.5 scoring
          if (id(pm2_5).has_state()) {
            float pm = id(pm2_5).state;
            if (pm < id(g_pm25_good)) {
              pm_score = 100.0f;
            } else if (pm < id(g_pm25_moderate)) {
              pm_score = 75.0f;
            } else if (pm < id(g_pm25_unhealthy)) {
              pm_score = 50.0f;
            } else {
              pm_score = 25.0f;
            }
          }

          // VOC scoring
          if (id(voc_index).has_state()) {
            float voc = id(voc_index).state;
            if (voc < id(g_voc_good)) {
              voc_score = 100.0f;
            } else if (voc < id(g_voc_moderate)) {
              voc_score = 75.0f;
            } else if (voc < id(g_voc_unhealthy)) {
              voc_score = 50.0f;
            } else {
              voc_score = 25.0f;
            }
          }

          // Calculate weighted average (CO2 and PM2.5 are most important)
          float overall = (co2_score * 0.4f) + (pm_score * 0.4f) + (voc_score * 0.2f);
          id(overall_air_quality_index) = (int)overall;

          ESP_LOGD("airiq", "AQI: %d (CO2:%.0f, PM:%.0f, VOC:%.0f)",
            id(overall_air_quality_index), co2_score, pm_score, voc_score);

# Run evaluation periodically
interval:
  - interval: 60s
    then:
      - script.execute: evaluate_air_quality
