packages:
  # The base AirIQ profile publishes MQTT telemetry; set substitutions like
  # `airiq_mqtt_username`/`airiq_mqtt_password` or override `mqtt: null` in your
  # product config if you need to disable publishing.
  airiq_basic: !include airiq_basic_profile.yaml
  diagnostics: !include diagnostics.yaml

esphome:
  on_boot:
    - priority: 600
      then:
        - script.execute: auto_fan_control_startup

interval:
  - interval: 5min
    then:
      - logger.log:
          level: INFO
          format: "IAQ classification: %s"
          args: ['id(air_quality_state).state.c_str()']
      - script.execute: auto_fan_control

output:
  - platform: gpio
    id: fan_output
    pin: GPIO15

switch:
  - platform: output
    id: fan_switch
    output: fan_output
    name: "${friendly_name} Air Exchange"
    icon: "mdi:fan"
    restore_mode: RESTORE_DEFAULT_OFF

script:
  - id: auto_fan_control_startup
    mode: queued
    then:
      - script.execute: auto_fan_control
  - id: auto_fan_control
    mode: restart
    then:
      - if:
          condition:
            text_sensor.state:
              id: air_quality_state
              state: "heavily polluted"
          then:
            - switch.turn_on: fan_switch
          else:
            - switch.turn_off: fan_switch

text_sensor:
  - platform: template
    id: air_quality_change_monitor
    internal: true
    lambda: |-
      return id(air_quality_state).state;
    update_interval: 30s
    on_value:
      then:
        - script.execute: auto_fan_control
