# ============================================================================
# Mini Four LEDs - WS2812B Addressable LED Strip
# ============================================================================
# Hardware: 4x WS2812B LEDs in daisy chain
# Connection: GPIO8 via 74LVC1G07 level shifter (3.3V → 5V)
# ============================================================================

substitutions:
  # LED Configuration (can be overridden)
  led_data_pin: GPIO8
  led_count: "4"
  led_chipset: WS2812
  led_rgb_order: GRB

# ----------------------------------------------------------------------------
# WS2812B LED STRIP
# ----------------------------------------------------------------------------
light:
  - platform: esp32_rmt_led_strip
    id: status_leds
    name: "${friendly_name} Status LEDs"
    pin: ${led_data_pin}
    num_leds: ${led_count}
    chipset: ${led_chipset}
    rgb_order: ${led_rgb_order}
    default_transition_length: 250ms
    effects:
      - pulse:
          name: "Pulse"
          transition_length: 1s
          update_interval: 1s
      - addressable_rainbow:
          name: "Rainbow"
          speed: 10
          width: 50
      - addressable_color_wipe:
          name: "Color Wipe"
          colors:
            - red: 100%
              green: 0%
              blue: 0%
              num_leds: 1
            - red: 0%
              green: 100%
              blue: 0%
              num_leds: 1
            - red: 0%
              green: 0%
              blue: 100%
              num_leds: 1
          add_led_interval: 100ms
          reverse: false
      - addressable_scan:
          name: "Scan"
          move_interval: 100ms
          scan_width: 1
