---
# ============================================================================
# PRESENCE DETECTION - ADVANCED PROFILE (LD2412)
# ============================================================================
# Advanced presence detection for LD2412 mmWave sensor (Native ESPHome).
# Includes gate-based threshold configuration, engineering mode,
# calibration controls, and detailed energy/distance sensors.
#
# LD2412-specific features:
# - 14 detection gates (0-13) at configurable resolution
# - Distance resolution: 0.75m, 0.5m, or 0.2m
# - Engineering mode for detailed diagnostics
# - Dynamic background correction for auto-calibration
# - Superior still presence detection up to 9 meters
#
# Native ESPHome component documentation:
# https://esphome.io/components/sensor/ld2412
# ============================================================================

# Include basic profile as foundation
packages:
  presence_base: !include presence_basic.yaml

# ----------------------------------------------------------------------------
# DISTANCE & TIMEOUT CONTROLS (Native Number Platform)
# ----------------------------------------------------------------------------
number:
  # Presence timeout - how long to maintain presence after last detection
  - platform: ld2412
    ld2412_id: ld2412_radar
    timeout:
      name: "${friendly_name} Presence Timeout"
      icon: "mdi:timer"

  # Minimum detection gate (1-12)
  - platform: ld2412
    ld2412_id: ld2412_radar
    min_distance_gate:
      name: "${friendly_name} Min Distance Gate"
      icon: "mdi:arrow-collapse-right"

  # Maximum detection gate (2-13)
  - platform: ld2412
    ld2412_id: ld2412_radar
    max_distance_gate:
      name: "${friendly_name} Max Distance Gate"
      icon: "mdi:arrow-expand-right"

  # Light threshold for OUT pin activation
  - platform: ld2412
    ld2412_id: ld2412_radar
    light_threshold:
      name: "${friendly_name} Light Threshold"
      icon: "mdi:brightness-6"

sensor:
  # ----------------------------------------------------------------------------
  # DISTANCE & ENERGY SENSORS (User-facing) - Native ESPHome Copy Sensors
  # ----------------------------------------------------------------------------
  # Detection distance - Native copy from hardware sensor
  - platform: copy
    id: ld2412_distance_exposed
    source_id: ld2412_detection_distance
    name: "${friendly_name} Detection Distance"
    icon: "mdi:ruler"
    unit_of_measurement: "cm"
    accuracy_decimals: 0
    state_class: measurement

  # Moving energy - Native copy from hardware sensor
  - platform: copy
    id: ld2412_moving_energy_exposed
    source_id: ld2412_moving_energy
    name: "${friendly_name} Moving Energy"
    icon: "mdi:signal-variant"
    unit_of_measurement: "%"
    accuracy_decimals: 0
    state_class: measurement

  # Still energy - Native copy from hardware sensor
  - platform: copy
    id: ld2412_still_energy_exposed
    source_id: ld2412_still_energy
    name: "${friendly_name} Still Energy"
    icon: "mdi:signal"
    unit_of_measurement: "%"
    accuracy_decimals: 0
    state_class: measurement

  # Detection confidence level (0-100%) - Keep template for calculation
  - platform: template
    id: detection_confidence_level
    name: "${friendly_name} Detection Confidence"
    icon: "mdi:progress-check"
    unit_of_measurement: "%"
    accuracy_decimals: 1
    state_class: measurement
    update_interval: 1s
    lambda: |-
      return id(presence_confidence) * 100.0f;

# ----------------------------------------------------------------------------
# CONFIGURATION SELECTORS (Native Select Platform)
# ----------------------------------------------------------------------------
select:
  # Distance resolution (0.75m, 0.5m, 0.2m)
  - platform: ld2412
    ld2412_id: ld2412_radar
    distance_resolution:
      name: "${friendly_name} Distance Resolution"
      icon: "mdi:ruler-square"

  # OUT pin behavior (high/low when triggered)
  - platform: ld2412
    ld2412_id: ld2412_radar
    out_pin_level:
      name: "${friendly_name} OUT Pin Level"
      icon: "mdi:electric-switch"

  # Light function (off, below threshold, above threshold)
  - platform: ld2412
    ld2412_id: ld2412_radar
    light_function:
      name: "${friendly_name} Light Function"
      icon: "mdi:lightbulb-auto"

  # Sensitivity modes (template-controlled)
  - platform: template
    id: presence_sensitivity
    name: "${friendly_name} Presence Sensitivity"
    icon: "mdi:tune"
    optimistic: true
    options:
      - Quiet Room      # Low threshold - detects subtle movements
      - Normal          # Balanced for typical rooms
      - High Traffic    # High threshold - ignores minor movements
    initial_option: Normal
    restore_value: true
    on_value:
      then:
        - lambda: |-
            // Log sensitivity change
            if (x == "Quiet Room") {
              ESP_LOGI("presence", "Sensitivity: Quiet Room (high sensitivity)");
            } else if (x == "Normal") {
              ESP_LOGI("presence", "Sensitivity: Normal");
            } else if (x == "High Traffic") {
              ESP_LOGI("presence", "Sensitivity: High Traffic (low sensitivity)");
            }


# ----------------------------------------------------------------------------
# CONTROL SWITCHES (Native Switch Platform)
# ----------------------------------------------------------------------------
switch:
  # Engineering mode - enables detailed gate energy sensors
  - platform: ld2412
    ld2412_id: ld2412_radar
    engineering_mode:
      name: "${friendly_name} Engineering Mode"
      icon: "mdi:wrench"

  # Bluetooth control
  - platform: ld2412
    ld2412_id: ld2412_radar
    bluetooth:
      name: "${friendly_name} Radar Bluetooth"
      icon: "mdi:bluetooth"

# ----------------------------------------------------------------------------
# CALIBRATION & CONTROL BUTTONS (Native Button Platform)
# ----------------------------------------------------------------------------
button:
  # Factory reset - restore LD2412 to factory defaults
  - platform: ld2412
    ld2412_id: ld2412_radar
    factory_reset:
      name: "${friendly_name} Factory Reset"
      icon: "mdi:factory"

  # Restart the radar module
  - platform: ld2412
    ld2412_id: ld2412_radar
    restart:
      name: "${friendly_name} Radar Restart"
      icon: "mdi:restart"

  # Query current parameters from radar
  - platform: ld2412
    ld2412_id: ld2412_radar
    query_params:
      name: "${friendly_name} Query Parameters"
      icon: "mdi:refresh"

  # Start dynamic background correction (auto-calibration)
  - platform: ld2412
    ld2412_id: ld2412_radar
    start_dynamic_background_correction:
      name: "${friendly_name} Start Calibration"
      icon: "mdi:tune-vertical"

  # Reset presence confidence (template button)
  - platform: template
    name: "${friendly_name} Reset Presence Calibration"
    icon: "mdi:restart-alert"
    on_press:
      - lambda: |-
          id(presence_confidence) = 0.0f;
          ESP_LOGI("presence", "Presence calibration reset");

# ----------------------------------------------------------------------------
# SENSOR INFO
# ----------------------------------------------------------------------------
text_sensor:
  # Firmware version
  - platform: ld2412
    ld2412_id: ld2412_radar
    version:
      name: "${friendly_name} Radar Firmware"
      icon: "mdi:chip"

  # MAC address
  - platform: ld2412
    ld2412_id: ld2412_radar
    mac_address:
      name: "${friendly_name} Radar MAC"
      icon: "mdi:identifier"
      internal: true

  # Diagnostics
  - platform: template
    id: presence_diagnostics
    name: "${friendly_name} Presence Diagnostics"
    icon: "mdi:information-outline"
    internal: true
    update_interval: 5s
    lambda: |-
      char buffer[256];
      snprintf(buffer, sizeof(buffer),
        "Confidence: %.1f%%, Distance: %.0f cm, Moving: %s, Still: %s",
        id(presence_confidence) * 100.0f,
        id(ld2412_detection_distance).state,
        id(ld2412_has_moving).state ? "Yes" : "No",
        id(ld2412_has_still).state ? "Yes" : "No"
      );
      return {buffer};

# ----------------------------------------------------------------------------
# BINARY SENSORS (User-facing)
# ----------------------------------------------------------------------------
binary_sensor:
  # Dynamic background correction status (native)
  - platform: ld2412
    ld2412_id: ld2412_radar
    dynamic_background_correction_status:
      name: "${friendly_name} Calibration Active"
      icon: "mdi:tune"

  # Expose moving target detection - Copy from hardware sensor
  - platform: copy
    id: ld2412_moving_detected
    source_id: ld2412_has_moving
    name: "${friendly_name} Moving Detected"
    icon: "mdi:run"
    device_class: motion

  # Expose still target detection - Copy from hardware sensor
  - platform: copy
    id: ld2412_still_detected
    source_id: ld2412_has_still
    name: "${friendly_name} Still Detected"
    icon: "mdi:human-handsdown"
    device_class: occupancy
