# ============================================================================
# PRESENCE DETECTION - BASIC PROFILE
# ============================================================================
# Simple, user-friendly presence detection for most users.
# Shows: Room Occupied (Yes/No) and Presence Score (0-100%)
#
# NOTE: This profile does NOT define the presence_confidence global.
# The global is defined by the hardware/expansion module (presence_ceiling.yaml,
# presence_wall.yaml, presence_ld2450.yaml, or presence_ld2412.yaml).
# ============================================================================

packages:
  health: !include device_health.yaml

binary_sensor:
  - platform: template
    id: presence_binary
    name: "${friendly_name} Presence"
    device_class: occupancy
    lambda: |-
      return id(presence_confidence) > 0.3f;

sensor:
  - platform: template
    id: presence_score
    name: "${friendly_name} Presence Score"
    update_interval: 1s
    unit_of_measurement: "%"
    accuracy_decimals: 0
    lambda: |-
      return id(presence_confidence) * 100.0f;
