# /config/esphome/packages/features/device_health.yaml
# Generic device-health sensors (safe for ESP32-S3 w/ ESP-IDF)

sensor:
  - platform: internal_temperature
    name: "${friendly_name} Internal Temperature"

  - platform: uptime
    name: "${friendly_name} Uptime (s)"

  - platform: wifi_signal
    name: "${friendly_name} WiFi RSSI"
    update_interval: 30s

text_sensor:
  - platform: wifi_info
    ip_address:
      name: "${friendly_name} IP"
    ssid:
      name: "${friendly_name} SSID"
    bssid:
      name: "${friendly_name} BSSID"
    mac_address:
      name: "${friendly_name} MAC"

  - platform: version
    name: "${friendly_name} ESPHome Version"
    hide_timestamp: true
