# esphome/packages/features/presence_pro_profile.yaml
# Pro Presence (LD2450): full entities, tuning controls, and diagnostics.

binary_sensor:
  - platform: ld2450
    ld2450_id: ld2450_radar
    has_target:
      name: "${friendly_name} Presence"
      device_class: occupancy
    has_moving_target:
      name: "${friendly_name} Moving"
    has_still_target:
      name: "${friendly_name} Still"

sensor:
  - platform: ld2450
    ld2450_id: ld2450_radar

    target_count:
      name: "${friendly_name} Target Count"
    still_target_count:
      name: "${friendly_name} Still Count"
    moving_target_count:
      name: "${friendly_name} Moving Count"

    target_1:
      x:
        name: "${friendly_name} T1 X (mm)"
      y:
        name: "${friendly_name} T1 Y (mm)"
      speed:
        name: "${friendly_name} T1 Speed (mm/s)"
      angle:
        name: "${friendly_name} T1 Angle (°)"
      distance:
        name: "${friendly_name} T1 Distance (mm)"
      resolution:
        name: "${friendly_name} T1 Resolution (mm)"

    target_2:
      x:
        name: "${friendly_name} T2 X (mm)"
      y:
        name: "${friendly_name} T2 Y (mm)"
      speed:
        name: "${friendly_name} T2 Speed (mm/s)"
      angle:
        name: "${friendly_name} T2 Angle (°)"
      distance:
        name: "${friendly_name} T2 Distance (mm)"
      resolution:
        name: "${friendly_name} T2 Resolution (mm)"

    target_3:
      x:
        name: "${friendly_name} T3 X (mm)"
      y:
        name: "${friendly_name} T3 Y (mm)"
      speed:
        name: "${friendly_name} T3 Speed (mm/s)"
      angle:
        name: "${friendly_name} T3 Angle (°)"
      distance:
        name: "${friendly_name} T3 Distance (mm)"
      resolution:
        name: "${friendly_name} T3 Resolution (mm)"

    zone_1:
      target_count:
        name: "${friendly_name} Zone1 Count"
      still_target_count:
        name: "${friendly_name} Zone1 Still"
      moving_target_count:
        name: "${friendly_name} Zone1 Moving"

    zone_2:
      target_count:
        name: "${friendly_name} Zone2 Count"
      still_target_count:
        name: "${friendly_name} Zone2 Still"
      moving_target_count:
        name: "${friendly_name} Zone2 Moving"

    zone_3:
      target_count:
        name: "${friendly_name} Zone3 Count"
      still_target_count:
        name: "${friendly_name} Zone3 Still"
      moving_target_count:
        name: "${friendly_name} Zone3 Moving"

number:
  - platform: ld2450
    ld2450_id: ld2450_radar

    presence_timeout:
      name: "${friendly_name} Presence Timeout (s)"
      entity_category: config

    zone_1:
      x1: { name: "${friendly_name} Zone1 X1" }
      y1: { name: "${friendly_name} Zone1 Y1" }
      x2: { name: "${friendly_name} Zone1 X2" }
      y2: { name: "${friendly_name} Zone1 Y2" }

    zone_2:
      x1: { name: "${friendly_name} Zone2 X1" }
      y1: { name: "${friendly_name} Zone2 Y1" }
      x2: { name: "${friendly_name} Zone2 X2" }
      y2: { name: "${friendly_name} Zone2 Y2" }

    zone_3:
      x1: { name: "${friendly_name} Zone3 X1" }
      y1: { name: "${friendly_name} Zone3 Y1" }
      x2: { name: "${friendly_name} Zone3 X2" }
      y2: { name: "${friendly_name} Zone3 Y2" }

switch:
  - platform: ld2450
    ld2450_id: ld2450_radar
    bluetooth:
      name: "${friendly_name} Bluetooth"
      entity_category: config
    multi_target:
      name: "${friendly_name} Multi-Target"
      entity_category: config

select:
  - platform: ld2450
    ld2450_id: ld2450_radar
    baud_rate:
      name: "${friendly_name} Baud Rate"
      entity_category: config
    zone_type:
      name: "${friendly_name} Zone Type"
      entity_category: config

# Pull in shared diagnostics from the same folder
<<: !include diagnostics.yaml
