substitutions:
  friendly_name: Sense360 Mini Presence Advanced
  device_name: sense360-mini-presence-advanced
  timezone: "UTC"

packages:
  product: github://sense360/esphome-public/packages/products/sense360-mini-presence.yaml

esphome:
  name: ${device_name}
