substitutions:
  friendly_name: Sense360 Ceiling Presence Advanced
  device_name: sense360-ceiling-presence-advanced
  timezone: "UTC"

packages:
  product: github://sense360/esphome-public/packages/products/sense360-ceiling-presence.yaml

esphome:
  name: ${device_name}
