---
# ============================================================================
# SENSE360 COMFORT + PRESENCE PROFILE
# ============================================================================
# Smart room monitoring combining:
# - Presence detection (LD2450 or LD2412 radar)
# - Environmental comfort (Comfort module)
#
# This profile is designed for:
# - Smart home room monitoring
# - Office occupancy tracking
# - Automated lighting/HVAC triggers
# - Energy efficiency monitoring
#
# Hardware Requirements:
# - Sense360 Core board
# - LD2450 or LD2412 presence module
# - Comfort expansion (SHT40 + BH1750)
#
# Power Budget:
# - 3.3V Rail: ~250mA (MCU + comfort sensors)
# - 5V Rail:   ~100mA (presence radar)
#
# I2C Address Map (Primary Bus):
# - 0x23: BH1750 (light sensor)
# - 0x44: SHT40 (temp/humidity)
# - 0x76: BME680 (pressure - optional)
# ============================================================================

substitutions:
  device_name: sense360-comfort
  friendly_name: Sense360 Room Monitor
  device_version: "1.0.0"

  # Presence sensor type: "ld2450" or "ld2412"
  presence_sensor_type: "ld2450"

  # Override UART baud based on sensor type
  uart_presence_baud: "256000"  # LD2450: 256000, LD2412: 115200

# ============================================================================
# INCLUDE CORE AND MODULES
# ============================================================================
packages:
  # Core hardware mapping
  core: !include ../hardware/sense360_core_mapping.yaml

  # Power management
  power: !include ../hardware/power_management.yaml

  # Expansion modules - choose presence sensor
  presence: !include ../expansions/presence_ld2450.yaml
  comfort: !include ../expansions/comfort.yaml

# ============================================================================
# PROFILE-SPECIFIC CONFIGURATION
# ============================================================================

# Register modules with power management
esphome:
  on_boot:
    - priority: 500
      then:
        - lambda: |-
            // Register power consumption
            id(power_presence_module_ma) = 80.0f;  // LD2450
            id(power_5v_consumption) = 80.0f;

            id(power_comfort_module_ma) = 50.0f;  // SHT40 + BH1750
            id(power_3v3_consumption) = 150.0f + 50.0f;  // MCU + Comfort

            ESP_LOGI("comfort", "Comfort + Presence profile initialized");

# ============================================================================
# ROOM MONITORING LOGIC
# ============================================================================
globals:
  # Room state: 0=vacant, 1=occupied-active, 2=occupied-still
  - id: room_state
    type: int
    restore_value: false
    initial_value: '0'

  # Comfort score (0-100)
  - id: room_comfort_score
    type: float
    restore_value: false
    initial_value: '50.0'

  # Vacancy timeout (seconds)
  - id: vacancy_timeout
    type: int
    restore_value: true
    initial_value: '300'  # 5 minutes

  # Last occupancy timestamp
  - id: last_occupancy_time
    type: unsigned long
    restore_value: false
    initial_value: '0'

# ============================================================================
# EXPOSED SENSORS
# ============================================================================
sensor:
  # Room temperature
  - platform: template
    id: room_temperature
    name: "${friendly_name} Temperature"
    unit_of_measurement: "째C"
    device_class: temperature
    state_class: measurement
    accuracy_decimals: 1
    update_interval: 30s
    lambda: |-
      return id(comfort_temperature).state;

  # Room humidity
  - platform: template
    id: room_humidity
    name: "${friendly_name} Humidity"
    unit_of_measurement: "%"
    device_class: humidity
    state_class: measurement
    accuracy_decimals: 0
    update_interval: 30s
    lambda: |-
      return id(comfort_humidity).state;

  # Room illuminance
  - platform: template
    id: room_illuminance
    name: "${friendly_name} Illuminance"
    unit_of_measurement: "lx"
    device_class: illuminance
    state_class: measurement
    accuracy_decimals: 0
    update_interval: 10s
    lambda: |-
      return id(comfort_light_sensor).state;

  # Comfort index
  - platform: template
    id: room_comfort_index
    name: "${friendly_name} Comfort Index"
    unit_of_measurement: "%"
    accuracy_decimals: 0
    update_interval: 60s
    lambda: |-
      return id(comfort_index_value);
    icon: mdi:emoticon-happy

  # Dew point
  - platform: template
    id: room_dew_point
    name: "${friendly_name} Dew Point"
    unit_of_measurement: "째C"
    device_class: temperature
    state_class: measurement
    accuracy_decimals: 1
    update_interval: 60s
    lambda: |-
      return id(comfort_dew_point_value);

  # Heat index / feels like
  - platform: template
    id: room_heat_index
    name: "${friendly_name} Feels Like"
    unit_of_measurement: "째C"
    device_class: temperature
    state_class: measurement
    accuracy_decimals: 1
    update_interval: 60s
    lambda: |-
      return id(comfort_heat_index_value);

  # Occupancy count
  - platform: template
    id: room_occupancy_count
    name: "${friendly_name} Occupancy Count"
    unit_of_measurement: "people"
    accuracy_decimals: 0
    update_interval: 5s
    lambda: |-
      return (float)id(presence_people_count);

  # Closest person distance
  - platform: template
    id: room_closest_distance
    name: "${friendly_name} Closest Distance"
    unit_of_measurement: "m"
    accuracy_decimals: 2
    update_interval: 2s
    lambda: |-
      return id(presence_closest_distance);

# ============================================================================
# EXPOSED BINARY SENSORS
# ============================================================================
binary_sensor:
  # Room occupied
  - platform: template
    id: room_occupied
    name: "${friendly_name} Occupied"
    device_class: occupancy
    lambda: |-
      return id(room_state) > 0;

  # Movement detected
  - platform: template
    id: room_movement
    name: "${friendly_name} Movement"
    device_class: motion
    lambda: |-
      return id(room_state) == 1;  // Active movement

  # Light level adequate
  - platform: template
    id: room_light_adequate
    name: "${friendly_name} Light Adequate"
    device_class: light
    lambda: |-
      // Consider > 300 lux adequate for office work
      return id(comfort_light_sensor).state > 300.0f;

  # Comfort conditions good
  - platform: template
    id: room_comfort_good
    name: "${friendly_name} Comfort Good"
    lambda: |-
      return id(comfort_index_value) >= 70.0f;

# ============================================================================
# EXPOSED TEXT SENSORS
# ============================================================================
text_sensor:
  # Room state description
  - platform: template
    id: room_state_text
    name: "${friendly_name} Room State"
    icon: mdi:home-account
    update_interval: 5s
    lambda: |-
      switch (id(room_state)) {
        case 0: return {"Vacant"};
        case 1: return {"Occupied (Active)"};
        case 2: return {"Occupied (Still)"};
        default: return {"Unknown"};
      }

  # Light level category
  - platform: template
    id: room_light_category
    name: "${friendly_name} Light Level"
    icon: mdi:lightbulb
    update_interval: 10s
    lambda: |-
      switch (id(comfort_light_level)) {
        case 0: return {"Dark"};
        case 1: return {"Dim"};
        case 2: return {"Normal"};
        case 3: return {"Bright"};
        default: return {"Unknown"};
      }

  # Comfort recommendation
  - platform: template
    id: room_comfort_recommendation
    name: "${friendly_name} Comfort Recommendation"
    icon: mdi:information
    update_interval: 60s
    lambda: |-
      float temp = id(comfort_temperature).state;
      float humidity = id(comfort_humidity).state;
      float lux = id(comfort_light_sensor).state;

      std::string rec = "";

      // Temperature recommendations
      if (temp < 18.0f) {
        rec += "Room too cold. ";
      } else if (temp > 26.0f) {
        rec += "Room too warm. ";
      }

      // Humidity recommendations
      if (humidity < 30.0f) {
        rec += "Air too dry. ";
      } else if (humidity > 70.0f) {
        rec += "Air too humid. ";
      }

      // Light recommendations (only if occupied)
      if (id(room_state) > 0) {
        if (lux < 100.0f) {
          rec += "Light level low. ";
        }
      }

      if (rec.empty()) {
        return {"Conditions optimal"};
      }
      return rec;

# ============================================================================
# CONTROLS
# ============================================================================
number:
  # Vacancy timeout setting
  - platform: template
    id: room_vacancy_timeout
    name: "${friendly_name} Vacancy Timeout"
    unit_of_measurement: "s"
    min_value: 30
    max_value: 600
    step: 30
    optimistic: true
    restore_value: true
    set_action:
      - lambda: |-
          id(vacancy_timeout) = (int)x;
          ESP_LOGI("room", "Vacancy timeout set to %d seconds", (int)x);

# ============================================================================
# ROOM STATE LOGIC
# ============================================================================
interval:
  - interval: 1s
    then:
      - lambda: |-
          int targets = id(ld2450_target_count).state;
          int moving = id(ld2450_moving_count).state;
          int still = id(ld2450_still_count).state;
          unsigned long now = millis();

          if (targets > 0) {
            // Someone is present
            id(last_occupancy_time) = now;

            if (moving > 0) {
              // Active movement
              id(room_state) = 1;
            } else if (still > 0) {
              // Still presence (someone sitting/sleeping)
              id(room_state) = 2;
            } else {
              // Generic presence
              id(room_state) = 1;
            }
          } else {
            // No one detected - check vacancy timeout
            unsigned long elapsed = now - id(last_occupancy_time);
            if (elapsed > (id(vacancy_timeout) * 1000)) {
              id(room_state) = 0;  // Vacant
            }
            // Keep current state during timeout period
          }

  - interval: 30s
    then:
      - lambda: |-
          // Log room status
          ESP_LOGD("room", "State: %d, Temp: %.1f째C, Humidity: %.0f%%, Light: %.0f lx, Comfort: %.0f%%",
            id(room_state),
            id(comfort_temperature).state,
            id(comfort_humidity).state,
            id(comfort_light_sensor).state,
            id(comfort_index_value));
