---
# ============================================================================
# SENSE360 FULL HVAC PROFILE
# ============================================================================
# Complete HVAC monitoring and control configuration combining:
# - Presence detection (LD2450 radar)
# - Air quality monitoring (AirIQ module)
# - Environmental comfort (Comfort module)
# - Fan control via GP8403 DAC
# - Multi-channel 12V fan control via SX1509 expander
#
# This profile is designed for:
# - Commercial HVAC systems
# - Server room cooling
# - Smart building ventilation
# - Industrial climate control
#
# Hardware Requirements:
# - Sense360 Core board
# - LD2450 presence module
# - AirIQ expansion (SEN55 + SCD41)
# - Comfort expansion (SHT40 + BH1750)
# - GP8403 DAC module
# - SX1509 GPIO expander
# - 12V power supply for fans
#
# Power Budget:
# - 3.3V Rail: ~400mA (MCU + sensors + expander)
# - 5V Rail:   ~200mA (presence radar)
# - 12V Rail:  ~2000mA (4x fans at 50% duty)
#
# I2C Address Map (Primary Bus):
# - 0x23: BH1750 (light sensor)
# - 0x44: SHT40 (temp/humidity)
# - 0x58: GP8403 (fan DAC)
# - 0x62: SCD41 (CO2)
# - 0x69: SEN55 (PM/VOC/NOx)
# - 0x76: BME680 (pressure - optional)
#
# I2C Address Map (Secondary Bus):
# - 0x3E: SX1509 (GPIO expander)
# ============================================================================

substitutions:
  device_name: sense360-hvac
  friendly_name: Sense360 HVAC Controller
  device_version: "1.0.0"

  # Override UART baud for LD2450
  uart_presence_baud: "256000"

  # Fan control settings
  fan_auto_mode_enabled: "true"
  fan_temp_setpoint: "24"  # Target temperature in Celsius

# ============================================================================
# INCLUDE CORE AND MODULES
# ============================================================================
packages:
  # Core hardware mapping
  core: !include ../hardware/sense360_core_mapping.yaml

  # Power management
  power: !include ../hardware/power_management.yaml

  # Expansion modules
  presence: !include ../expansions/presence_ld2450.yaml
  airiq: !include ../expansions/airiq.yaml
  comfort: !include ../expansions/comfort.yaml
  fan_dac: !include ../expansions/fan_gp8403.yaml
  gpio_expander: !include ../expansions/gpio_expander_sx1509.yaml
  fan_12v: !include ../expansions/fan_12v_pwm.yaml

# ============================================================================
# PROFILE-SPECIFIC CONFIGURATION
# ============================================================================

# Register modules with power management
esphome:
  on_boot:
    - priority: 500
      then:
        - lambda: |-
            // Register power consumption for each module
            // Presence: 80mA on 5V rail
            id(power_presence_module_ma) = 80.0f;
            id(power_5v_consumption) = 80.0f;

            // AirIQ: 150mA on 3.3V rail (SEN55 + SCD41)
            id(power_airiq_module_ma) = 150.0f;

            // Comfort: 50mA on 3.3V rail (SHT40 + BH1750)
            id(power_comfort_module_ma) = 50.0f;

            // Fan DAC: 20mA on 3.3V rail
            id(power_fan_dac_module_ma) = 20.0f;

            // GPIO Expander: 30mA on 3.3V rail
            id(power_expander_module_ma) = 30.0f;

            // Recalculate 3.3V total
            id(power_3v3_consumption) = 150.0f + 150.0f + 50.0f + 20.0f + 30.0f;  // ~400mA

            ESP_LOGI("hvac", "HVAC profile initialized - all modules registered");

# ============================================================================
# HVAC CONTROL LOGIC
# ============================================================================
globals:
  # HVAC mode: 0=off, 1=cooling, 2=heating, 3=auto
  - id: hvac_mode
    type: int
    restore_value: true
    initial_value: '3'  # Auto mode

  # Temperature setpoint
  - id: hvac_setpoint
    type: float
    restore_value: true
    initial_value: '${fan_temp_setpoint}'

  # Deadband (hysteresis)
  - id: hvac_deadband
    type: float
    restore_value: false
    initial_value: '1.0'

  # Fan speed override (-1 = auto)
  - id: hvac_fan_override
    type: int
    restore_value: true
    initial_value: '-1'

# ============================================================================
# HVAC SENSORS (exposed to Home Assistant)
# ============================================================================
sensor:
  # Current temperature (from Comfort module SHT40)
  - platform: template
    id: hvac_current_temperature
    name: "${friendly_name} Temperature"
    unit_of_measurement: "°C"
    device_class: temperature
    state_class: measurement
    accuracy_decimals: 1
    update_interval: 30s
    lambda: |-
      return id(comfort_temperature).state;

  # Current humidity (from Comfort module SHT40)
  - platform: template
    id: hvac_current_humidity
    name: "${friendly_name} Humidity"
    unit_of_measurement: "%"
    device_class: humidity
    state_class: measurement
    accuracy_decimals: 0
    update_interval: 30s
    lambda: |-
      return id(comfort_humidity).state;

  # Air quality index (from AirIQ module)
  - platform: template
    id: hvac_aqi
    name: "${friendly_name} Air Quality Index"
    unit_of_measurement: "AQI"
    accuracy_decimals: 0
    update_interval: 60s
    lambda: |-
      return (float)id(airiq_aqi_value);

  # CO2 level (from AirIQ module)
  - platform: template
    id: hvac_co2
    name: "${friendly_name} CO2"
    unit_of_measurement: "ppm"
    device_class: carbon_dioxide
    state_class: measurement
    accuracy_decimals: 0
    update_interval: 30s
    lambda: |-
      return id(airiq_co2).state;

  # Occupancy count (from Presence module)
  - platform: template
    id: hvac_occupancy_count
    name: "${friendly_name} Occupancy Count"
    unit_of_measurement: "people"
    accuracy_decimals: 0
    update_interval: 5s
    lambda: |-
      return (float)id(presence_people_count);

  # Total fan power (from 12V fans)
  - platform: template
    id: hvac_fan_power
    name: "${friendly_name} Fan Power"
    unit_of_measurement: "W"
    device_class: power
    state_class: measurement
    accuracy_decimals: 1
    update_interval: 10s
    lambda: |-
      return id(fan_12v_total_power).state;

# ============================================================================
# HVAC BINARY SENSORS
# ============================================================================
binary_sensor:
  # Room occupied (based on presence detection)
  - platform: template
    id: hvac_room_occupied
    name: "${friendly_name} Occupied"
    device_class: occupancy
    lambda: |-
      return id(presence_people_count) > 0;

  # Ventilation needed (based on CO2 levels)
  - platform: template
    id: hvac_ventilation_needed
    name: "${friendly_name} Ventilation Needed"
    device_class: problem
    lambda: |-
      // CO2 > 1000 ppm indicates poor ventilation
      return id(airiq_co2).state > 1000.0f;

  # Air quality alert (based on AQI)
  - platform: template
    id: hvac_air_quality_alert
    name: "${friendly_name} Air Quality Alert"
    device_class: problem
    lambda: |-
      // AQI > 100 is unhealthy for sensitive groups
      return id(airiq_aqi_value) > 100;

# ============================================================================
# HVAC CONTROLS
# ============================================================================
number:
  # Temperature setpoint
  - platform: template
    id: hvac_setpoint_control
    name: "${friendly_name} Temperature Setpoint"
    unit_of_measurement: "°C"
    min_value: 16
    max_value: 30
    step: 0.5
    optimistic: true
    restore_value: true
    set_action:
      - lambda: |-
          id(hvac_setpoint) = x;
          ESP_LOGI("hvac", "Setpoint changed to %.1f°C", x);

  # Fan speed override
  - platform: template
    id: hvac_fan_speed_override
    name: "${friendly_name} Fan Speed Override"
    unit_of_measurement: "%"
    min_value: -1
    max_value: 100
    step: 5
    optimistic: true
    restore_value: true
    set_action:
      - lambda: |-
          id(hvac_fan_override) = (int)x;
          if (x < 0) {
            ESP_LOGI("hvac", "Fan speed set to AUTO");
          } else {
            ESP_LOGI("hvac", "Fan speed override set to %d%%", (int)x);
          }

select:
  # HVAC mode selection
  - platform: template
    id: hvac_mode_select
    name: "${friendly_name} Mode"
    options:
      - "Off"
      - "Cooling"
      - "Heating"
      - "Auto"
    initial_option: "Auto"
    optimistic: true
    restore_value: true
    set_action:
      - lambda: |-
          if (x == "Off") id(hvac_mode) = 0;
          else if (x == "Cooling") id(hvac_mode) = 1;
          else if (x == "Heating") id(hvac_mode) = 2;
          else if (x == "Auto") id(hvac_mode) = 3;
          ESP_LOGI("hvac", "HVAC mode changed to %s", x.c_str());

# ============================================================================
# HVAC CONTROL SCRIPT
# ============================================================================
script:
  - id: hvac_control_loop
    mode: single
    then:
      - lambda: |-
          // Skip if mode is off
          if (id(hvac_mode) == 0) {
            // Turn off all fans
            auto call0 = id(sx1509_fan_0).turn_off();
            call0.perform();
            auto call1 = id(sx1509_fan_1).turn_off();
            call1.perform();
            return;
          }

          float current_temp = id(comfort_temperature).state;
          float setpoint = id(hvac_setpoint);
          float deadband = id(hvac_deadband);
          int fan_speed = 0;

          // Check for manual override
          if (id(hvac_fan_override) >= 0) {
            fan_speed = id(hvac_fan_override);
          } else {
            // Auto mode: calculate fan speed based on temperature deviation
            float temp_diff = current_temp - setpoint;

            if (id(hvac_mode) == 1 || id(hvac_mode) == 3) {  // Cooling or Auto
              if (temp_diff > deadband) {
                // Cooling needed - scale fan speed with temperature difference
                fan_speed = std::min(100, (int)(30 + (temp_diff - deadband) * 20));
              } else if (temp_diff > 0) {
                // Slightly warm - low speed
                fan_speed = 30;
              }
            }

            // Boost ventilation if CO2 is high
            if (id(airiq_co2).state > 1200.0f && fan_speed < 50) {
              fan_speed = 50;  // Minimum 50% for ventilation
              ESP_LOGD("hvac", "Boosting fan for CO2 ventilation");
            }

            // Boost if AQI is high
            if (id(airiq_aqi_value) > 100 && fan_speed < 60) {
              fan_speed = 60;  // Boost for air quality
              ESP_LOGD("hvac", "Boosting fan for air quality");
            }

            // Reduce speed if room is unoccupied (energy saving)
            if (id(presence_people_count) == 0 && fan_speed > 30) {
              fan_speed = 30;  // Low speed when unoccupied
              ESP_LOGD("hvac", "Reducing fan speed - room unoccupied");
            }
          }

          // Apply fan speed
          if (fan_speed == 0) {
            auto call0 = id(sx1509_fan_0).turn_off();
            call0.perform();
            auto call1 = id(sx1509_fan_1).turn_off();
            call1.perform();
          } else {
            auto call0 = id(sx1509_fan_0).turn_on();
            call0.set_speed(fan_speed);
            call0.perform();
            auto call1 = id(sx1509_fan_1).turn_on();
            call1.set_speed(fan_speed);
            call1.perform();
          }

          ESP_LOGD("hvac", "HVAC: temp=%.1f, setpoint=%.1f, fan=%d%%",
                   current_temp, setpoint, fan_speed);

# ============================================================================
# HVAC CONTROL INTERVAL
# ============================================================================
interval:
  - interval: 30s
    then:
      - script.execute: hvac_control_loop

  - interval: 60s
    then:
      # Update 12V fan temperature input for auto mode
      - script.execute:
          id: fan_12v_set_temperature
          temperature: !lambda 'return id(comfort_temperature).state;'
