substitutions:
  friendly_name: Sense360 Mini Presence
  device_name: sense360-mini-presence-basic
  timezone: "UTC"

packages:
  base: !include ../../packages/base/complete.yaml
  hardware: !include ../../packages/hardware/sense360_core_mini.yaml
  presence_sensor: !include ../../packages/hardware/presence_ld2450.yaml
  profile: !include ../../packages/features/presence_basic_profile.yaml
