substitutions:
  friendly_name: Sense360 Mini AirIQ
  device_name: sense360-mini-airiq-basic
  timezone: "UTC"

packages:
  wifi: !include ../../packages/base/wifi.yaml
  api: !include ../../packages/base/api_encrypted.yaml
  ota: !include ../../packages/base/ota.yaml
  logging: !include ../../packages/base/logging.yaml
  time: !include ../../packages/base/time.yaml
  hardware: !include ../../packages/hardware/sense360_core_mini.yaml
  profile: !include ../../packages/features/airiq_basic_profile.yaml
